### ISSUE TITLE
bug: Public Client lacks custom muticall contract address setting option

### ISSUE THREAD

**Issue by okeyzero** [wagmi-dev/viem#1003]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.5.3

### Current Behavior

The custom muticall contract address setting option is missing here
https://viem.sh/docs/clients/public.html#eth-call-aggregation-via-multicall

But here is the option to customise the muticall contract address settings
https://viem.sh/docs/contract/multicall.html#multicalladdress-optional

### Expected Behavior

```javascript
const client = createPublicClient({
  batch: {
    multicall: {
      multicallAddress: '0xca11bde05977b3631167028862be2a173976ca11',
    },
  },
  chain: mainnet,
  transport: http(),
})

```

### Steps To Reproduce

N/A

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

N/A

### Anything else?

N/A

**Comment by tmm** [comment]
Addresses in Viem are typically "chain-driven" - in this case, if you want to specify a custom multicall3 address, you should update it on the chain (e.g. set `mainnet.contracts.multicall3.address`). For example:

```ts
const customMainnet = {
  ...mainnet,
  contracts: {
    ...mainnet.contracts,
    multicall3: {
      address: '0xca11bde05977b3631167028862be2a173976ca11',
    },
  },
}

const client = createPublicClient({
  chain: customMainnet,
  transport: http(),
})
```

Does that make sense?
