### ISSUE TITLE
bug: watchContractEvent missing multiple logs from same transaction #2880

### ISSUE THREAD

**Issue by illestrater** [wagmi-dev/viem#1014]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.5.4

### Current Behavior

Upon listening for logs with watchContractEvent, a single log is emitted and "duplicates" seem to be removed.

### Expected Behavior

My contract is written to emit multiple of the same logs, with varying return data. I should expect multiple of these logs to be caught by the event listener as it's written in my contract to emit these "duplicates" intentionally

### Steps To Reproduce

Using watchContractEvent or useContractEvent on contract events that is emitted multiple times in a single transaction.

**Comment by jxom** [comment]
Can you please provide a minimal reproducible example via https://new.viem.sh?

Hard to tell what’s going on without an ABI.

**Comment by tmm** [comment]
No worries! Thanks for going through the process and congrats on figuring it out.
