### ISSUE TITLE
bug: wrong typings

### ISSUE THREAD

**Issue by jrocca82** [wagmi-dev/viem#1016]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.5.4

### Current Behavior

Package doesn't build due to incorrect syntax in typing with extensions.

### Expected Behavior

`T<const TypeOne extends TypeTwo> `should be `T<TypeOne extends TypeTwo>` this issue is located in several places, such as the Client type and ABI typings.

### Steps To Reproduce

Package does not build in a typscript project.

**Comment by jxom** [comment]
This is TypeScript’s `const` generic keyword. Please make sure you have upgraded to TypeScript 5.
