### ISSUE TITLE
bug: getContract type error on optimism

### ISSUE THREAD

**Issue by sakulstra** [wagmi-dev/viem#1018]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.6.0

### Current Behavior

Hey i just upgraded from an quite outdated viem version and started getting type-errors on `optimism`
![image](https://github.com/wagmi-dev/viem/assets/4396533/646b44ec-f376-4879-bbad-d31ac83d6436)

All other chains appear to be fine.
![image](https://github.com/wagmi-dev/viem/assets/4396533/3ca4441f-a035-4702-b802-4674241b0bb8)

I checked the changelog and couldn't find anything.

Optimism in this case is simply defined as:
```
export const optimismClient = createPublicClient({
  chain: optimism,
  transport: http(process.env.RPC_OPTIMISM),
});
```
The type-error seems to be coming from a return type mismatch on `getBlock`.

### Expected Behavior

optimism should work

### Steps To Reproduce

I tried to create a reproduction, but didn't manage to.
Any idea what could be the reason(probably it's just me being stupid).

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/edit/viem-getting-started-vvjus6?file=index.ts,package.json

**Comment by jxom** [comment]
Weird you can’t reproduce on StackBlitz. Can you share the type error? Also can you try on [TypeScript Playground](https://www.typescriptlang.org/play)? You should be able to just copy and paste the code (the playground will auto import the modules).

**Comment by jxom** [comment]
Weird you can’t reproduce on StackBlitz. Can you share the type error? Also can you try on [TypeScript Playground](https://www.typescriptlang.org/play)? You should be able to just copy and paste the code (the playground will auto import the modules).

**Comment by sakulstra** [comment]
@jxom on [typescript playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgYygUwIYzQBQK4BGANsMgMIloB2MANHABYwxj0DmaMZENUGy8AL5wAZlAgg4AcgBuwNCCkBuAFChIsRHAhgYoYAGcQ9EBmBUqnOMLETpchQHpkDM1QPKVK5DwPxT5pZclDRwALwo6Fi4hCTkITAAFAgqcCiu5gBccAEWnLSpcDB87how2UwsiQCUBYLVqt6+8Dp6IIYgFPKhEaiY2PjEpF3USSlpLm7ZrfpGBWnFGKXQ5YzMYDV1DV5oAB5lKM05bkEAortoyHgw0Ny8-PARHFw8iwLJhRgAJl-oBgbZKQABl2fgYUnmcAwBGA2QA2gBdSFgWLDBLZXJBEY0LaNPYHHzuFq6WYgc6Xa63V58AThODPO5vMafH5-AHSEFgiGfGHwpGFFFDeLdVYzdpGbF0FT1VRAA
) seems like there are problems with resolving the types from viem/chains

Here is the full typescript error:
```
Type '{ account: undefined; batch?: { multicall?: boolean | { batchSize?: number | undefined; wait?: number | undefined; } | undefined; } | undefined; cacheTime: number; chain: Assign<{ readonly id: 10; ... 5 more ...; readonly contracts: { ...; }; }, ChainConfig<...>>; ... 47 more ...; extend: <const client extends { ......' is not assignable to type '{ account: undefined; batch?: { multicall?: boolean | { batchSize?: number | undefined; wait?: number | undefined; } | undefined; } | undefined; cacheTime: number; chain: Chain | undefined; ... 47 more ...; extend: <const client extends { ...; }>(fn: (client: Client<...>) => client) => Client<...>; }'.
  The types returned by 'getBlock(...)' are incompatible between these types.
    Type 'Promise<GetBlockReturnType<Assign<{ readonly id: 10; readonly name: "OP Mainnet"; readonly network: "optimism"; readonly nativeCurrency: { readonly name: "Ether"; readonly symbol: "ETH"; readonly decimals: 18; }; readonly rpcUrls: { ...; }; readonly blockExplorers: { ...; }; readonly contracts: { ...; }; }, ChainCon...' is not assignable to type 'Promise<GetBlockReturnType<Chain | undefined, any, any>>'.
      Type 'GetBlockReturnType<Assign<{ readonly id: 10; readonly name: "OP Mainnet"; readonly network: "optimism"; readonly nativeCurrency: { readonly name: "Ether"; readonly symbol: "ETH"; readonly decimals: 18; }; readonly rpcUrls: { ...; }; readonly blockExplorers: { ...; }; readonly contracts: { ...; }; }, ChainConfig<...>...' is not assignable to type 'GetBlockReturnType<Chain | undefined, any, any>'.
        Type 'GetBlockReturnType<Assign<{ readonly id: 10; readonly name: "OP Mainnet"; readonly network: "optimism"; readonly nativeCurrency: { readonly name: "Ether"; readonly symbol: "ETH"; readonly decimals: 18; }; readonly rpcUrls: { ...; }; readonly blockExplorers: { ...; }; readonly contracts: { ...; }; }, ChainConfig<...>...' is not assignable to type '{ transactions: `0x${string}`[] | ({ from: `0x${string}`; gas: bigint; nonce: number; to: `0x${string}` | null; value: bigint; r: `0x${string}`; s: `0x${string}`; v: bigint; gasPrice: bigint; maxFeePerGas?: undefined; maxPriorityFeePerGas?: undefined; ... 8 more ...; transactionIndex: number | null; } | { ...; } | {...'.
          Types of property 'transactions' are incompatible.
            Type '`0x${string}`[] | ({ from: `0x${string}`; gas: bigint; nonce: number; to: `0x${string}` | null; value: bigint; r: `0x${string}`; s: `0x${string}`; v: bigint; gasPrice: bigint; maxFeePerGas?: undefined; maxPriorityFeePerGas?: undefined; ... 11 more ...; transactionIndex: number | null; } | ... 6 more ... | { ...; })[]' is not assignable to type '`0x${string}`[] | ({ from: `0x${string}`; gas: bigint; nonce: number; to: `0x${string}` | null; value: bigint; r: `0x${string}`; s: `0x${string}`; v: bigint; gasPrice: bigint; maxFeePerGas?: undefined; maxPriorityFeePerGas?: undefined; ... 8 more ...; transactionIndex: number | null; } | { ...; } | { ...; })[]'.
              Type '({ from: `0x${string}`; gas: bigint; nonce: number; to: `0x${string}` | null; value: bigint; r: `0x${string}`; s: `0x${string}`; v: bigint; gasPrice: bigint; maxFeePerGas?: undefined; maxPriorityFeePerGas?: undefined; ... 11 more ...; transactionIndex: number | null; } | ... 6 more ... | { ...; })[]' is not assignable to type '`0x${string}`[] | ({ from: `0x${string}`; gas: bigint; nonce: number; to: `0x${string}` | null; value: bigint; r: `0x${string}`; s: `0x${string}`; v: bigint; gasPrice: bigint; maxFeePerGas?: undefined; maxPriorityFeePerGas?: undefined; ... 8 more ...; transactionIndex: number | null; } | { ...; } | { ...; })[]'.
                Type '({ from: `0x${string}`; gas: bigint; nonce: number; to: `0x${string}` | null; value: bigint; r: `0x${string}`; s: `0x${string}`; v: bigint; gasPrice: bigint; maxFeePerGas?: undefined; maxPriorityFeePerGas?: undefined; ... 11 more ...; transactionIndex: number | null; } | ... 6 more ... | { ...; })[]' is not assignable to type '`0x${string}`[]'.
                  Type '{ from: `0x${string}`; gas: bigint; nonce: number; to: `0x${string}` | null; value: bigint; r: `0x${string}`; s: `0x${string}`; v: bigint; gasPrice: bigint; maxFeePerGas?: undefined; maxPriorityFeePerGas?: undefined; ... 11 more ...; transactionIndex: number | null; } | ... 6 more ... | { ...; }' is not assignable to type '`0x${string}`'.
                    Type '{ from: `0x${string}`; gas: bigint; nonce: number; to: `0x${string}` | null; value: bigint; r: `0x${string}`; s: `0x${string}`; v: bigint; gasPrice: bigint; maxFeePerGas?: undefined; maxPriorityFeePerGas?: undefined; ... 11 more ...; transactionIndex: number | null; }' is not assignable to type '`0x${string}`'.ts(2322)
getContract.d.ts(31, 5): The expected type comes from property 'publicClient' which is declared here on type 'GetContractParameters<Transport, Chain | undefined, Account | undefined, readonly [{ readonly inputs: readonly [{ readonly internalType: "address"; readonly name: "ovmL2CrossDomainMessenger"; readonly type: "address"; }, ... 5 more ..., { ...; }]; readonly stateMutability: "nonpayable"; readonly type: "constructor";...'
```

**Comment by tmm** [comment]
Looks like an issue with `typescript@5.1.6`. If you use `typescript@5.0.4` should work correctly.

Have a PR open that should fix this https://github.com/wagmi-dev/viem/pull/1017

**Comment by thomas-waite** [comment]
This is not working either for me and does not look fixed. Should be re-opened

**Comment by jxom** [comment]
@thomas-waite – can you please open a new issue with a minimal reproducible example via [TypeScript Playground](https://www.typescriptlang.org/play)?

FWIW, I can't reproduce OP's issue here: https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbzgYygUwIYzQBQK4BGANsMgMIloB2MANHABYwxj0DmaMZENUGy8AL5wAZlAgg4AcgBuwNCCkBuAFChIsRHAhgYoYAGcQ9EBmBUqnOMLETpchQHpkDM1QPKVK5DwPxT5pZclDRwALwo6Fi4hCTkITAAFAgqcCiu5gBccAEWnLSpcDB87how2UwsiQCUBYLVqt6+8Dp6IIYgFPKhEaiY2PjEpF3USSlpLm7ZrfpGBWnFGKXQ5YzMYDV1DV5oAB5lKM05bkEAortoyHgw0Ny8-PARHFw8iwLJhRgAJl-oBgbZKQABl2fgYUnmcAwBGA2QA2gBdSHIBLZXJBEY0LaNPYHHzuFq6WYgc6Xa63V58AThODPO5vMafH5-AHSEFgiGfGHwpGFFHdVYzdpGTF0FT1VRAA
