### ISSUE TITLE
Failed to Build with Yarn: Type error: Type parameter declaration expected.

### ISSUE THREAD

**Issue by Kaldrogh** [wagmi-dev/viem#1020]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.6.0

### Current Behavior

![image](https://github.com/wagmi-dev/viem/assets/22390211/4973f81a-eee0-42f2-be97-5554973b3104)

### Expected Behavior

To pass the build successfuly

**Comment by jxom** [comment]
You will need to upgrade to TypeScript 5.
