### ISSUE TITLE
bug: addChain functionality not supported

### ISSUE THREAD

**Issue by blackpintz** [wagmi-dev/viem#1024]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.6.0

### Current Behavior

I am trying to add chain or switch chain but I keep getting this error:

```
buildRequest.ts:131 Uncaught UnknownRpcError: An unknown RPC error occurred.

Details: Request method wallet_addEthereumChain is not supported
Version: viem@1.5.4
```
Mind you, I am using viem version 1.6.0.

```


### Expected Behavior

_No response_

### Steps To Reproduce


const walletClient = createWalletClient({
	chain: mainnet,
	transport: custom(window.ethereum!),
})

const add = await walletClient.addChain({ chain: polygonMumbai }) 
```

### Anything else?

I want to switch to polygon network and then proceed to do a `sendtransaction` on the polygon network.

**Comment by tmm** [comment]
What wallet are you using? Wallets are not required to support `wallet_addEthereumChain`, which is likely what this error message means.

**Comment by blackpintz** [comment]
Hey, I am using metamask wallet. So how should I get around it?

**Comment by tmm** [comment]
Hard to tell without knowing more info. Can you put together a minimal reproduction with steps to follow, then I can re-open this issue and look into it.

**Comment by blackpintz** [comment]
Hey, I have recreated the issue here, https://github.com/blackpintz/Viem-bug-report. I am trying to switch the chain to polygon and the error pops up. It is blocking me from calling a send transaction. 

Steps:

1.` yarn`
2. `yarn run dev`
3. Open the local browser and view the error on the console.

PS: I am using a metamask wallet.

**Comment by tmm** [comment]
Your wallet needs to be connected in order to call this method. Doesn’t look like there’s a way to do that in the minimal example.
