### ISSUE TITLE
bug: TransactionReceiptNotFoundError: Transaction receipt with hash 

### ISSUE THREAD

**Issue by qnxdev** [wagmi-dev/viem#1056]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.2.9

### Current Behavior

TransactionReceiptNotFoundError: Transaction receipt with hash "0x6d90d7e90e50773d6462a287a7c17a8a73559aae2183ee97f42aad2a345d834b" could not be found. The Transaction may not be processed on a block yet.  Version: viem@1.2.10     at getTransactionReceipt (getTransactionReceipt.js:33:1)     at async Object.onBlockNumber (waitForTransactionReceipt.js:122:1)

waitForTransactionReceipt is supposed to wait for txn instead of throwin err right?

### Expected Behavior

Wait and return txn data

### Steps To Reproduce

This my piece of code

`
          const tx = await client.waitForTransactionReceipt({ hash });`

**Comment by jxom** [comment]
This is typically due to using a Public RPC Provider or RPC Provider that has aggressive load balancing & caching. Can you try the same with Alchemy, Infura, QuickNode or Ankr?

**Comment by prometx11** [comment]
What is the suggested solution for dapps where you need to access rpcs in the frontend? 
Anyone could abuse the private RPC key if shared on the frontend. 

This issue seems less common with Ethersjs, any idea why?

**Comment by jxom** [comment]
RPC API keys are designed to be used in the browser. You should be using the RPC Provider’s API key whitelisting to properly secure your key against abuse.

**Comment by ZimM-LostPolygon** [comment]
For me, this is happening even on a reliable private RPC. Here's the network requests sequence I'm seeing:
1. `eth_getTransactionByHash` succeeds, returns the transaction data.
2. `eth_getTransactionReceipt` returns `null`.
3. `eth_getBlockByNumber` with the transaction's block number succeeds, returns list of transactions that includes the one being awaited.
4. `eth_getTransactionReceipt` is called again, returns `null`, at which point TransactionReceiptNotFoundError is thrown.

This sequence looks somewhat odd, but since this seems to happen on any RPC, I believe this should still be handled gracefully. The alternative is to just put a loop with a `try..catch` block, but that's exactly the thing the library should be handling.

**Comment by jxom** [comment]
Please open a new issue with a minimal reproducible example.

**Comment by aptum11** [comment]
Experiencing the same.

**Comment by jxom** [comment]
https://github.com/wevm/viem/issues/1056#issuecomment-1916113234

**Comment by aptum11** [comment]
```
  const { writeContractAsync } = useWriteContract();


        const minABI = [
          {
            constant: false,
            inputs: [
              {
                name: "_to",
                type: "address",
              },
              {
                name: "_value",
                type: "uint256",
              },
            ],
            name: "transfer",
            outputs: [
              {
                name: "",
                type: "bool",
              },
            ],
            payable: false,
            stateMutability: "nonpayable",
            type: "function",
          },
        ];
        const amountToSend = parseUnits(
          depositTokenInfo.tokenInput,
          depositTokenInfo.tokenDecimals
        );
        const hash = await writeContractAsync({
          abi: minABI,
          address: address1,
          functionName: "transfer",
          args: [address2, amountToSend],
        });
        await publicClient.waitForTransactionReceipt({
          hash,
        });
  ```

**Comment by seanbhart** [comment]
experiencing the same issue. any update on the timeline for a fix?

**Comment by jxom** [comment]
Locking issue as replying without a minimal reproducible example isn’t helpful for anyone.

Please open a new issue with a minimal reproducible example.
