### ISSUE TITLE
bug: window.ethereum check

### ISSUE THREAD

**Issue by jrocca82** [wagmi-dev/viem#1079]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.5.4

### Current Behavior

Instantiating Viem (ie. creating a public clien) currently requires a window.ethereum object, or it will throw errors.  This is counterintuitive, as the client should not require a window.ethereum object in order to read contract functions.

### Expected Behavior

Standard practice on etherscan and in ethers.js do not require wallet connections to read contract functions, but are being required by viem, as read functions are not accessible without the viem client, but the viem client is only accessible when there is a window.ethereum object.

Alternatively, documents should be updated to make developers aware of this behavior, as it was difficult to debug.

### Steps To Reproduce

Trying to instantiate viem in a mobile browser or while in incognito mode will not work until after a user has connected their wallet. 

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://labrys-soulbound-j0x6kshr4-labrys.vercel.app/

**Comment by jxom** [comment]
You do not need `window.ethereum` or the `custom` transport to read contract functions. You can just use the `http` transport:

```ts
import { createPublicClient, http } from 'viem'
import { mainnet } from 'viem/chains'

const client = createPublicClient({
  chain: mainnet,
  transport: http(),
})

const value = await client.readContract({ ... })
```
