### ISSUE TITLE
bug: watchEvent dies after 30s when using Bun

### ISSUE THREAD

**Issue by rayzr522** [wagmi-dev/viem#1084]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.9.0

### Current Behavior

when using [Bun](https://bun.sh/) to run a simple script that uses `client.watchEvent` to listen for on-chain events, the process consistently dies within ~30 seconds (usually 31-33s, so presumably a few seconds for init & then there's some kind of timeout at play)

e.x.:
```bash
$ time bun .
0xC303159De48B82C5dB0901DBaAde73aba21Df9f1 minted 32 on 0x0c700fe23ae289677003ec8244b5b6c612318ebe
0x3D6fEb003dF39E2DbEe3448Fa88B7ce32Be413f8 minted 67 on 0x943ee07eb7d19d83906d59624d6407470fffbffa
0x3D6fEb003dF39E2DbEe3448Fa88B7ce32Be413f8 minted 68 on 0x943ee07eb7d19d83906d59624d6407470fffbffa
0x3D6fEb003dF39E2DbEe3448Fa88B7ce32Be413f8 minted 69 on 0x943ee07eb7d19d83906d59624d6407470fffbffa
0x3D6fEb003dF39E2DbEe3448Fa88B7ce32Be413f8 minted 70 on 0x943ee07eb7d19d83906d59624d6407470fffbffa
0x3D6fEb003dF39E2DbEe3448Fa88B7ce32Be413f8 minted 71 on 0x943ee07eb7d19d83906d59624d6407470fffbffa
0x3D6fEb003dF39E2DbEe3448Fa88B7ce32Be413f8 minted 72 on 0x943ee07eb7d19d83906d59624d6407470fffbffa
0x3D6fEb003dF39E2DbEe3448Fa88B7ce32Be413f8 minted 73 on 0x943ee07eb7d19d83906d59624d6407470fffbffa
0x3D6fEb003dF39E2DbEe3448Fa88B7ce32Be413f8 minted 74 on 0x943ee07eb7d19d83906d59624d6407470fffbffa
0x3D6fEb003dF39E2DbEe3448Fa88B7ce32Be413f8 minted 75 on 0x943ee07eb7d19d83906d59624d6407470fffbffa
0x3D6fEb003dF39E2DbEe3448Fa88B7ce32Be413f8 minted 76 on 0x943ee07eb7d19d83906d59624d6407470fffbffa
bun .  0.16s user 0.06s system 0% cpu 33.343 total
```

### Expected Behavior

the process should run indefinitely until killed, as it does when being run with Node

### Steps To Reproduce

to repro:
1. clone the repro repo
2. `bun install`
3. `bun run index.ts`

the repo is effectively just:
```ts
client.watchEvent({
  event: {
    // https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC721/IERC721.sol#L15
    name: "Transfer",
    type: "event",
    inputs: [
      { type: "address", name: "from", indexed: true },
      { type: "address", name: "to", indexed: true },
      { type: "uint256", name: "tokenId", indexed: true },
    ],
  },
  args: {
    from: "0x0000000000000000000000000000000000000000",
  },
  strict: true,

  onLogs(logs) {
    for (const log of logs) {
      console.log(
        `${log.args.to} minted ${log.args.tokenId} on ${log.address}`,
      );
    }
  },
});
```
if you run this with bun (`bun run index.ts`) the process exits silently after ~30s, but if you run it via node (easiest is `pnpm dlx tsx index.ts`, or you could use npx & ts-node, makes no difference) the process runs indefinitely as expected.

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://github.com/rayzr522/viem-bun-watch-issue

### Anything else?

im using Bun 0.8.1 (the latest version as of rn)

i took a brief glance thru the codebase and my understanding is that viem uses isomorphic-ws under the hood, which by extension should be using Bun's `WebSocket` impl in the global namespace. i tried making a simple websocket server & client using both Bun's WebSocket impl directly & via isomorphic-ws, and in both cases it ran forever and never exited.

so my guess is that the issue isnt with the WebSocket impl itself, but maybe something in the `withTimeout` function? but it seems to be something in the viem-specific code, not in isomorphic-ws or other libs

**Comment by tansanDOTeth** [comment]
This would make sense with someone of results I shared here #534

**Comment by jxom** [comment]
Let’s track here: https://github.com/oven-sh/bun/issues/3065

**Comment by junhuang-ho** [comment]
Issue still persists on viem 1.18.9. Possibly dependent on this: https://github.com/oven-sh/bun/issues/6686

**Comment by Markeljan** [comment]
`bun upgrade --canary` seems to fix this or at least makes the memory leak way more manageable.
