### ISSUE TITLE
bug: Missing Trie Node when calling simulateContract at specific Block number

### ISSUE THREAD

**Issue by Loris-EPFL** [wagmi-dev/viem#1092]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.3.18

### Current Behavior

I have the following code (see on StackBlitz for reproductible example) which uses simulateContract to simulate a write interraction with a contract at speicific block numbers (via the optional argument blockNumber) : 

`const { result  } : any = await publicClient.simulateContract({
        address: uniswapPolygonManagerAdress,
        abi: UNISWAP_MANAGER_ABI,
        functionName: 'collect',
        account: owner as `0x${string}`,
        blockNumber : BigInt(currBlock),
        args : [[tokenID, owner, amount0, amount1]]
      }) `

This works fine and give me accurate data for some/most block numbers, but i have this error sometimes : 

`ContractFunctionExecutionError: An error occurred while executing: missing trie node 79d976fb2280254e05a3ffc807591a7a8c363303e902138e7e1ce8a84e538b29 (path )

Raw Call Arguments:
  from:  0x221deacaebdd6ce7a789a105bf4f0441597935d6
  to:    0xc36442b4a4522e871399cd717abdd847ab11fe88
  data:  0xfc6f7865000000000000000000000000000000000000000000000000000000000001ff1a000000000000000000000000221deacaebdd6ce7a789a105bf4f0441597935d6000000000000000000000000000000000000000000000000001fffffffffffff000000000000000000000000000000000000000000000000001fffffffffffff
 
Contract Call:
  address:   0xc36442b4a4522e871399cd717abdd847ab11fe88
  function:  collect((uint256 tokenId, address recipient, uint128 amount0Max, uint128 amount1Max))
  args:             (["130842","0x221deacaebdd6ce7a789a105bf4f0441597935d6","9007199254740991","9007199254740991"])
  sender:    0x221deacaebdd6ce7a789a105bf4f0441597935d6

Docs: https://viem.sh/docs/contract/simulateContract.html
Details: missing trie node 79d976fb2280254e05a3ffc807591a7a8c363303e902138e7e1ce8a84e538b29 (path )
Version: viem@0.3.18`

### Expected Behavior

From what i looked on the internet, it looks like it may be due to viem / the rpc provider not fully indexing every block, leading to some sort of uncomplete data fetch at specific block numbers, hence the error. Any idea on how i could fix this issue ?

Thanks in advance !

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/edit/viem-getting-started-h2jnxp?file=index.ts

**Comment by jxom** [comment]
Yeah, this seems like an RPC Provider issue to me. Can you try using a different RPC URL and see if it still happens? viem does not do any indexing of sorts, so I don't think it is an issue in viem.

**Comment by Loris-EPFL** [comment]
Changing rpc to ankr worked and solved the issue, thanks for everything !

> Yeah, this seems like an RPC Provider issue to me. Can you try using a different RPC URL and see if it still happens? viem does not do any indexing of sorts, so I don't think it is an issue in viem.
