### ISSUE TITLE
bug: get "Expected 0 arguments, but got 1." type error on `encodeFunctionData` function 

### ISSUE THREAD

**Issue by moojing** [wagmi-dev/viem#1156]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.10.3

### Current Behavior

when I use `viem` with create-react-app, and use the code below 
```
  import { encodeFunctionData } from "viem";
  import { Abi } from "./abi";
  ...
  const data = encodeFunctionData({
    abi: Abi,
    functionName: "approve",
    args: [oneInchSpender, amount],
  });
```

I'll get the error `Expected 0 arguments, but got 1.`from create-react-app , but I don't see any error in my VSCode, and when I remove the parameter within this function, the error on the web page is gone, but the type error in the VSCode will show up. ( this can be expected).

<img width="817" alt="Screenshot 2023-09-06 at 4 48 00 PM" src="https://github.com/wagmi-dev/viem/assets/11360957/0fbc7a43-0547-4235-9b43-8949ec58f1ca">

### Expected Behavior

there should not be any error with this function when I pass the parameter into it.

### Steps To Reproduce

use the code below 
```
  import { encodeFunctionData } from "viem";
  import { Abi } from "./abi"; // erc20 abi
  ... 
  const data = encodeFunctionData({
    abi: Abi,
    functionName: "approve",
    args: ["0x1223.....", amount],
  });
```

and run the project.

### Anything else?

no

**Comment by jxom** [comment]
Works okay for me: https://www.typescriptlang.org/play?target=99#code/JYWwDg9gTgLgBAbzgUwHYGMIBNkDECuGMwEqAIgIYwVwC+cAZlBCHAOQBuwyIbAUKEixEKKOgBMABgCCAI2B1GzVmwryYATzDIA9DGQBnGPz5pMOAkRLkqFABQI+cOGuAAuURJnyANE8aE6MSkAHIUIMgeqmBgzBzIbH7OFFAA5gYeANpskgAeiXAAjKgAuny0AJRAA

Can you please fork that playground and reproduce the issue there? Thanks! Will reopen when a reproduction is provided.
