### ISSUE TITLE
bug: New public RPC introduced by #1153 doesn't work as expected

### ISSUE THREAD

**Issue by liarco** [wagmi-dev/viem#1165]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.10.4

### Current Behavior

Create a public client for Mumbai Testner (`createPublicClient({ chain: polygonMumbai, transport: http() })`), most calls will fail (we noticed this while trying to verify some signatures with the publicClient API. This doesn't happen with a custom RPC endpoint so the one introduced by #1153 might be bugged.

### Expected Behavior

Public RPC should return valid responses.

### Steps To Reproduce

```typescript
import { createPublicClient, http } from 'viem';
import { polygonMumbai } from 'viem/chains';

(async () =>{
  const defaultClient = createPublicClient({ chain: polygonMumbai, transport: http() });

  // Fails
  console.log([await defaultClient.getChainId(), await defaultClient.getBlockNumber()]);
})();
```

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://github.com/liarco/viem-bug-verifySignature-reproducer

**Comment by jxom** [comment]
Not ideal at all! Fixed via d828894abedcd4eb8a35f04825858f27140fbe2c.
