### ISSUE TITLE
bug: gnosis chiado has bad configuration 

### ISSUE THREAD

**Issue by begmaroman** [wagmi-dev/viem#1168]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.10.4

### Current Behavior

https://github.com/wagmi-dev/viem/blob/main/src/chains/definitions/gnosisChiado.ts#L3

testnet: true field is missing in the gnosis chiado chain config

### Expected Behavior

https://github.com/wagmi-dev/viem/blob/main/src/chains/definitions/gnosisChiado.ts#L3

testnet: true must be present

### Steps To Reproduce

-

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

-

### Anything else?

-

**Comment by jxom** [comment]
Fixed via #1170.
