### ISSUE TITLE
bug: Websocket not working due to commit  f33086e

### ISSUE THREAD

**Issue by kliyer-ai** [wagmi-dev/viem#1174]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.10.7

### Current Behavior

An error when using the websocket transport:

![image](https://github.com/wagmi-dev/viem/assets/27199575/2bea7b26-c65a-4b12-884f-de575b3292e5)

### Expected Behavior

No error

### Steps To Reproduce

```
  const transport = webSocket("...");

  const provider = createPublicClient({
    chain: arbitrum,
    transport: transport,
  });

  const bn = await provider.getBlockNumber();
  console.log(bn);
```

**Comment by kliyer-ai** [comment]
Okay I did some research and this commit breaks it: https://github.com/wagmi-dev/viem/commit/f33086ef88a1c9650b2b0efa6a034490519eead8

I downgraded the package version and now it works.

**Comment by jxom** [comment]
Runtimes & bundlers are cursed... Will fix

**Comment by jxom** [comment]
Can you let me know if `viem@0.0.0-jxom-fix-ws.20230908T031511` fixes this issue? If so, I'll release.
