### ISSUE TITLE
bug: Cannot Deploy Contract

### ISSUE THREAD

**Issue by Iamknownasfesal** [wagmi-dev/viem#1179]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.6.0

### Current Behavior

I connect to my metamask via W3Modal(which is Wallet Connect) and then deploy contract with it(via wagmi), code:

```ts
let client = await getWalletClient();
let hash = await client?.deployContract({
  abi: state.contract.abi as Abi,
  bytecode: `0x${state.contract.opcode}`,
  value: parseEther("0.1"),
  chain: polygonMumbai,
  args: [parseEther("0.1")],
});
```

When i submit this to the metamask and approve, it stays in submitted status. Which is odd. What am i doing wrong here?
(state.contract.abi and state.contract.opcode are correct in this context)

My constructor:

`{"inputs":[{"internalType":"uint256","name":"value","type":"uint256"}],"stateMutability":"payable","type":"constructor"}`

### Expected Behavior

Should be able to run this transaction? IDK how to pronounce this

**Comment by jxom** [comment]
Thanks for reporting. Can you please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) via https://new.viem.sh or a separate repo? It will save us a lot of time reproducing your config & environment, and trying to reproduce your issue. See [Why reproductions are required](https://antfu.me/posts/why-reproductions-are-required).

Please reopen this issue when a reproduction is added.
