### ISSUE TITLE
bug: Incorrect signature generated when signing bytes<n> data types

### ISSUE THREAD

**Issue by kyscott18** [wagmi-dev/viem#1180]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.10.8

### Current Behavior

When signing a eip712 message that contains bytes<N> data types, the incorrect signature is generated. 

### Expected Behavior

I expect the recovered address from recovering the signer address from the signature and data to be the same as the address used to sign the message.

### Steps To Reproduce

Signing and then immediately recovering the signer should always return the address used to sign. Solidity signature verification libraries should be able to verify that the signature is correct. 

The example shows that signing and recovering don't give the same address out. After a lot of debugging, I am pretty confident that the signing is the part that is broken and not the decoding. Recovering the signing address using solidity will return the same address as the viem `recoverTypedDataAddress()` function. Also this only applies to non-zero bytes which makes me think it has something to do with zero padding but not sure.

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://github.com/kyscott18/viem-signing-bug

### Anything else?

```sh
$ bun run src/index.ts                                                   
Signer:  0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
Zero bytes recovered signer:  0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
Non-zero bytes recovered signer:  0xDA4f98DabB81ea0392EB5A6664be8038758c3D1B
```

**Comment by jxom** [comment]
Thanks for flagging! This is an issue that resides upstream in Anvil's JSON-RPC implementation of `eth_signTypedData_v4`, have posted an issue here: https://github.com/foundry-rs/foundry/issues/5803
