### ISSUE TITLE
bug: Transaction could not be found although successful

### ISSUE THREAD

**Issue by pedromcunha** [wagmi-dev/viem#1187]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.6.7

### Current Behavior

Our SDK observes the transaction using viem until it succeeds or fails. In this case the transaction succeeded but viem reported that the transaction could not be found. Here's a [jam video](https://jam.dev/c/5efbdcb4-9278-4e1f-8f67-9ab38fcbe200) detailing the api requests/responses and the console logs. You can also test this in our [production environment](https://explorer.reservoir.tools), although it's not always reproducible.

### Expected Behavior

If the transaction was submitted and successful it should have been found by viem, even if it needed to poll until it was found.

### Steps To Reproduce

The jam video should be enough to get the conversation going.

**Comment by jxom** [comment]
Curious if this still happens when you use an alternative RPC provider (not a public one)? This issue mostly arises due to load balancing issues on the RPC provider.

**Comment by jxom** [comment]
Going to close this for now as usually the solution is to use a different RPC provider (can achieve with viem’s `fallback` Transport). Let me know if the issue still persists after that.

**Comment by pedromcunha** [comment]
Thanks, this makes sense, going to give that a try.
