### ISSUE TITLE
bug: Block type missing withdrawals

### ISSUE THREAD

**Issue by sakulstra** [wagmi-dev/viem#1189]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.10.4

### Current Behavior

The `Block` type is missing `withdrawalsRoot` and `withdrawals`.

### Expected Behavior

Block type should contain withdrawals

### Steps To Reproduce

  const block = await publicClient.getBlock({ blockHash });

### Anything else?

Also i'd like to draw some attention to https://github.com/wagmi-dev/viem/discussions/1172. When migrating to viem, noticed that this particular feature is missing and afaik also not mentioned on the migration guide.

Currently working around via `return publicClient.request({ method: 'eth_getProof' as any, params: [address, slots, toHex(block.number)] as any });` but having this native would be great.

**Comment by jxom** [comment]
Will be fixed in 1.16!
