### ISSUE TITLE
documentation: add includeTransactions as parameter for watchBlocks

### ISSUE THREAD

**Issue by sunmer** [wagmi-dev/viem#1190]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.10.9

### Anything else?

`includeTransactions` isn't documented as an optional parameter for watchBlocks
Should be added to
https://github.com/wagmi-dev/viem/blob/85826b51c505336998de11d6943a617ad1bc0d91/site/docs/actions/public/watchBlocks.md?plain=1#L66

**Comment by sunmer** [comment]
As a caveat, it seems as if includeTransactions returns `undefined` when using websocket connections (I'm on Quicknode).

**Comment by jxom** [comment]
Fixed docs!
