### ISSUE TITLE
bug: addChain method adds a duplicate network if the RPC URL is different than in metamask

### ISSUE THREAD

**Issue by VampishWolf** [wagmi-dev/viem#1193]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.2.14

### Current Behavior

addChain method adds a duplicate network if the RPC URL is different than in metamask. This issue doesn't exist when using wagmi method.

### Expected Behavior

The chain should be checked on the basis of chainId in the wallet before adding a new duplicate network

### Steps To Reproduce

Steps to reproduce -
- When no chain present on metamask, added chain with addChain method followed by switchChain to switch the network
- Go to metamask networks, and change the RPC URL and switch to a different network.
- Now when running the same code logic, it ends up adding a duplicate chain in metamask with it's own RPC link.

`try {
      await walletClient!.addChain({
        chain: availableChains[selectedChain.network],
      })
      await walletClient!.switchChain({ id: +selectedChain.id })
    } catch (error) {
      console.error(error)
    }`

**Comment by tmm** [comment]
Interesting that MetaMask behaves that way. Seems more of an issue there than with Viem.

**Comment by jxom** [comment]
Best to raise this on MetaMask side as this is more behavior a wallet should handle (we can’t check if the chain is already in the wallet). Weird that this works in wagmi as it’s using the same RPC calls.
