### ISSUE TITLE
bug: run viem inside a Snap: hangs upon read

### ISSUE THREAD

**Issue by firnprotocol** [wagmi-dev/viem#1213]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.10.14

### Current Behavior

I am an able to load viem inside of a [MetaMask Snap](https://github.com/MetaMask/snaps), but **unable to read from the blockchain.**

i have developed a minimal MWE in [this single commit](https://github.com/firnprotocol/template-snap-monorepo/commit/ca2b95cdb24e2570cc059afcbbab043c5e0191f7#diff-b47c5a03603aff4a5a42a6d4ef569a9a62d86f260004c519871d0e26a4276803), which builds off of MetaMask's [snap template repo](https://github.com/firnprotocol/template-snap-monorepo).

**Symptoms.**

- when I do a normal call, either using `publicClient.readContract` or `contract.read.myMethod`, the call **hangs indefinitely**, until it times out and is killed by metamask. see e.g. [this code](https://github.com/firnprotocol/template-snap-monorepo/blob/ca2b95cdb24e2570cc059afcbbab043c5e0191f7/packages/snap/src/index.ts#L21-L32).
- bizarrely, i was able to make progress by explicitly doing a [`publicClient.multicall`](https://viem.sh/docs/contract/multicall.html). see [this code](https://github.com/firnprotocol/template-snap-monorepo/blob/ca2b95cdb24e2570cc059afcbbab043c5e0191f7/packages/snap/src/index.ts#L34-L49). upon running that multicall, i got a large error, which can be seen below:
<details>
<summary>Expand error dump</summary>
[{"status":"failure","error":{"details":"Provided value is not JSON-RPC compatible: Expected the value to satisfy a union of , but received: [object Object].","docsPath":"/docs/contract/readContract","metaMessages":["Raw Call Arguments:"," to: 0xca11bde05977b3631167028862be2a173976ca11\n data: 0x82ad56cb00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000e0000000000000000000000000fba3912ca04dd458c843e2ee08967fc04f3579c200000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000000418160ddd00000000000000000000000000000000000000000000000000000000000000000000000000000000fba3912ca04dd458c843e2ee08967fc04f3579c200000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000002470a08231000000000000000000000000a5cc3c03994db5b0d9a5eedd10cabab0813678ac00000000000000000000000000000000000000000000000000000000"," ","Contract Call:"," address: 0xca11bde05977b3631167028862be2a173976ca11\n function: aggregate3((address target, bool allowFailure, bytes callData)[])\n args: ([{"allowFailure":true,"callData":"0x18160ddd","target":"0xFBA3912Ca04dd458c843e2EE08967fC04f3579c2"},{"allowFailure":true,"callData":"0x70a08231000000000000000000000000a5cc3c03994db5b0d9a5eedd10cabab0813678ac","target":"0xFBA3912Ca04dd458c843e2EE08967fC04f3579c2"}])"],"shortMessage":"An unknown RPC error occurred.","name":"ContractFunctionExecutionError","version":"viem@1.10.12","message":"An unknown RPC error occurred.\n\nRaw Call Arguments:\n to: 0xca11bde05977b3631167028862be2a173976ca11\n data: 0x82ad56cb00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000e0000000000000000000000000fba3912ca04dd458c843e2ee08967fc04f3579c200000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000000418160ddd00000000000000000000000000000000000000000000000000000000000000000000000000000000fba3912ca04dd458c843e2ee08967fc04f3579c200000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000002470a08231000000000000000000000000a5cc3c03994db5b0d9a5eedd10cabab0813678ac00000000000000000000000000000000000000000000000000000000\n \nContract Call:\n address: 0xca11bde05977b3631167028862be2a173976ca11\n function: aggregate3((address target, bool allowFailure, bytes callData)[])\n args: ([{"allowFailure":true,"callData":"0x18160ddd","target":"0xFBA3912Ca04dd458c843e2EE08967fC04f3579c2"},{"allowFailure":true,"callData":"0x70a08231000000000000000000000000a5cc3c03994db5b0d9a5eedd10cabab0813678ac","target":"0xFBA3912Ca04dd458c843e2EE08967fC04f3579c2"}])\n\nDocs: https://viem.sh/docs/contract/readContract.html\nDetails: Provided value is not JSON-RPC compatible: Expected the value to satisfy a union of , but received: [object Object].\nVersion: viem@1.10.12","cause":{"details":"Provided value is not JSON-RPC compatible: Expected the value to satisfy a union of , but received: [object Object].","metaMessages":["Raw Call Arguments:"," to: 0xca11bde05977b3631167028862be2a173976ca11\n data: 0x82ad56cb00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000e0000000000000000000000000fba3912ca04dd458c843e2ee08967fc04f3579c200000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000000418160ddd00000000000000000000000000000000000000000000000000000000000000000000000000000000fba3912ca04dd458c843e2ee08967fc04f3579c200000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000002470a08231000000000000000000000000a5cc3c03994db5b0d9a5eedd10cabab0813678ac00000000000000000000000000000000000000000000000000000000"],"shortMessage":"An unknown RPC error occurred.","name":"CallExecutionError","version":"viem@1.10.12","message":"An unknown RPC error occurred.\n\nRaw Call Arguments:\n to: 0xca11bde05977b3631167028862be2a173976ca11\n data: 0x82ad56cb00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000e0000000000000000000000000fba3912ca04dd458c843e2ee08967fc04f3579c200000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000000418160ddd00000000000000000000000000000000000000000000000000000000000000000000000000000000fba3912ca04dd458c843e2ee08967fc04f3579c200000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000002470a08231000000000000000000000000a5cc3c03994db5b0d9a5eedd10cabab0813678ac00000000000000000000000000000000000000000000000000000000\n\nDetails: Provided value is not JSON-RPC compatible: Expected the value to satisfy a union of , but received: [object Object].\nVersion: viem@1.10.12","cause":{"details":"Provided value is not JSON-RPC compatible: Expected the value to satisfy a union of , but received: [object Object].","shortMessage":"An unknown RPC error occurred.","name":"UnknownRpcError","version":"viem@1.10.12","message":"An unknown RPC error occurred.\n\nDetails: Provided value is not JSON-RPC compatible: Expected the value to satisfy a union of , but received: [object Object].\nVersion: viem@1.10.12","cause":{"code":"ERR_ASSERTION"},"code":-1}},"abi":[{"inputs":[{"components":[{"name":"target","type":"address"},{"name":"allowFailure","type":"bool"},{"name":"callData","type":"bytes"}],"name":"calls","type":"tuple[]"}],"name":"aggregate3","outputs":[{"components":[{"name":"success","type":"bool"},{"name":"returnData","type":"bytes"}],"name":"returnData","type":"tuple[]"}],"stateMutability":"view","type":"function"}],"args":[[{"allowFailure":true,"callData":"0x18160ddd","target":"0xFBA3912Ca04dd458c843e2EE08967fC04f3579c2"},{"allowFailure":true,"callData":"0x70a08231000000000000000000000000a5cc3c03994db5b0d9a5eedd10cabab0813678ac","target":"0xFBA3912Ca04dd458c843e2EE08967fC04f3579c2"}]],"contractAddress":"0xca11bde05977b3631167028862be2a173976ca11","functionName":"aggregate3"}},{"status":"failure","error":{"details":"Provided value is not JSON-RPC compatible: Expected the value to satisfy a union of , but received: [object Object].","docsPath":"/docs/contract/readContract","metaMessages":["Raw Call Arguments:"," to: 0xca11bde05977b3631167028862be2a173976ca11\n data: 0x82ad56cb00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000e0000000000000000000000000fba3912ca04dd458c843e2ee08967fc04f3579c200000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000000418160ddd00000000000000000000000000000000000000000000000000000000000000000000000000000000fba3912ca04dd458c843e2ee08967fc04f3579c200000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000002470a08231000000000000000000000000a5cc3c03994db5b0d9a5eedd10cabab0813678ac00000000000000000000000000000000000000000000000000000000"," ","Contract Call:"," address: 0xca11bde05977b3631167028862be2a173976ca11\n function: aggregate3((address target, bool allowFailure, bytes callData)[])\n args: ([{"allowFailure":true,"callData":"0x18160ddd","target":"0xFBA3912Ca04dd458c843e2EE08967fC04f3579c2"},{"allowFailure":true,"callData":"0x70a08231000000000000000000000000a5cc3c03994db5b0d9a5eedd10cabab0813678ac","target":"0xFBA3912Ca04dd458c843e2EE08967fC04f3579c2"}])"],"shortMessage":"An unknown RPC error occurred.","name":"ContractFunctionExecutionError","version":"viem@1.10.12","message":"An unknown RPC error occurred.\n\nRaw Call Arguments:\n to: 0xca11bde05977b3631167028862be2a173976ca11\n data: 0x82ad56cb00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000e0000000000000000000000000fba3912ca04dd458c843e2ee08967fc04f3579c200000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000000418160ddd00000000000000000000000000000000000000000000000000000000000000000000000000000000fba3912ca04dd458c843e2ee08967fc04f3579c200000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000002470a08231000000000000000000000000a5cc3c03994db5b0d9a5eedd10cabab0813678ac00000000000000000000000000000000000000000000000000000000\n \nContract Call:\n address: 0xca11bde05977b3631167028862be2a173976ca11\n function: aggregate3((address target, bool allowFailure, bytes callData)[])\n args: ([{"allowFailure":true,"callData":"0x18160ddd","target":"0xFBA3912Ca04dd458c843e2EE08967fC04f3579c2"},{"allowFailure":true,"callData":"0x70a08231000000000000000000000000a5cc3c03994db5b0d9a5eedd10cabab0813678ac","target":"0xFBA3912Ca04dd458c843e2EE08967fC04f3579c2"}])\n\nDocs: https://viem.sh/docs/contract/readContract.html\nDetails: Provided value is not JSON-RPC compatible: Expected the value to satisfy a union of , but received: [object Object].\nVersion: viem@1.10.12","cause":{"details":"Provided value is not JSON-RPC compatible: Expected the value to satisfy a union of , but received: [object Object].","metaMessages":["Raw Call Arguments:"," to: 0xca11bde05977b3631167028862be2a173976ca11\n data: 0x82ad56cb00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000e0000000000000000000000000fba3912ca04dd458c843e2ee08967fc04f3579c200000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000000418160ddd00000000000000000000000000000000000000000000000000000000000000000000000000000000fba3912ca04dd458c843e2ee08967fc04f3579c200000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000002470a08231000000000000000000000000a5cc3c03994db5b0d9a5eedd10cabab0813678ac00000000000000000000000000000000000000000000000000000000"],"shortMessage":"An unknown RPC error occurred.","name":"CallExecutionError","version":"viem@1.10.12","message":"An unknown RPC error occurred.\n\nRaw Call Arguments:\n to: 0xca11bde05977b3631167028862be2a173976ca11\n data: 0x82ad56cb00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000e0000000000000000000000000fba3912ca04dd458c843e2ee08967fc04f3579c200000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000000418160ddd00000000000000000000000000000000000000000000000000000000000000000000000000000000fba3912ca04dd458c843e2ee08967fc04f3579c200000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000002470a08231000000000000000000000000a5cc3c03994db5b0d9a5eedd10cabab0813678ac00000000000000000000000000000000000000000000000000000000\n\nDetails: Provided value is not JSON-RPC compatible: Expected the value to satisfy a union of , but received: [object Object].\nVersion: viem@1.10.12","cause":{"details":"Provided value is not JSON-RPC compatible: Expected the value to satisfy a union of , but received: [object Object].","shortMessage":"An unknown RPC error occurred.","name":"UnknownRpcError","version":"viem@1.10.12","message":"An unknown RPC error occurred.\n\nDetails: Provided value is not JSON-RPC compatible: Expected the value to satisfy a union of , but received: [object Object].\nVersion: viem@1.10.12","cause":{"code":"ERR_ASSERTION"},"code":-1}},"abi":[{"inputs":[{"components":[{"name":"target","type":"address"},{"name":"allowFailure","type":"bool"},{"name":"callData","type":"bytes"}],"name":"calls","type":"tuple[]"}],"name":"aggregate3","outputs":[{"components":[{"name":"success","type":"bool"},{"name":"returnData","type":"bytes"}],"name":"returnData","type":"tuple[]"}],"stateMutability":"view","type":"function"}],"args":[[{"allowFailure":true,"callData":"0x18160ddd","target":"0xFBA3912Ca04dd458c843e2EE08967fC04f3579c2"},{"allowFailure":true,"callData":"0x70a08231000000000000000000000000a5cc3c03994db5b0d9a5eedd10cabab0813678ac","target":"0xFBA3912Ca04dd458c843e2EE08967fC04f3579c2"}]],"contractAddress":"0xca11bde05977b3631167028862be2a173976ca11","functionName":"aggregate3"}}]
</details>

i have no idea whether the two errors (i.e., the hanging, vs. the `Provided value is not JSON-RPC compatible` above) are related, or completely different bugs.

### Expected Behavior

should work; should show a dialog containing the result.

### Steps To Reproduce

clone [my MWE](https://github.com/firnprotocol/template-snap-monorepo). run `yarn install && yarn start`. navigate to http://localhost:8000/. install Flask. connect to the snap in the top right; then click "send message".

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://github.com/firnprotocol/template-snap-monorepo

### Anything else?

happy to help debug.

**Comment by jxom** [comment]
Mind raising this on the MetaMask repo? Viem doesn't do anything fancy when it comes to making network requests, etc. We just use native `fetch` with `AbortController` (for timeouts). I do know that MetaMask Snaps are run in Secure EcmaScript (SES), so might be something weird going on in the isolated JS realm that's causing it to block some public APIs?

**Comment by firnprotocol** [comment]
k, re-raised as https://github.com/MetaMask/snaps/issues/1750. any help would still be appreciated; e.g., perhaps you can tell from the error dump where exactly in the codebase the error is coming from.

**Comment by firnprotocol** [comment]
actually, maybe I can ask you directly: can i ask where specifically in the viem codebase the error `Provided value is not JSON-RPC compatible: Expected the value to satisfy a union of , but received: [object Object].` is being thrown? the codebase appears not to contain this text verbatim anywhere—perhaps it's coming from a library / subcall? this fact makes it difficult to debug.

specifically, is this referring to what is passed into the outbound JSON-RPC request, or to what comes back from the wallet? thanks in advance.
