### ISSUE TITLE
bug: websocket subscriptions don't work in 1.10.13+

### ISSUE THREAD

**Issue by lekevicius** [wagmi-dev/viem#1219]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.10.14

### Current Behavior

Calling `watchBlocks` (simplest subscription) on a `PublicClient<WebSocketTransport>` does not work after 1.10.13, 1.10.12 is the last working version. 1.9.5 also works. The problem seems to only occur on local network (anvil), seems like public blockchains via Alchemy still work.

Additionally, `await this.subscriptionsRPC.transport.getSocket()` crashes in utils/rpc.ts on line 161, WebSocket is undefined.

This in on node v18.17.1.

### Expected Behavior

`watchBlocks` should `console.log` when new blocks arrive; after 1.10.13 it's silent. Same code works when reverting to 1.10.12 or 1.9.5.

### Steps To Reproduce

```
this.subscriptionsRPC = createPublicClient({
  transport: webSocket("ws://127.0.0.1:8545"),
  chain: hardhat,
});

this.subscriptionsRPC.watchBlocks({
  onBlock: (block) => {
    console.log('RPC new block:', block);
  },
});
```

No logs received after 1.10.13.

**Comment by jxom** [comment]
It still seems to work in viem's test suite which runs on an Anvil fork. Mind providing a minimal reproducible example via a separate repo? Will re-open when done.
