### ISSUE TITLE
bug: no way way to close websockets

### ISSUE THREAD

**Issue by murderteeth** [wagmi-dev/viem#1222]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.10.14

### Current Behavior

I haven't found a way to close websockets after reading both docs and code. I tried various things including `await (client.transport.getSocket()).close()` as mentioned here, https://github.com/wagmi-dev/viem/discussions/620, but nothing has worked for me. `await (client.transport.getSocket()).close()` hangs for me, as an example, and doesn't return. Instead the socket eventually timesout on its own.

I think this a bug. Please add api support for closing sockets or at least document a supported way to close them to make debugging socket issues easier.

**Comment by jxom** [comment]
Do you mind providing a minimal reproducible example? Hard to tell what's going on as WebSocket implementation varies on environment. We have a test for `.close()` in our test suite here which works okay (in Node 20 at least): https://github.com/wagmi-dev/viem/blob/main/src/utils/rpc.test.ts#L672-L693

Will re-open when reproduction is provided

**Comment by murderteeth** [comment]
> Do you mind providing a minimal reproducible example? Hard to tell what's going on as WebSocket implementation varies on environment. We have a test for `.close()` in our test suite here which works okay (in Node 20 at least): https://github.com/wagmi-dev/viem/blob/main/src/utils/rpc.test.ts#L672-L693
> 
> Will re-open when reproduction is provided

my code works now, thank you! the test code cleared everything up for me.

**Comment by jxom** [comment]
great to hear
