### ISSUE TITLE
encodeAbiParameters giving error for arguments

### ISSUE THREAD

**Issue by NidhiPrakash27** [wagmi-dev/viem#1224]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package Version

1.10.14

### Current Behavior

Providing two arguments to encodeAbiParameters is giving the below error on the server
![ERROR](https://github.com/wagmi-dev/viem/assets/124063068/2a5b50ce-453b-4ad1-943c-c425440dc122)

But when removing both the arguments it gives this error on VS Code
![ERROR2](https://github.com/wagmi-dev/viem/assets/124063068/4d027054-5021-47a4-8905-b88e8418d8e2)

I created a reproducible example in Codesandbox but it is working there
Link to reproducible: https://codesandbox.io/s/competent-cdn-mtkm3g?file=/src/hook.jsgives

### Expected Behavior

It should not give any errors as it expects 2 arguments.

### Steps To Reproduce

Just open this Codesandbox link.
Type anything in the input box and check the console for encoded value

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://codesandbox.io/s/competent-cdn-mtkm3g?file=/src/hook.js

**Comment by jxom** [comment]
`"0x${string} | undefined"` is not a valid ABI type. I think you mean `"address"`?

**Comment by jxom** [comment]
Oh, looks like you fixed it in your codesandbox? I am not getting errors.

**Comment by NidhiPrakash27** [comment]
@jxom ??

**Comment by jxom** [comment]
Please provide a minimal reproduction that reproduces the error. If the codesandbox doesn't emit an error, then I suspect it may be something to do with your tsconfig.json.
