### ISSUE TITLE
bug: getEnsResolver should not depend on an universal resolver

### ISSUE THREAD

**Issue by DefiCake** [wagmi-dev/viem#1245]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.3.36

### Current Behavior

`getEnsResolver` needs an universal resolver to fetch resolvers. This is redundant and does not allow for custom ENS configurations. It also does not seem to follow ENS 's recommendations on how to query the resolver of a name.

```ts
export async function getEnsResolver<TChain extends Chain | undefined>(
  client: Client<Transport, TChain>,
  {
    blockNumber,
    blockTag,
    name,
    universalResolverAddress: universalResolverAddress_,
  }: GetEnsResolverParameters,
) {
  let universalResolverAddress = universalResolverAddress_
  if (!universalResolverAddress) {
    if (!client.chain)
      throw new Error(
        'client chain not configured. universalResolverAddress is required.',
      )

    universalResolverAddress = getChainContractAddress({
      blockNumber,
      chain: client.chain,
      contract: 'ensUniversalResolver',
    })
  }

  const [resolverAddress] = await readContract(client, {
    address: universalResolverAddress,
    abi: [
      {
        inputs: [{ type: 'bytes' }],
        name: 'findResolver',
        outputs: [{ type: 'address' }, { type: 'bytes32' }],
        stateMutability: 'view',
        type: 'function',
      },
    ],
    functionName: 'findResolver',
    args: [toHex(packetToBytes(name))],
    blockNumber,
    blockTag,
  })
  return resolverAddress
}
```

Instead, the optional argument should be the ENS root address defaulting to `0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e` and querying `resolver()` for the namehash.

### Expected Behavior

ENS should be queried for the resolver of the namehash, not another contract which might or might not exist in the chain.

**Comment by tmm** [comment]
The Universal Resolver is an [official ENS contract](https://github.com/ensdomains/ens-contracts/blob/master/contracts/utils/UniversalResolver.sol) and uses less RPC requests.
