### ISSUE TITLE
bug: Invalid url link in docs to multicall Live Example

### ISSUE THREAD

**Issue by Joetoledano** [wagmi-dev/viem#1252]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.12.2

### Current Behavior

In the Live Example section for the `multicall` Action, there is an error saying that the url to this repository is invalid

![image](https://github.com/wagmi-dev/viem/assets/10095107/ba26f67d-6637-42a8-9d5d-1987a59b4c68)

### Expected Behavior

The Live Example would load correctly 

### Steps To Reproduce

1. Visit the live example section: https://viem.sh/docs/contract/multicall.html#live-example

### Anything else?

Already attached it above but here is the screenshot again 

![image](https://github.com/wagmi-dev/viem/assets/10095107/78fa4465-92ef-4520-835c-ebc2a289ca29)

**Comment by tmm** [comment]
The paths for the examples changed when switching over to Bun. Easy first issue if anyone wants to pick it up! Just need to update the example URLs on the docs site to match the repository directory structure (like PR #1258 does).
