### ISSUE TITLE
Receiving `error TS1479` during build.

### ISSUE THREAD

**Issue by humblemodulo** [wagmi-dev/viem#1254]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.12.2

### Current Behavior

There appears to be a breakage between `"viem": "1.10.10"` and `"viem": "1.10.11"` inside `.ts` file when doing something like the following...

```
import {
  createPublicClient,
  webSocket
} from 'viem';
```

... and attempting to build the project containing the relevant `.ts` files.  The error is as follows:

```error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls```

This assumes the following inside `tsconfig.json` as well:

```
{
  "compilerOptions": {
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    ...
  }
  ...
}
```

Everything works fine until version `1.10.10`, then breaks at `1.10.11` and beyond.

### Expected Behavior

Build without TS1479 errors.

### Steps To Reproduce

- Upgrade to `viem 1.10.11` or beyond.
- `import {...} from 'viem'`
-  build  (tried `node`, `bun`, `tsup`)

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

[Editable StackBliz Example](https://stackblitz.com/edit/typescript-bgv8tz)

### Anything else?

The sample project is set to `1.10.10`.  Build and notice success.  Clear all `dist/node_modules` folders and `pnpm.lock`, adjust viem to `1.10.11` and notice build failure.

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.

**Comment by humblemodulo** [comment]
> Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.

Added.

**Comment by tmm** [comment]
Can you share the code editor version of StackBlitz? Can use [`new.viem.sh`](https://new.viem.sh) to reproduce.

This is what I see when I follow the link.

<img width="1097" alt="image" src="https://github.com/wagmi-dev/viem/assets/6759464/19f606cd-11c1-43f4-9044-5f84558a3ccb">

**Comment by humblemodulo** [comment]
> Can you share the code editor version of StackBlitz? Can use [`new.viem.sh`](https://new.viem.sh) to reproduce.
> 
> This is what I see when I follow the link.
> <img alt="image" width="1097" src="https://user-images.githubusercontent.com/6759464/270802968-19f606cd-11c1-43f4-9044-5f84558a3ccb.png">

Adjusted link as well as your provided project.

**Comment by witem** [comment]
@tmm 
I'm experiencing the same error after upgrade from 1.10.3 to the latest one(1.14.0)

**Comment by witem** [comment]
I found that in one release between this was added - `"type": "module",` to `package.json` https://github.com/wagmi-dev/viem/blob/main/src/package.json#L5 which caused this problem with the build. @tmm can we delete this line from `package.json`?
