### ISSUE TITLE
bug: remove https://rpc.sepolia.org/ as it doesn't work

### ISSUE THREAD

**Issue by Garito** [wagmi-dev/viem#1257]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.6.0

### Current Behavior

All calls to this rpc returns 503 service unavailable

### Expected Behavior

To work properly

### Steps To Reproduce

Make a call to sepolia using this rpc

**Comment by tmm** [comment]
Works fine when I run the following. It's a public RPC so could be rate-limited or down at times.

```bash
> curl -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","id":0,"method":"eth_blockNumber"}' https://rpc.sepolia.org
{"jsonrpc":"2.0","id":0,"result":"0x42c223"}
```

**Comment by Garito** [comment]
Is it possible to disable it without using rank? (rank eats the infura credit)
