### ISSUE TITLE
bug: setIntervalMining assumes the node receives a value in seconds

### ISSUE THREAD

**Issue by fvictorio** [wagmi-dev/viem#1261]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.12.2

### Current Behavior

The docs [say](https://viem.sh/docs/actions/test/setIntervalMining.html) that the `setIntervalMining` receives a number of seconds, but then it just forwards the value to `evm_setIntervalMining`. The problem is that this value, at least in Hardhat, is meant to be specified in milliseconds (maybe Anvil does something different).

### Expected Behavior

If you do `testClient.setIntervalMining({interval: 5})` with a test client in Hardhat mode, it should use `5000` in the JSON-RPC param.

**Comment by jxom** [comment]
Fixed: https://github.com/wagmi-dev/viem/commit/61ef4d224c860e99f3ac82adb8e4c767a77b6dc0
