### ISSUE TITLE
bug: contract instance watchEvent filter not working

### ISSUE THREAD

**Issue by kliyer-ai** [wagmi-dev/viem#1264]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.12.2

### Current Behavior

Say I have contract:
```
const chContract = getContract({
    address: "0x...",
    abi: myAbi,
    publicClient,
    walletClient,
  });
```

and I create filter:
```
chContract.watchEvent.MyEvent(
    {},
    {
      onLogs: async (logs) => {}
    }
)
```

the on logs function gets called for every event and not only `MyEvent`.

### Expected Behavior

I would only see logs for `MyEvent`.

### Steps To Reproduce

See code above.

**Comment by jxom** [comment]
Thanks for reporting. Can you please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) via https://new.viem.sh or a separate repo? It will save us a lot of time reproducing your config & environment, and trying to reproduce your issue. See [Why reproductions are required](https://antfu.me/posts/why-reproductions-are-required).

Please reopen this issue when a reproduction is added.

**Comment by jxom** [comment]
Also might be worth trying another RPC Provider.

**Comment by kliyer-ai** [comment]
Yeah the rpc was the problem...
