### ISSUE TITLE
err.walk is not a function

### ISSUE THREAD

**Issue by Marcelh1983** [wagmi-dev/viem#1275]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.14.0

### Current Behavior

using react&vite

I trying to find the real problem in my code. 
But only got the error: `err.walk is not a function`

![image](https://github.com/wagmi-dev/viem/assets/3284645/61727015-c66b-40e0-aefc-fe5499aa1202)

### Expected Behavior

Get the actual error, in this case: `invalid BigInt syntax`

### Steps To Reproduce

passing a value that cannot be parsed to a bigint as gasprice of the sendTransaction function of wagmi.

**Comment by jxom** [comment]
Thanks for reporting. Can you please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) via https://new.viem.sh or a separate repo? It will save us a lot of time reproducing your config & environment, and trying to reproduce your issue. See [Why reproductions are required](https://antfu.me/posts/why-reproductions-are-required).

Please reopen this issue when a reproduction is added.
