### ISSUE TITLE
bug: Type inference does not work

### ISSUE THREAD

**Issue by sbeben** [wagmi-dev/viem#1285]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.10.9

### Current Behavior

I am using wigmi's core actions which in fact are just wrappers for viem's client actions, so, I'm not shure where to address this exactly, but return types of readContract are unknown, no type inference for functionName and args as well.
typescript: 5.0.4
viem: 1.10.9
wagmi: 1.4.1

### Expected Behavior

as described here:
https://viem.sh/docs/typescript.html

### Steps To Reproduce

1. tsconfig - compilerOptions: strict: true
2. `const stones = [
  {
    inputs: [],
    type: 'constructor',
  },
  {
    inputs: [],
    name: 'DOMAIN_SEPARATOR',
    outputs: [
      {
        internalType: 'bytes32',
        name: '',
        type: 'bytes32',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'DOMAIN_TYPE_HASH',
    outputs: [
      {
        internalType: 'bytes32',
        name: '',
        type: 'bytes32',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'LEVELUP_TYPE_HASH',
    outputs: [
      {
        internalType: 'bytes32',
        name: '',
        type: 'bytes32',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'MINT_TYPE_HASH',
    outputs: [
      {
        internalType: 'bytes32',
        name: '',
        type: 'bytes32',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'account',
        type: 'address',
      },
      {
        internalType: 'uint256',
        name: 'assetId',
        type: 'uint256',
      },
    ],
    name: 'activateUserPosition',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    name: 'activeUserAssets',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'priceETH',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: 'levels',
        type: 'uint256',
      },
      {
        internalType: 'string',
        name: 'assetUri',
        type: 'string',
      },
    ],
    name: 'addAsset',
    outputs: [
      {
        internalType: 'uint256',
        name: 'assetId',
        type: 'uint256',
      },
    ],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'bytes32',
        name: '',
        type: 'bytes32',
      },
    ],
    name: 'alreadyPerformed',
    outputs: [
      {
        internalType: 'bool',
        name: '',
        type: 'bool',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    name: 'asset',
    outputs: [
      {
        internalType: 'uint256',
        name: 'priceETH',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: 'firstIndex',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: 'levels',
        type: 'uint256',
      },
      {
        internalType: 'string',
        name: 'uri',
        type: 'string',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'assetId',
        type: 'uint256',
      },
    ],
    name: 'assetTotalSupply',
    outputs: [
      {
        internalType: 'uint256',
        name: 'supply',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'account',
        type: 'address',
      },
      {
        internalType: 'uint256',
        name: 'id',
        type: 'uint256',
      },
    ],
    name: 'balanceOf',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address[]',
        name: 'accounts',
        type: 'address[]',
      },
      {
        internalType: 'uint256[]',
        name: 'ids',
        type: 'uint256[]',
      },
    ],
    name: 'balanceOfBatch',
    outputs: [
      {
        internalType: 'uint256[]',
        name: '',
        type: 'uint256[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'account',
        type: 'address',
      },
      {
        internalType: 'uint256',
        name: 'assetId',
        type: 'uint256',
      },
    ],
    name: 'deactivateUserPosition',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'id',
        type: 'uint256',
      },
    ],
    name: 'exists',
    outputs: [
      {
        internalType: 'bool',
        name: '',
        type: 'bool',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        components: [
          {
            type: 'address',
          },
          {
            type: 'uint256',
          },
          {
            type: 'uint256',
          },
          {
            type: 'uint256',
          },
          {
            type: 'uint256',
          },
        ],
        internalType: 'struct LevelUpParams',
        name: 'params',
        type: 'tuple',
      },
    ],
    name: 'getLevelUpHash',
    outputs: [
      {
        internalType: 'bytes32',
        name: '',
        type: 'bytes32',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        components: [
          {
            type: 'address',
          },
          {
            type: 'uint256',
          },
          {
            type: 'string',
          },
          {
            type: 'uint256',
          },
          {
            type: 'uint256',
          },
        ],
        internalType: 'struct MintParams',
        name: 'params',
        type: 'tuple',
      },
    ],
    name: 'getMintHash',
    outputs: [
      {
        internalType: 'bytes32',
        name: '',
        type: 'bytes32',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'account',
        type: 'address',
      },
    ],
    name: 'getTokens',
    outputs: [
      {
        internalType: 'uint256[]',
        name: '',
        type: 'uint256[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'string',
        name: '_name',
        type: 'string',
      },
      {
        internalType: 'string',
        name: '_symbol',
        type: 'string',
      },
      {
        internalType: 'string',
        name: '_uri',
        type: 'string',
      },
      {
        internalType: 'address',
        name: '_staking',
        type: 'address',
      },
    ],
    name: 'initialize',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
    ],
    name: 'isApprovedForAll',
    outputs: [
      {
        internalType: 'bool',
        name: '',
        type: 'bool',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        components: [
          {
            type: 'address',
          },
          {
            type: 'uint256',
          },
          {
            type: 'uint256',
          },
          {
            type: 'uint256',
          },
          {
            type: 'uint256',
          },
        ],
        internalType: 'struct LevelUpParams',
        name: 'params',
        type: 'tuple',
      },
      {
        components: [
          {
            type: 'uint8',
          },
          {
            type: 'bytes32',
          },
          {
            type: 'bytes32',
          },
        ],
        internalType: 'struct SignatureParams',
        name: 'signature',
        type: 'tuple',
      },
    ],
    name: 'levelUp',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        components: [
          {
            type: 'address',
          },
          {
            type: 'uint256',
          },
          {
            type: 'string',
          },
          {
            type: 'uint256',
          },
          {
            type: 'uint256',
          },
        ],
        internalType: 'struct MintParams',
        name: 'params',
        type: 'tuple',
      },
      {
        components: [
          {
            type: 'uint8',
          },
          {
            type: 'bytes32',
          },
          {
            type: 'bytes32',
          },
        ],
        internalType: 'struct SignatureParams',
        name: 'signature',
        type: 'tuple',
      },
    ],
    name: 'mint',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'name',
    outputs: [
      {
        internalType: 'string',
        name: '',
        type: 'string',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'nextAssetPointer',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'nextIdPointer',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
      {
        internalType: 'uint256[]',
        name: '',
        type: 'uint256[]',
      },
      {
        internalType: 'uint256[]',
        name: '',
        type: 'uint256[]',
      },
      {
        internalType: 'bytes',
        name: '',
        type: 'bytes',
      },
    ],
    name: 'safeBatchTransferFrom',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
      {
        internalType: 'bytes',
        name: '',
        type: 'bytes',
      },
    ],
    name: 'safeTransferFrom',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
      {
        internalType: 'bool',
        name: '',
        type: 'bool',
      },
    ],
    name: 'setApprovalForAll',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'assetId',
        type: 'uint256',
      },
      {
        internalType: 'string',
        name: 'assetUri',
        type: 'string',
      },
    ],
    name: 'setAssetUri',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'string',
        name: 'defaultUri',
        type: 'string',
      },
    ],
    name: 'setDefaultUri',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: '_validator',
        type: 'address',
      },
    ],
    name: 'setValidator',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'staking',
    outputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'bytes4',
        name: 'interfaceId',
        type: 'bytes4',
      },
    ],
    name: 'supportsInterface',
    outputs: [
      {
        internalType: 'bool',
        name: '',
        type: 'bool',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'symbol',
    outputs: [
      {
        internalType: 'string',
        name: '',
        type: 'string',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'tokenId',
        type: 'uint256',
      },
    ],
    name: 'tokenURI',
    outputs: [
      {
        internalType: 'string',
        name: '',
        type: 'string',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    name: 'tokens',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'id',
        type: 'uint256',
      },
    ],
    name: 'totalSupply',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'tokenId',
        type: 'uint256',
      },
    ],
    name: 'uri',
    outputs: [
      {
        internalType: 'string',
        name: '',
        type: 'string',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    name: 'userAssetPosition',
    outputs: [
      {
        internalType: 'uint256',
        name: 'level',
        type: 'uint256',
      },
      {
        internalType: 'string',
        name: 'trait',
        type: 'string',
      },
      {
        internalType: 'bool',
        name: 'isActive',
        type: 'bool',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    name: 'userAssets',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'validator',
    outputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        name: 'hashData',
        type: 'bytes32',
      },
      {
        indexed: true,
        name: '_validator',
        type: 'address',
      },
    ],
    name: 'ActionPerformed',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        name: 'account',
        type: 'address',
      },
      {
        indexed: true,
        name: 'operator',
        type: 'address',
      },
      {
        indexed: false,
        name: 'approved',
        type: 'bool',
      },
    ],
    name: 'ApprovalForAll',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        name: 'version',
        type: 'uint8',
      },
    ],
    name: 'Initialized',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        name: 'operator',
        type: 'address',
      },
      {
        indexed: true,
        name: 'from',
        type: 'address',
      },
      {
        indexed: true,
        name: 'to',
        type: 'address',
      },
      {
        indexed: false,
        name: 'ids',
        type: 'uint256[]',
      },
      {
        indexed: false,
        name: 'values',
        type: 'uint256[]',
      },
    ],
    name: 'TransferBatch',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        name: 'operator',
        type: 'address',
      },
      {
        indexed: true,
        name: 'from',
        type: 'address',
      },
      {
        indexed: true,
        name: 'to',
        type: 'address',
      },
      {
        indexed: false,
        name: 'id',
        type: 'uint256',
      },
      {
        indexed: false,
        name: 'value',
        type: 'uint256',
      },
    ],
    name: 'TransferSingle',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        name: 'value',
        type: 'string',
      },
      {
        indexed: true,
        name: 'id',
        type: 'uint256',
      },
    ],
    name: 'URI',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        name: 'previousValidator',
        type: 'address',
      },
      {
        indexed: true,
        name: 'currentValidator',
        type: 'address',
      },
    ],
    name: 'ValidatorSetted',
    type: 'event',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'expected',
        type: 'address',
      },
    ],
    name: 'AccessDenied',
    type: 'error',
  },
  {
    inputs: [
      {
        internalType: 'bytes32',
        name: 'structHash',
        type: 'bytes32',
      },
    ],
    name: 'ActionAlreadyPerformed',
    type: 'error',
  },
  {
    inputs: [],
    name: 'AlreadyMinted',
    type: 'error',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'currentTime',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: 'deadline',
        type: 'uint256',
      },
    ],
    name: 'DeadlineExpired',
    type: 'error',
  },
  {
    inputs: [],
    name: 'FunctionDisabled',
    type: 'error',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'assetId',
        type: 'uint256',
      },
    ],
    name: 'InvalidAsset',
    type: 'error',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'actual',
        type: 'address',
      },
      {
        internalType: 'address',
        name: 'expected',
        type: 'address',
      },
    ],
    name: 'InvalidSigner',
    type: 'error',
  },
  {
    inputs: [],
    name: 'InvalidValidator',
    type: 'error',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'actual',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: 'minimum',
        type: 'uint256',
      },
    ],
    name: 'InvalidValue',
    type: 'error',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'actual',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: 'limit',
        type: 'uint256',
      },
    ],
    name: 'NumberOfAssetsExceeded',
    type: 'error',
  },
  {
    inputs: [],
    name: 'PositionDisabled',
    type: 'error',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'actual',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: 'increase',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: 'limit',
        type: 'uint256',
      },
    ],
    name: 'PositionLevelExceeded',
    type: 'error',
  },
  {
    inputs: [],
    name: 'UnrecognizedPosition',
    type: 'error',
  },
  {
    inputs: [],
    name: 'ValidationFailed',
    type: 'error',
  },
] as const`
3. 
<img width="328" alt="Screenshot 2023-10-04 at 14 06 54" src="https://github.com/wagmi-dev/viem/assets/58523020/029a7a6d-f919-4ef0-9ca9-0b8c4c557286">
4. inline does not work as well 
<img width="305" alt="Screenshot 2023-10-04 at 14 19 08" src="https://github.com/wagmi-dev/viem/assets/58523020/cc5f5bb3-e538-4635-a566-e4b30a3bbba2">

**Comment by jxom** [comment]
Thanks for reporting. Can you please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) via https://new.viem.sh or a separate repo? It will save us a lot of time reproducing your config & environment, and trying to reproduce your issue. See [Why reproductions are required](https://antfu.me/posts/why-reproductions-are-required).

Please reopen this issue when a reproduction is added.

**Comment by sbeben** [comment]
here you go
https://stackblitz.com/edit/viem-getting-started-s9jdgn?file=index.ts
meither viem's client.readContract nor wagmi's readContract does not give any typings

**Comment by tmm** [comment]
Viem requires TypeScript 5.0.4 or later.

**Comment by sbeben** [comment]
> Viem requires TypeScript 5.0.4 or later.
thanks for response
but switching to 5.0.4 did not give the desired result as well
https://stackblitz.com/edit/viem-getting-started-s9jdgn?file=index.ts

**Comment by sbeben** [comment]
@jxom any thoughts on that?

**Comment by tmm** [comment]
The ABI is malformed. The `"constructor"` item must have a `"stateMutability"` property. If you add that to the ABI or remove the item, it works appropriately ([TypeScript Playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgYygUwIYzQBQK4BGANsMgMIloB2MANHABYwxhwC+cAZlBCHAOQA3YGhD8AUKEixEcEBmBUqaeB268Bw0QHpkDBVQDOEqdHhJ0GACZkINKBmSquPPvwACAdwwBzEMF1oNAlxZDtDeGsrdENDOABeAQAGAA8ARgAmAGYAFhCwo3hkShoElEtsfGJSChEaAAoEcTgUfUUALjkDZTpmuBgHI2kYTqYWeoBKWnE2CfFQ8PgIuzQ4xIBtPu1tWUUwPBhDTvWAXXoYAE8wNE7+AoioPCdofnZplqaWlr2Do7hT95fKgYEA3AQAEQA8gBZACCAEkAHIAfQAygBRHCwgBKsIAKpDsfxAS0IAd9odjkhFNgoMCiHirmD+AQLthDFkMsS4MDQbduZdrrdWezOa82Gc+i0Ilg0NCDhgCMASJdblpPMSpf0mbdOHgqE5gHZNS02IDPl8fpT-pKvjyQcyoXCkci8QBNHDo5EACVhqO9Jq+ZJYvypcBpaDpGAZOoEItWYvovOZAtjLLZCa57FtXxl2HlMEVyuAqs0Ig1JO1QoEeoNMCNVEDZr6Fu+VApfwBWuTtwAMuiAGro3sAVRwro9Xt9-sDpPJof+1JokfpjOr6dFXKTDv55zT8Y5WYllbzcoVSpVFzV5dnVeZtcNxsBzY+WqtnZzLR7AmhSLxE89H0-QDStgw7MMIyjGN1wPRN7T5ARUxgjND3FT84FPAsi0va80ArLVBXvfVH0bZ9zTfdsF02O0PnDZcoLXZkohiYxtwQ-hHDCfUYCQpirGiVZjDeLVaMg1c0zwGkMgAVgANm5b8ONiFR4SsXjbkkmgZPk4S7XQxTHHrQRZRHQxIxwCBDBLBtbzAqj0Mw89i1LfgqDsMAMAuRUiGCStCN1Yj6yfPoX0QCjwP+ETdno8T12YwSFJ3RC9zi-iWPFStRJi6NGI0qS5MS9j1IETSYG0jKtX0pKOMNQQ0FMyNYWUw5bPna11iXWlYuZUryrYlMUp6-KdOPLVHMLC8SyvMs8Nvfya0CmyyJbcKqKizqVxyiThsK5kwCgUg0HRPEQLvPKtIK3SaI2hjtou+T+tuHy6qIVizpKnarrtG7utuB5FB8XbbgwZqRwO4r+H+qhAa+uAqvYqImrMnjQLazsfq29deoKx6BBB5HVIh7GRocwt8ycnCBDc9tPO83yCLTB8gtIkLyLtd8IOy6DmVgrd4IG96N0zNDKwMohLCsC4cEjThoFBNTUZDdqMe54UIAgIggeSwWCHVzXsxPMmzwm5zpqEG8-MZxbgtNNnLUo5W6K6zGhvurX+CJz7RrtAzmtapXO3Wp3NtVj63dx-h9sO47Tvm-hiYqmjoud0P452iPOGAKAInhKgrDQFJPbd2GspT3Kw7KnH+aetAXreuOE5L5OQ-LyGBgB928HBwa-vb6HE6+UnZSwyaXPVOarbrJbWZW9mHfR4Pbqx9Pq7x5rCZ7ivyoN7tqvxlQ8QgQsiFRPAwDAIgLn9iKOsX36t6rxTDDPi+r83tPi+93MjZH03cPwu0ccmbT1trPe2N8g5iRdsDNKCUI6cTJDQCG8VYgD2+nfaBD8Hqr34MABWgtG6hRaPDHm0YMAGjQJCTg18qIq1bgnCORdK4k0NsPCmU1-4T3XMAm2V1Wx0QgUnOhaYUGGFOO7BB3F64iNgbEcRTdhHL3uuIiOeDpFKOYfIohcNRbVQIGQihVCABCWA9A0MdlA1OxMVE4KYdpLRQ9yYm0pubWaltuHWxZqA18c9BHXQwanUREjkBcSQe-IJCiAn0JXr7Am+CG5e0rCQ24+dDLAGMtgBqUALJWWZuYj8rCnHYQ4VTdytNiD00AZPEiTY7Zthvoo12zD3Z4LsZdL+X5qoF2ABEViWo7IWK5q3XWGt3YQxGfrDpGEf7sLHhbBmHip68NCvwjmkUhFRRaGEcAKwaCByTuguOETtFCIIYkzZXwkAJM-plfx1zmlN0OXdB5JzB63LbGXNMDwnjwF7LXNARARxgBwBgBwIA+kHJwR5MFEKDlxxgGfHyt5vFvN3uxHwKg-kvSBd6EGDB8mc0+chTcYz368xFmNGZziSmuIAV8IBnjalgPqWtDZkLtmQGUHs44FzaJHNkUJV5TyNHbyFZcwWUMYZir5c80V7zxX3LlRc9Cc8iXMm+U4OA0IaQgphcioE1VoUglhUneFiLKk0W0ckgQGKYDapoLiww+LFYNKifuFCcFFLjI9UeRxxtilzLcQsoiSyvF8NWoMtVMCBKoPgSExBKNBbHOtfwW1h8ADW1ATVwAGQvSx0TlEnFJWcwtFK7TjQDWbce7iQ01OWj48BrL-H5q+X3QGEdkTJghpKtB4qW3rh7R2wwFwQC601u-HtkT+3qrbe7ZEXdgDdtnVOoZMiY1vUUsiGU6aO7hIFb2lNihrLRmAAALwtXOAOxw-W-xcdTDyXkKlcNrXk+tYVfFNvQdO6N6VGF7vXb20uLc12-tsf+9KsND2GFhOfHgdUrAADFoCwiIOO-paNCXAZgnrYtccJllu-mw6lga6UtAZaGplDaWXtXWhcjluyaOQplalADjyFWyvafK5jTSlVMdkIqzjvL+McZGvKlV9so0CA1b8-5gLgWguNfqzp7EjXgqU4LBFF8L1fFefwu09GuWMaY1c55AAOQDdz3UkrY9x4UPqLPEPld+qTAwflwFRMAHwwIEXoF1Yp+VT9PPea7tpqp65NNItuVa3R7FnoAqBQSm0hT-WjzNve8pkXg0BQo2+1Z88eVsoOQZ6gRnIUmZYxB6VwmRWCb4+VmdB1+42eqzx2rxmS0vLE051dA7XOavtTAPzamAuGoU8Ni5ZqtP6t03R3gnKSv7Pa-c8zzX6t2es1VtbcZ7NsfEx8rDDW3Mea81gELQ3s0+2qlZE7PnQv0rTBFu70W0XMn8GE9DV6kuUqI5W246XH2ZbCy+kB4aP3tRTV2l1tC3W9ca+2sDErl1TIralzhNbst1pnlRgR9kYvMmUCkGASMVAWUgol2+zmP7NL-R10VN7ZlVvmUDjHr6sfvsbeDvHf2C4wFUqT+i5PGnnWpwjgTLDvtFNRzNUjgseFhpWRGxbX6et8QAzT-lrHdMw9V6Br14GEorsk1T+xRb1cia0bcoXWCbF69p3JC3kCVfrdWLhqzLvINc6kxgTgaATEwD0HiQYhgfdQAQ64cn9PiNpbKQD7T5HMcory345XRuglm4qwbrXlO0+i5A5ny32vhd9VzzV0TjujcMJL61svpzKcHld8S93z3LvsUMN7tAgfyHB8jGH3gEfku3ppf9umz6Wcg4V2DpXfand433ennX+fy8HbVqM+fK-JlJM95DFQMH9oQGMkQJDUAUNobtLm69A+Gd-ZjyP9HC0cts6T5+6fFeYl73XvEkTFmrdtzhxI0G3ciOf+HuL2f0O+ABi6UOnOEuKWf8pSNMseo+9+CeoOHOeaM+v+u6OC+cnAGAeARAMAYMkBQBHcO8Le6qKg4IaAuB+BhB3cH2N8kev28BD6t+WWyBrOieiumGS8C+saOCyIB+eCWALw+uqCZBBqreKgA4J6VgIhUA-eMBg+Lkw+T6d+-AculG7O1GBSoBLmGAO6-cUB6Bqec+VeP6meTBUutKSBGhjKuW3Bi4he227IeQqi9EuByAaAG8OsKEeQEhym6qL8ZghguctInh2m5+ThdeOGa+cYOGAR0yP21h1a7BdhD+XBk+F+ehkMI6Y6guzhmBRh5hLmwByOVKzBNh6hmhDhWR0RGBleikMAEAmaVAPhYuBGgRtwzRrRI42I8IBRlOg6JRRRUqVhcBVRaRNRj+jh1EzaGBOetuGulWBelOjR1UbSNeqK5B3RLRWagxDRb+RU78hC4xLiqRzOHB4+dSOOkay+WCLSn+penROCzRx8p858l8Bxr+4cIxpxl+UeaOUx9hMxdRFOhxvxTRexbRTx1eLxikC63x9xoxDeDWpB5RyRExFx92iyKBE+aBBW8xphauIxxyqxEJIuSxX+IBOxJUZkx+zUOS1kvCl6yeL+yJ6xsWsmmx3+hRwxTRDgJYS6ZR5JRu+Gqi0GtUvkOsCRzehGkuWJTOOJwOyyNxaycxKeyJixGxYhgqopHJRxAsHRNJkhPU9JxOLUxhPB98xuj8Opdu4u5aFRKRSpZG1SnBqBOh2RtJQgsh8hSJvBFh-BVJGe4hGJCp5xrpsuIJmRXw5CdgI6ZIfwuBr0aAlY6pju+cKQaAVgnQrmaZOC+gTq4IWAGA3qG25JWZOZeZjwBZm6QhchzRChupB6W+sIJE0sUAssUA8sth-y72sZLQ8ZVAiZeAyZ0YZk6Z+W6y8xVZuZ-QtZcaoSiayxi+teecBc1ZC5eAdZ1UEA1wDgTZyC+6K6c5nQKZk5OCGAsG++OZ4yspm+ORu+cG0YR+J+fZdUA5npcAw5o545qZU5rqigZ5XAE5u57EdU2cS0HWK2Uyikucx6JA56CsaR-ZKMoJcZ1Mf555YFgFz+WUIF+ZEc+5kY-pLZp5m585RFOC6gYg5FWeG52ZVFi5rxEAx5mulZlFOFAFOCaimxDu65IFF54FzIB+O56i1eAl2xpptwneRgIefuZi6haFWh-Cv5IASZ3Fk5sxmZXF25IltwJFh5ohSaJ5DFhFLFiktF7FKxulTFNZO5EczRNla5s5elwlqisJRebWyuQluFOCYl0pxpcpXRAgcl3eUAHm0MgOyptwKltRmFCZGlY5WlaZOlgl7l-likgVwp6JnF9l+lnlPJJpoV-AfRAxyln56Fg5P5WFyV-52lYJdlW51Fik+0tcRoY5MhJAjZJlq5YZ+VLVll1UyAXc6ANA3VwhR59Fj5Ppk1vVkVKg2AKFlx-A8VGFXp9RxJuuXSKQ1wTgd59FKa7ZXhsQVBVAIgK1sVAgkYPAzZG1txJhyJ5KEc0mjqzqvhG2x1JEKGEsUsMscsh1qFUAd1qlj1F+OCv1mAksA2h1gst1Lw35GZ65PxlJI1Y1JWeIoAQV1JDFqNxeikqSVgJAygxVIVOCVB1gJNR0e1WcQNq1CN91ie4NSWOCCGni4IPSdMXlN1INiN+Jm14J+NdpCMH+ZNKaucDZFpfZfNTNSN05Gp7JgZs+JJBkTgeA0YLlA1S+ytHEZhikBc+1y1WteplUW+ktshx2ygctbp64jNYN6pZwOCFtPV81ZF8NstA8T+pWStNpnJTE6tmtJx5yKNBpkJ1Ub2oAeAdFDprZORLteC3VO5MtoNCVgtOtfthpwMgd46sdhuYdaNsWoAQpwdNyZtORiI0dBAkYVCFphg6IKQXhOZ9N11a1ntuWLNAIOCTJzMnNbeFSPNbdoN8tbJQGut-t2dCKQdedeNBdBN1UigqAmAZkZN+p49WdAgJA-gK5uNs1MlAgPdDYWKAKDdTd+cV1ttzI9tHdjtEcI4VA6AYQXmZ6OZh9T4Htw9KyndTtikbtzMCGCgPkg99twkJwP5cQ9wMA8wkDP5GAZQGA3gJYKAJQMAAAdBLLYPYIZI0H0KIoCEWJ0MsMoIYICHLoiNVGmtCbCqCj4J2PwKkPwJKLMNA4sD+cZMqHTKiM0cQ-A4g-ABg3YAMNgxaHg7g0qIQ9w6sKQ54uQ+igfFQ4GDQ3Qww0w3MEAA)). Where did you get the ABI from?
