### ISSUE TITLE
bug: Circular dependency

### ISSUE THREAD

**Issue by spider9375** [wagmi-dev/viem#1287]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package Version

1.15.1

### Current Behavior

(!) Circular dependencies
node_modules/viem/_esm/utils/encoding/fromHex.js -> node_modules/viem/_esm/utils/encoding/toBytes.js -> node_modules/viem/_esm/utils/encoding/fromHex.js
node_modules/viem/_esm/utils/encoding/fromHex.js -> node_modules/viem/_esm/utils/encoding/toBytes.js -> node_modules/viem/_esm/utils/encoding/toHex.js -> node_modules/viem/_esm/utils/encoding/fromHex.js
node_modules/viem/node_modules/abitype/dist/esm/index.js -> node_modules/viem/node_modules/abitype/dist/esm/human-readable/parseAbiItem.js -> node_modules/viem/node_modules/abitype/dist/esm/index.js

### Expected Behavior

no circular dependencies

### Steps To Reproduce

-

### Anything else?

![image](https://github.com/wagmi-dev/viem/assets/32629458/cf2c7f8e-aef4-4d88-a4a5-827a35fc1031)

**Comment by jxom** [comment]
Is this producing an issue for you? If not, closing.
