### ISSUE TITLE
bug: viem bundles cjs and esm builds in nextjs

### ISSUE THREAD

**Issue by sambacha** [wagmi-dev/viem#1288]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.15.1

### Current Behavior

![Screenshot 2023-10-04 at 1 45 08 PM](https://github.com/wagmi-dev/viem/assets/32783916/e630f223-f1d8-4a5e-adf4-891637b9f7b4)

### Expected Behavior

not to bundle cjs and esm

### Steps To Reproduce

build in nextjs

**Comment by jxom** [comment]
If you're not using the Safe SDK though, you can build up your RainbowKit wallets manually: https://www.rainbowkit.com/docs/custom-wallet-list

**Comment by sambacha** [comment]
Thanks!

**Comment by yagopv** [comment]
Hey @sambacha. Currently `@safe-global/safe-apps-sdk` has the ESM support under the [.next.0](https://www.npmjs.com/package/@safe-global/safe-apps-sdk/v/9.0.0-next.0) version.

Was merged in this [PR](https://github.com/safe-global/safe-apps-sdk/pull/512)
