### ISSUE TITLE
NPM package size is 90 megabytes

### ISSUE THREAD

**Issue by paulmillr** [wagmi-dev/viem#1291]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

latest

### Current Behavior

The unnecessary file is `utils/encoding/__snapshots__/toRlp.test.ts.snap`

**Comment by jxom** [comment]
Fixed: https://github.com/wagmi-dev/viem/commit/b9d622d38542c36cffef1a887144ab44f980d764

thanks!
