### ISSUE TITLE
bug: After getting TransactionExecutionError: Execution reverted for an unknown reason error, I cannot execute any tx

### ISSUE THREAD

**Issue by demirbey05** [wagmi-dev/viem#1294]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.6.0

### Current Behavior

 If the transaction is reverted with `TransactionExecutionError: Execution reverted for an unknown reason error`, I cannot execute any transaction anymore. The subsequent TXs give the `TransactionExecutionError: The amount of gas provided for the transaction exceeds the limit allowed for the block.` I need to refresh the page to continue. 

If I got  `ContractFunctionExecutionError: The contract function "resourceSystemInit" reverted with the following signature:` I can continue to execute txs.

I have tested at Anvil network and at some test networks.

### Expected Behavior

I am expecting that I can continue to execute txs after I get `TransactionExecutionError: Execution reverted for an unknown reason error`.

### Steps To Reproduce

I tried the send same tx with 3 different clients at the same time and I got the `TransactionExecutionError: Execution reverted for an unknown reason error`. After that time, your transactions will be reverted.

**Comment by demirbey05** [comment]
When I send two transactions whose total exceeds the block gas limit to same block. I get `TransactionExecutionError: The amount of gas provided for the transaction exceeds the limit allowed for the block.`. After that point I cannot execute any tx until I refresh the page.
`

**Comment by jxom** [comment]
Thanks for reporting. Can you please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) via https://new.viem.sh or a separate repo? It will save us a lot of time reproducing your config & environment, and trying to reproduce your issue. See [Why reproductions are required](https://antfu.me/posts/why-reproductions-are-required).

Please reopen this issue when a reproduction is added.

**Comment by demirbey05** [comment]
@jxom It is okay to ask me to reproduce the bug, but I want to give you some feedback. Your `new.viem.sh` environment is not good for a web3 developer who is used to using react or next in his dev environment. Please add react or next to this reproduce environment. It is so time-consuming to reproduce a bug in such a simple HTML or JS form.

**Comment by jxom** [comment]
Please provide a minimal repro in React then: https://vite.new/react-ts

Just need to install and add `viem` there.

**Comment by Mokekula** [comment]
Не работает, помогите
