### ISSUE TITLE
bug: TS type error without strict mode

### ISSUE THREAD

**Issue by imaksp** [wagmi-dev/viem#1319]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.16.0

### Current Behavior

as per discussion https://github.com/wagmi-dev/viem/discussions/1304 creating issue with TS playground here,
it started giving type error after `1.15.2` update (https://github.com/wagmi-dev/viem/commit/de24c066e905448f778b0c30668f3bf279b3fe7b) if strict/strictNullChecks are false.

### Expected Behavior

It should not give type error.

### Steps To Reproduce

See this playground:
https://www.typescriptlang.org/play?strictNullChecks=false&ts=5.1.6#code/JYWwDg9gTgLgBAbwFBzgYQgOwGbAOYA0KcAxlrngK5QCmaAFgIbCYDORqJtjMd5+HODSgkATAAYAggCEAkoNmYAVjRK8AJhkyZVMaEQC+cbFAgg4AcgACAd0Z4QwAPRlaFgNxJQkWIjghmbRoYAjhIABsATzwsUNYaCOBGOCMTM0tbe0cXJhZWDy9waHgEOBZsakYABVMAN2B1YRTjU3NrOwdnVxondWBWGCcwOobhVidyyoLvYr8wSgAjcOASGoh6xqhmtLbMzpdoHr6BoZHN8fmllemi31K8YK0YKEY1bdbLepoQAqQyNngl2WJEUFReAGkaJE4ABeSwAFQAogBleEAfXBiIAmr9GKxIpgSMZKISYMAsGVMMAYAAKACUiGIpCwAzmi2BaGWNEwITgNhoC2REBIAGtglV2StOcBubySLk2M04f8KNQ6ArWDSmag4ABtAIsHS8+KJRihCLRLAAXUEOr1kxeaw2whppUYYGAkMiAC4wpKQThKl6UnTzf6naMoPSrdq6Z47f9WSr8LDSNxeFoKK7tahGJQ9FodGpfc9KDRbTr-kW9FBWL7dTobHBFCo1DRNFhq9BXaQNSGbTm-VcSNLZRXUPzBcKxTAJcPRzyKwY49rntDkHbUMBsDSAITJvAAOirumgDI3m9QMHopibjbgiKgpijFkLp62-TgmAg8EauB06iHhYK6XgY2qJvAdjhOEjxcjyqaMHY1LMjg+DHp276Hg8MAAOqMNBsEyjy9KeEyEEoc8rzwHC2FPC8ag9oOuYLMAvrCGIUhyOOOqMOo6i0KwdaWOIAAeogACx0DQADMABs4gAOwAIzSAs2AAGJoNgkiyYi4iqYiACcAAc0gKbJslKaINDiLJJDiKIEgACIWNxE74TBMALiETEhkg2pGCQPDyjSwjPueg6JhAMGHuEEB4DSFhhdAvquUIT5nvGOpgQYQA

**Comment by jxom** [comment]
Strict mode is needed to make sure [inference works correctly](https://viem.sh/docs/typescript.html).

**Comment by imaksp** [comment]
Hi, I know that as you told me in one of my previous report, so I created discussion by mentioning it (strict false) but I was told to create issue instead by @tmm. also it is fine if type inference does not work as good as with strict mode but in this case it is giving compile error. but anyways we are in process of enabling strict mode after that we can upgrade to latest viem easily. Thanks.
