### ISSUE TITLE
bug: Holesky rpc endpoint does not support eth_chainId

### ISSUE THREAD

**Issue by mateuszradomski** [wagmi-dev/viem#1320]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.15.3

### Current Behavior

The current RPC endpoint url is `https://rpc.holesky.ethpandaops.io`, it does not support `eth_chainId`. You can validate this by doing:

```
$ cast rpc --rpc-url=https://rpc.holesky.ethpandaops.io eth_chainId
Error: 
(code: -32601, message: Unsupported method: eth_chainId, data: None)
```

Behaviour for a different RPC URL:

```
$ cast rpc --rpc-url=https://ethereum-holesky.publicnode.com eth_chainId
"0x4268"
```

Using `.writeContract()` fails because the endpoint does not support `eth_chainId` but the function is using that function.

### Expected Behavior

Use a RPC that supports `eth_chainId` so that `.writeContract()` passes.

**Comment by jxom** [comment]
Fixed in 1.16.3
