### ISSUE TITLE
bug: `parseAbiParameters` does not recognize the `tuple` keyword

### ISSUE THREAD

**Issue by ardislu** [wagmi-dev/viem#133]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.1.1

### Current Behavior

`parseAbiParameters` doesn't seem to accept the `tuple` keyword. Example:

```javascript
import { encodeAbiParameters, parseAbiParameters } from 'viem';

const types = ['tuple(uint256, uint256)'];
const objects = [[1, 2]];

encodeAbiParameters(parseAbiParameters(types), objects);
// BaseError [AbiTypeError]: Invalid ABI parameter.
```

### Expected Behavior

It should accept the `tuple` keyword, like how `ethers` does:

```javascript
import { AbiCoder } from 'ethers';
const ethersCoder = new AbiCoder();

const types = ['tuple(uint256, uint256)'];
const objects = [[1, 2]];

const ethersResult = ethersCoder.encode(types, objects);
console.log(ethersResult);
// 0x00000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000002
```

I'm not sure how commonly used this syntax is though. I saw it from this blog post: https://blog.ricmoo.com/human-readable-contract-abis-in-ethers-js-141902f4d917

### Steps To Reproduce

Full combined example code:

```javascript
import { AbiCoder } from 'ethers';
import { encodeAbiParameters, parseAbiParameters } from 'viem';
const ethersCoder = new AbiCoder();

const types = ['tuple(uint256, uint256)'];
// Workaround: omit the 'tuple' keyword:
// const types = ['(uint256, uint256)'];
const objects = [[1, 2]];

const ethersResult = ethersCoder.encode(types, objects);
console.log(ethersResult);
// 0x00000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000002

const viemResult = encodeAbiParameters(parseAbiParameters(types), objects);
console.log(viemResult);
// BaseError [AbiTypeError]: Invalid ABI parameter.
```

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://github.com/ardislu/eth-abi-coder-comparison

### Anything else?

As a workaround, you can simply omit the `tuple` keyword:

```javascript
import { encodeAbiParameters, parseAbiParameters } from 'viem';

// Workaround: omit the 'tuple' keyword:
const types = ['(uint256, uint256)'];
const objects = [[1, 2]];

encodeAbiParameters(parseAbiParameters(types), objects);
// 0x00000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000002
```

**Comment by tmm** [comment]
Thanks for checking out viem!

viem's Human-Readable ABIs (powered by [ABIType](https://abitype.dev/api/human.html)) don't support prefixing tuples with the `tuple` keyword. The following are valid though:

```ts
import { parseAbiParameters } from 'viem'

parseAbiParameters('(uint256, uint256)')
parseAbiParameters([
  'struct MyStruct { uint256; uint256; }',
  'MyStruct',
])
```

The reason the `tuple` keyword isn't supported is that it's not valid Solidity! viem's Human-Readable ABIs try to stay as close to valid Solidity signatures as possible. More info [here](https://abitype.dev/api/human.html).
