### ISSUE TITLE
bug: using bun and websocket causes JSON Parse error: Unterminated string

### ISSUE THREAD

**Issue by rori4** [wagmi-dev/viem#1342]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.16.3

### Current Behavior

When trying to do a subscription with a client with a websocket transport and run your script with bun it throws an error 

```
SyntaxError: JSON Parse error: Unterminated string
      at onMessage (.../node_modules/viem/_esm/utils/rpc.js:78:32)
73 |             // Set up a cache for incoming "synchronous" requests.
74 |             const requests = new Map();
75 |             // Set up a cache for subscriptions (eth_subscribe).
76 |             const subscriptions = new Map();
77 |             const onMessage = ({ data }) => {
78 |                 const message = JSON.parse(data);
```

### Expected Behavior

The JSON parsing to not cause this error

### Steps To Reproduce

Note: Bun version = 1.0.5
1. Create a websocket client

```
websocketClient = createPublicClient({
			chain: chain,
			transport: webSocket(websocketEndpoint),
		});
```
2. Subscribe to`watchBlocks`
```
websocketClient.watchBlocks({
			emitOnBegin: true,
			onBlock: (block) => console.log(block),
		});
```

3. run your ts file with bun `bun example.ts`
4. error is thrown

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

NA

**Comment by rori4** [comment]
I think it's related to this one but it has been closed: https://github.com/wagmi-dev/viem/issues/1322

Also if there is a need for a minimal example and the steps are not clear let me know and I can create a github repo.

**Comment by jxom** [comment]
This is a bug in Bun. There is an open issue for it here: https://github.com/oven-sh/bun/issues/6189
