### ISSUE TITLE
bug: Property writeContract does not exist 

### ISSUE THREAD

**Issue by pranav-singhal** [wagmi-dev/viem#1350]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.16.5

### Current Behavior

Whenever I call writeContract on `WalletClient`, I get this error in typescript:

```
Property 'writeContract' does not exist on type '{ account: Account<`0x${string}`> | undefined; batch?: { multicall?: boolean | { batchSize?: number | undefined; wait?: number | undefined; } | undefined; } | undefined; cacheTime: number; ... 10 more ...; extend: () => const; }'.ts(2339)

```

My understanding is that its not defined on the `WalletClient` type. 

### Expected Behavior

Ideally, this should be defined on the type definition of `WalletClient`

**Comment by pranav-singhal** [comment]
PS:

I have noticed a similar problem with functions like:

`getAddresses`

`simulateConctract` 

While I can call them, I have to use `ts-ignore` inorder to compile the typescript

**Comment by jxom** [comment]
Works fine in my minimal reproducible example: https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzjAnmApnA6gQwDZ7owDCew6AdjADRwDGU6OM6uBRp5VtAFjDGFpgcUAM7oAggCNgcAL5wAZlAgg4AcgBu5EOoBQoSLERwQOYBQpF5SlWq06A9HR7mKo-XseO42nHAADBiYWNkISMkoYAL06CHd4OkiqAH0ARjgAXnpGZlZ8cM4ogAoEPTg4HDo4gFcqAC4NAAYAD3VqcvpXC0azCysaTpgoHHcjGEa+AWKASj05OdjkmHSAOgB3KGAWYnjhqphSzpwZRuExSRligG11RTq6GGB4yrAwFU10WfUAXRmOio4AAmQMYolEjXUrXanXuFEezwoADkcCB0JCcG8Puh9As9F4fH5AmEOMsAsg0OhYvFRIlllk4BQagRKqI4HUANYUCDrCis7AFUlcGD4pLCjZbHZ7EaPI6A05wc7iaTAG53B5PF6Y94QT7fP4AyrVCB1CbNNqG4Gg9DgyHQw0uNy9NwDQ1whHxFFojFY3U4+aLIA

Closing, but if you can reproduce it, I will reopen.

**Comment by pranav-singhal** [comment]
I think there was some confusion in the way I explained the issue.

Basically, the code compiles without any problems, but I see this error:
![Uploading Screenshot 2023-10-14 at 11.32.51 PM.png…]()

**Comment by pranav-singhal** [comment]
@jxom  Can you take a look at the last comment?

**Comment by jxom** [comment]
If you provide a minimal reproduction, then I’ll be happy to take a look.

**Comment by vantrung1408** [comment]
same with me, any idea?
