### ISSUE TITLE
Inconsistent block explorer URL formatting 

### ISSUE THREAD

**Issue by AmaxJ** [wagmi-dev/viem#1355]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.14.0

### Current Behavior

Some block explorer urls have a trailing slash, while others don't.

![Screenshot 2023-10-16 at 11 47 46 AM](https://github.com/wagmi-dev/viem/assets/9729784/3a7d8aa7-1da2-43d5-b464-fd805286b741)
![Screenshot 2023-10-16 at 11 47 59 AM](https://github.com/wagmi-dev/viem/assets/9729784/cabbe480-acc9-4c93-9888-6b74d237c3a9)

### Expected Behavior

All urls have a consistent format.

### Steps To Reproduce

This can be seen just by looking at the values of the block explorer default Urls.

**Comment by tmm** [comment]
None should have a trailing slash. Easy fix if you want credit :)
