### ISSUE TITLE
bug: getLogs unexpectedly returns wrong transactionHash in some cases

### ISSUE THREAD

**Issue by korbav** [wagmi-dev/viem#1359]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.16.6

### Current Behavior

getLogs function, sometimes returns wrong transaction hashes.

I'm not able to understand what case would cause this to happen but I'm facing this issue quite often.
Likewise, I'm not able to give you a code to reproduce this issue since it's totally unpredictable.

Thus, just FYI, I'm using this code : 

```
const bridgeLog = await publicClient.getLogs({
        event: parseAbiItem('event LogMessagePublished(address, uint64, uint32, bytes, uint8)'),
        address,
        blockHash,
        strict: true
      });
```

**Comment by jxom** [comment]
viem just relays the transaction hash that is provided by the RPC. Maybe try a different RPC if its returning incorrect data.
