### ISSUE TITLE
bug: `chainId` is being ignored on sendTransaction

### ISSUE THREAD

**Issue by atanasbozhkov** [wagmi-dev/viem#1365]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.16.6

### Current Behavior

I've noticed some odd behaviour when switching chains from the wallet client and immediately sending a tx. 
I believe the issue is related to this: https://github.com/wagmi-dev/wagmi/pull/3076, but is not entirely fixed by it. 

When preparing a writeContract call - `chainId` is passed in and it propagates through writeContract -> sendTransaction -> assertCurrentChain.

The problem I see at the moment is that `sendTransaction` [completely ignores](https://github.com/wagmi-dev/viem/blob/main/src/actions/wallet/sendTransaction.ts#L133) the `chainId` param. 
The `chainId` param is technically inside `rest.chainId`. 
sendTranscation instead opts-in to check `chain` which is defaulted to `client.chain` and in some cases it's null which skips the chain assert entirely. 

The correct behaviour should be to replace [this block](https://github.com/wagmi-dev/viem/blob/main/src/actions/wallet/sendTransaction.ts#L156-L162) with something like: 
```typescript 
if (chain !== null) {
  chainId = await getChainId(client);
  assertCurrentChain({
    currentChainId: chainId,
    chain,
  });
} else if (rest.chainId !== null) {
  if (rest.chainId !== chainid) {
    throw new ChainMismatchError({ rest.chainId, chainid});
  }
}
```

**Comment by atanasbozhkov** [comment]
Happy to raise a PR for this if you have guidance or specific requirements.

**Comment by jxom** [comment]
Can you provide a minimal reproduction of this issue? Wagmi should be passing the correct chain via `chain`, which gets asserted. `chainId` is not a valid parameter to `sendTransaction` (only `chain` is).

Will reopen when a repro is provided!

**Comment by atanasbozhkov** [comment]
I'm not sure what reproduction to provide on incorrectly passed internal parameters. 
It seems that the issue is specifically related to `prepareWriteContract` on Wagmi's side. I'll reopen the issue there instead.
