### ISSUE TITLE
bug: viem not usable in cloudflare worker contexts (EvalError)

### ISSUE THREAD

**Issue by Ncookiez** [wagmi-dev/viem#1375]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.16.6

### Current Behavior

Viem or one of its dependencies seems to use `eval` under the hood, which makes the package not able to be used for CloudFlare workers. I can't seem to pinpoint ***where*** it is being used here.

The error when trying to deploy to CloudFlare through Wrangler is the following:

`EvalError: Code generation from strings disallowed for this context [code: 10021]`

Removing Viem from the codebase makes it possible to deploy the worker.

### Expected Behavior

Viem should be able to be used within CloudFlare workers :)

### Steps To Reproduce

- Write a simple CloudFlare worker.
- Add Viem and a function using it in whatever way.
- Attempt to deploy worker through Wrangler.

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://github.com/Ncookiez/ptlist

^ Not really super minimal, but at least it's reproducible. It is a simple worker that uses Viem for a couple calls and an event log query.

**Comment by jxom** [comment]
Sneaky buggers
