### ISSUE TITLE
waitForTransactionReceipt throw 'block not found' error

### ISSUE THREAD

**Issue by Sanketpatel521** [wagmi-dev/viem#1378]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.16.5

### Current Behavior

waitForTransactionReceipt call throws BlockNotFoundError, But the transaction is approved and gets mined successfully.

**Example log**
```Block at number "49017707" could not be found.

Version: viem@1.16.5
BlockNotFoundError: Block at number "49017707" could not be found.

Version: viem@1.16.5
    at getBlock (/app/node_modules/viem/_cjs/actions/public/getBlock.js:25:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.onBlockNumber (/app/node_modules/viem/_cjs/actions/public/waitForTransactionReceipt.js:70:47)
```
### Expected Behavior

waitForTransactionReceipt should return the transaction receipt and not throw an error if a transaction is successful.

### Steps To Reproduce

normally using waitForTransactionReceipt, it should throw an error I mentioned randomly.

### Anything else?

i am using ankr paid rpc.

**Comment by jxom** [comment]
Thanks for reporting. Can you please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) via https://new.viem.sh or a separate repo? It will save us a lot of time reproducing your config & environment, and trying to reproduce your issue. See [Why reproductions are required](https://antfu.me/posts/why-reproductions-are-required).

Please reopen this issue when a reproduction is added.
