### ISSUE TITLE
bug: Address | Account unimplemented multicall

### ISSUE THREAD

**Issue by joeblau** [wagmi-dev/viem#1380]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.16.1

### Current Behavior

This property does not exist: https://viem.sh/docs/contract/multicall.html#account-optional

This is the error:

> Object literal may only specify known properties, and 'account' does not exist in type 'MulticallParameters<[{ functionName: "totalSupply"; address:

```
  const results = await client.multicall({
    contracts: [
      {
        address: getAddress("0x06450dEe7FD2Fb8E39061434BAbCFC05599a6Fb8"),
        abi: XEN_CRYPTO_ABI,
        functionName: "getUserMint",
        account: "0xBFBE733d560bc0a4E5502587853f92b3aE83344F",
      },
    ],
    account: "0xBFBE733d560bc0a4E5502587853f92b3aE83344F",
  });
```

### Expected Behavior

Multicall should support passing an account the same way `readContract` does.

https://viem.sh/docs/contract/readContract.html#account-optional

### Steps To Reproduce

Implement the sample code from the site in TypeScript.

Error will show up.

### Anything else?

<img width="805" alt="image" src="https://github.com/wagmi-dev/viem/assets/1218847/6de2e24a-b7ba-43ce-a8f6-c335693e18d3">
<img width="863" alt="image" src="https://github.com/wagmi-dev/viem/assets/1218847/2b80eaff-c957-49ed-9731-0858f8fae7bd">

**Comment by jxom** [comment]
Need to update the docs, but account doesn’t exist because `msg.sender` turns into the multicall contract address and not the one which you pass.

**Comment by joeblau** [comment]
Thanks for checking on this!
