### ISSUE TITLE
bug: random chain id error on transactions sometimes

### ISSUE THREAD

**Issue by deanpress** [wagmi-dev/viem#1389]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.16.6

### Current Behavior

Sometimes when calling `publicClient.writeContract({...})` I get an error that the chain ID is incorrect. Strangely, the chain ID is either 0, 1, infinity, or a seemingly random number like `26121166`.

The chain id is set normally with `viem.defineChain({ id: 123 })`, and it works upon retrying the same transaction. It appears to happen randomly, and happens more frequently when making lots of concurrent transactions:

```
2|beacon  | 2 | Object.defineProperty(exports, "__esModule", { value: true });
2|beacon  | 3 | exports.BaseError = void 0;
2|beacon  | 4 | const utils_js_1 = require("./utils.js");
2|beacon  | 5 | class BaseError extends Error {
2|beacon  | 6 |     constructor(shortMessage, args = {}) {
2|beacon  | 7 |         super();
2|beacon  |             ^
2|beacon  | TransactionExecutionError: The current chain of the wallet (id: 26121166) does not match the target chain for the transaction (id: 42170 – undefined).
2|beacon  | Current Chain ID:  26121166
2|beacon  | Expected Chain ID: 42170 – undefined
2|beacon  |
2|beacon  | Request Arguments:
2|beacon  |   from:   ...
2|beacon  |   to:     ...
2|beacon  |   data:   ...
2|beacon  |   gas:    5000000
2|beacon  |   nonce:  ...
2|beacon  | Version: viem@1.16.5
2|beacon  |       at new BaseError (/root/beacon/node_modules/viem/_cjs/errors/base.js:7:8)
2|beacon  |       at new TransactionExecutionError (/root/beacon/node_modules/viem/_cjs/errors/transaction.js:155:8)
2|beacon  |       at getTransactionError (/root/beacon/node_modules/viem/_cjs/utils/errors/getTransactionError.js:14:11)
2|beacon  |       at /root/beacon/node_modules/viem/_cjs/actions/wallet/sendTransaction.js:77:8
2|beacon  |       at processTicksAndRejections (:55:76)
2|beacon  |       at processTicksAndRejections (:55:76)
```

### Expected Behavior

When making a transaction, the chain id should be static and never different from what is defined in the chain.

### Steps To Reproduce

Set up a custom chain like:
```js
      const chain = /*#__PURE__*/ viem.defineChain({
        id: Number(process.env.CHAIN_ID),
        name: process.env.CHAIN_NAME,
        network: process.env.CHAIN_NAME,
        nativeCurrency: {
          decimals: 18,
          name: "Ether",
          symbol: "ETH",
        },
        rpcUrls: {
          default: { http: ... },
          public: { http: ... },
        },
        fees: {
          baseFeeMultiplier: 1.15,
        },
      });
```

Then assign the chain to a transport (I'm using a fallback transport):
```
const transport = viem.fallback([...httpTransports, ...wsTransports], {
        retryCount: 10,
        retryDelay: 1000,
      });
```

and a wallet:
```
    signer = viem.createWalletClient({
      account,
      chain: chain,
      transport: transport,
      cacheTime: 350,
    });
```

Then, spam a lot of contract writes. Eventually you'll see some strange errors pop up, including this one about the chain id.

**Comment by tmm** [comment]
Thanks for reporting. Can you please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) via https://new.viem.sh or a separate repo? It will save us a lot of time reproducing your config & environment, and trying to reproduce your issue. See [Why reproductions are required](https://antfu.me/posts/why-reproductions-are-required).

Please reopen this issue when a reproduction is added.

**Comment by jxom** [comment]
What wallet are you using? The "current" Chain ID comes from there, so likely the wallet is giving you a bogus chain ID.

**Comment by nalinbhardwaj** [comment]
@tmm @jxom we've seen this reproduce in https://github.com/daimo-eth/daimo/blob/master/packages/daimo-api/src/network/viemClient.ts -- don't have a smaller reproduction but the wallet client is set up in the backend API with the right chain config and there should be no path to a wallet client with an incorrect chain config, but occasionally (maybe once every ~2 weeks ?) we see a failure like:

```
The current chain of the wallet (id: 1) does not match the target chain for the transaction (id: 8453 – Base).
```

**Comment by danaugrs** [comment]
We're seeing this as well. Obtaining the chain id from Wagmi's `useChainId` hook returns `1` but submitting the transaction when connected via WalletConnect V2 seems to think the chain is `137` Polygon.

```
TransactionExecutionError: The current chain of the wallet (id: 137) does not match the target chain for the transaction (id: 1 – undefined).

Current Chain ID:  137
Expected Chain ID: 1 – undefined
```
