### ISSUE TITLE
The method does not exist / is not available.

### ISSUE THREAD

**Issue by Haianh9999** [wagmi-dev/viem#1394]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.10.12

### Current Behavior

When I connect to the metamask app on the phone and signMessage on the phone I get the error: 
The method does not exist / is not available.

- Screenshot: 
<img width="994" alt="Screenshot 2023-10-26 at 10 21 20" src="https://github.com/wagmi-dev/viem/assets/96808297/fdb7e33c-8be7-4961-b2ae-4deae9aff0f0">

**Comment by Haianh9999** [comment]
@jxom Could you help me resolve this issue? 🙇

**Comment by jxom** [comment]
Thanks for reporting. Can you please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) via https://new.viem.sh or a separate repo? It will save us a lot of time reproducing your config & environment, and trying to reproduce your issue. See [Why reproductions are required](https://antfu.me/posts/why-reproductions-are-required).

Please reopen this issue when a reproduction is added.
