### ISSUE TITLE
bug: invalid abi

### ISSUE THREAD

**Issue by skiv71** [wagmi-dev/viem#1406]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

latest

### Current Behavior

viem complains about the following abi, which was auto generated by ethers and works in ethers...

function getAllRequests() view returns (tuple(bytes32 id, address owner, tuple(address payee, address payer, address token, uint8 status, uint8 _type, uint256 value, uint256 paid, uint256 redeemed, uint256 refunded, uint256 dueDate, string conversion) data, tuple(address party, int256 value, uint256 timestamp, string note)[] transactions, string metadata, uint256 timestamp, tuple(uint256 payeeReleased, uint256 payerReleased) escrow)[] list)

### Expected Behavior

Would like it to work

### Steps To Reproduce

try parseAbi on the above

### Anything else?

No

**Comment by jxom** [comment]
That is an Ethers flavored ABI. Viem only supports generic flavored ABIs. To fix this, simply find and replace the word `”tuple”` with `””`.

**Comment by skiv71** [comment]
Ah, my bad... thanks for the heads up!
