### ISSUE TITLE
bug: Property 'read' does not exist on type 'GetContractReturnType'

### ISSUE THREAD

**Issue by skiv71** [wagmi-dev/viem#1407]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

latest

### Current Behavior

Vscode intellisense reports <contract>.read does not exist.

I've checked the code and it's not clear if the return type interface declares the read property, although I can see it's added during the passing of publicClient.

I've also confirmed it exists in the browser and it does work as intended.

**Comment by jxom** [comment]
Thanks for reporting. Can you please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) via https://new.viem.sh or a separate repo? It will save us a lot of time reproducing your config & environment, and trying to reproduce your issue. See [Why reproductions are required](https://antfu.me/posts/why-reproductions-are-required).

Please reopen this issue when a reproduction is added.
