### ISSUE TITLE
bug: Wrong explorer link for Neon DevNet chain

### ISSUE THREAD

**Issue by mnedelchev-vn** [wagmi-dev/viem#1425]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

viem@1.18.2

### Current Behavior

The issue is that this piece of code located here [https://github.com/wagmi-dev/viem/blob/main/src/chains/definitions/neonDevnet.ts](https://github.com/wagmi-dev/viem/blob/main/src/chains/definitions/neonDevnet.ts)
```typescript
blockExplorers: {
    default: {
      name: 'Neonscan',
      url: 'https://neonscan.org',
    },
  }
``` 
has wrong values.

### Expected Behavior

It should be:
```typescript
blockExplorers: {
    default: {
      name: 'Neonscan DevNet',
      url: 'https://devnet.neonscan.org',
    },
  }
``` 
``` 

### Steps To Reproduce

_No response_

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

_No response_

### Anything else?

<img width="1284" alt="Screenshot 2023-11-01 at 16 54 20" src="https://github.com/wagmi-dev/viem/assets/45385208/2e09b0c2-b9f6-4881-b7ca-8614d17796e4">

**Comment by jxom** [comment]
Fixed!
