### ISSUE TITLE
bug: iframe not initialized

### ISSUE THREAD

**Issue by outdoteth** [wagmi-dev/viem#1437]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.17.1

### Current Behavior

I'm getting an iframe error when I first log in with privy and then try to submit a transaction. When I refresh and try again, it works. Here is the error:

```
TransactionExecutionError: An unknown RPC error occurred.

Request Arguments:
  from:  0x87F7e276baf2eE9c11fcA3F813E02841F0e32110
  to:    0x9Dc7BD779E470CdA3273Dff07b61A7dD9a57924E
  data:  0xefc81a8c

Details: iframe not initialized
Version: viem@1.17.1
    at getTransactionError (900-6120cd6fd118d411.js:21:32436)
    at sendTransaction (900-6120cd6fd118d411.js:21:33539)
    at async writeContract (900-6120cd6fd118d411.js:21:33844)
    at async submit (733-cc2baf9517ceb6b0.js:1:1069)
```

**Comment by jxom** [comment]
Thanks for reporting. The error in the "Details" there is coming from an external source, so likely not viem. If you suspect this is a viem issue, can you please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) via https://new.viem.sh or a separate repo? It will save us a lot of time reproducing your config & environment, and trying to reproduce your issue. See [Why reproductions are required](https://antfu.me/posts/why-reproductions-are-required).

Please reopen this issue when a reproduction is added.
