### ISSUE TITLE
fetchFeeData  throws an error

### ISSUE THREAD

**Issue by Marcelh1983** [wagmi-dev/viem#1440]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.18.4

### Current Behavior

`fetchFeeData`  throws an error:

> error: InternalRpcError: An internal error was received. URL: https://cloudflare-eth.com Request body: {"method":"eth_getBlockByNumber","params":["latest",false]} Details: Internal error Version: viem@1.18.4

see: [codesandbox](https://codesandbox.io/p/sandbox/wagmi-fetch-gas-wvfqwp?file=%2Fsrc%2FApp.tsx%3A1%2C1): 

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://codesandbox.io/p/sandbox/wagmi-fetch-gas-wvfqwp?file=%2Fsrc%2FApp.tsx%3A1%2C1

**Comment by jxom** [comment]
Cloudflare (default mainnet public RPC) is currently experiencing a major outage. As always, in production, you should provide your own RPC URL to the transports.
