### ISSUE TITLE
bug: watchContractEvent does not filter

### ISSUE THREAD

**Issue by Celeborn2BeAlive** [wagmi-dev/viem#1454]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.18.6

### Current Behavior

When using `client.watchContractEvent` with `eventName: 'Transfer'` as filter, I still get other events ("Approval" for example).

### Expected Behavior

I was expecting `onLogs` to only be called with "Transfer" events.

### Steps To Reproduce

1. Go on the minimal example https://stackblitz.com/edit/viem-getting-started-rrjssr?file=index.ts and open JS console
2. Go on Goerli's UNI contract page https://goerli.etherscan.io/address/0x1f9840a85d5af5bf1d1762f925bdaddc4201f984#writeContract and call approve with some parameters
3. See on the JS console the log of the approval event

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/edit/viem-getting-started-rrjssr?file=index.ts

### Anything else?

Maybe I misunderstood something from the event filtering system. In that case please tell me, but reading the doc I was pretty sure to do the right thing.
The doc mentions:

> watchContractEvent will attempt to create an [Event Filter](https://viem.sh/docs/contract/createContractEventFilter.html) and listen to changes to the Filter per polling interval, however, if the RPC Provider does not support Filters (ie. eth_newFilter), then watchContractEvent will fall back to using [getLogs](https://viem.sh/docs/actions/public/getLogs.html) instead.

So I guess my RPC does not support `eth_newFilter`, but I was expecting `getLogs` to do the filtering with scoping as explained in https://viem.sh/docs/actions/public/getLogs.html.

**Comment by jxom** [comment]
Fixed in `1.18.7`.
