### ISSUE TITLE
bug: estimateContractGas returns a different value from estimateGas

### ISSUE THREAD

**Issue by junhuang-ho** [wagmi-dev/viem#1466]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.18.0

### Current Behavior

From the [docs](https://viem.sh/docs/contract/estimateContractGas.html), `estimateContractGas` calls `estimateGas` internally. But when I call them both on a contract function call, they both return different gas values. Shouldn't they be the same? If not, why are they different?

### Expected Behavior

same gas values

### Steps To Reproduce

```
const params = {
    address: "0x...",
    abi: abi,
    functionName: "testFn",
    args: [13],
    account,
  };
  
const gas = await publicClient.estimateContractGas(params as any);

const gasEstimate = await publicClient.estimateGas(params as any);
```

**Comment by jxom** [comment]
You are passing invalid parameters to `estimateGas`. Internally, `estimateContractGas` encodes the contract function data, and then populates the `data` parameter of `estimateGas` with the encoded function data.
