### ISSUE TITLE
bug: hexToString returns string where length is 32

### ISSUE THREAD

**Issue by sosoxuc** [wagmi-dev/viem#1476]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.18.9

### Current Behavior

hexToString("0x73424e4250455250000000000000000000000000000000000000000000000000").length = 32
hexToString("0x73424e4250455250000000000000000000000000000000000000000000000000").trim().length = 32
hexToString("0x73424e4250455250000000000000000000000000000000000000000000000000") = "sBNBPERP"

### Expected Behavior

hexToString("0x73424e4250455250000000000000000000000000000000000000000000000000").length = 8
hexToString("0x73424e4250455250000000000000000000000000000000000000000000000000") = "sBNBPERP"

### Steps To Reproduce

Try code above

### Anything else?

No

**Comment by jxom** [comment]
For "32 bytes"-like strings you need to pass a size: `hexToString("...", { size: 32 })`

If coming from Ethers:
- `decodeBytes32String` == `hexToString("...", { size: 32 })`
- `toUtf8String` == `hexToString("...")`

**Comment by sosoxuc** [comment]
Current Behavior
hexToString("0x73424e4250455250000000000000000000000000000000000000000000000000").length = 32
hexToString("0x73424e4250455250000000000000000000000000000000000000000000000000").trim().length = 32
hexToString("0x73424e4250455250000000000000000000000000000000000000000000000000") = "sBNBPERP"

Expected Behavior
hexToString("0x73424e4250455250000000000000000000000000000000000000000000000000").length = 8
hexToString("0x73424e4250455250000000000000000000000000000000000000000000000000") = "sBNBPERP"


This is not right....

**Comment by sosoxuc** [comment]
@jxom ^^

**Comment by jxom** [comment]
`hexToString` literally processes each byte and converts it to a UTF-8 character, so the empty string characters are valid. 

To get it to work with your expected behavior, please read my reply: https://github.com/wagmi-dev/viem/issues/1476#issuecomment-1804721339

**Comment by sosoxuc** [comment]
Your reply does not contain solution

**Comment by jxom** [comment]
It does. You need to specify the bytes size.

```diff
hexToString(
  "..."
+ { size: 32 }
)
```
