### ISSUE TITLE
bug: multicall compile issue

### ISSUE THREAD

**Issue by sosoxuc** [wagmi-dev/viem#1478]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.18.9

### Current Behavior

I try to use multicall but not working

    const results = await client.multicall(
        {contracts:[{
            address: "0x18f763fd61Efd3D9884981CC2CBd6845351e4b70",
            abi: marketAbi,
            functionName: "proxy"
        }]})

### Expected Behavior

    const results = await client.multicall(
        {contracts:[{
            address: "0x18f763fd61Efd3D9884981CC2CBd6845351e4b70",
            abi: marketAbi,
            functionName: "proxy"
        }]})

Should compile

### Steps To Reproduce

![Screenshot from 2023-11-10 02-44-46](https://github.com/wagmi-dev/viem/assets/2141167/cd405055-98dd-4c46-bb54-f00bfb231d02)

The same call using readContract works well

**Comment by sosoxuc** [comment]
https://stackblitz.com/edit/stackblitz-starters-wkssnu?file=main.ts

**Comment by tmm** [comment]
Works fine for me: [TypeScript Playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgYygUwIYzQBQK4BGANsMgMIloB2MANHABYwxhwC+cAZlBCHAOQA3YGhD8AUOOQQqAZ3ggMUANZoYAQQLA4AXjgBtcXERHjKGfIw0AXHBhQ8aWqePAqYPDFm39AXWdmcFQYIGi2-GA8AB4AnvwBZhCeHl4+LmYI6YFu2FDBRAAqMWBhAtI0UBjI8DjRcQmBxjDFpfwYACbt6LKy8VnsDXD+6WAYMRjEpZwYRLJO6ZbYALKeE8AkzeHCaADufYHNJeGceFTVwDL7A+K+cBiy5nIwkuXyKJQ0uijoWLiEJOQPjAABSZJqVOSQWC2JgsYEASmcbHhLws8G6eCIXi+GB2GGA8GQQIAdCBMTBSDMiKDTOV7FVUgZ0mDGh0umgeuEAAxRACMAA5OAB2ABsAGZOO0RbyAKKSsUAEQAnPz+QAWFW8shkABMZAAQlL1QBWMXG3loNUEIVcq6BNa2RQqNSaYCDYwnM4UmQAORCrUiEFiduuxmGyMkGKxsnEAHpY3AAHoAfiAA)
