### ISSUE TITLE
bug: viem not able to parse getBlockNumber response

### ISSUE THREAD

**Issue by makemake-kbo** [wagmi-dev/viem#1490]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

latest

### Current Behavior

When viem is pointing to [blutgang](https://github.com/rainshowerLabs/blutgang), it fails to get the block number and returns a `TypeError: Invalid argument type in ToBigInt operation` error.

Im not a JS/TS person, but my guess would be is that its parsing the response wrong.
```
response: {"jsonrpc":"2.0","id":1,"result":"0x11b442f"}
```

Original issue on blutgang repo: https://github.com/rainshowerLabs/blutgang/issues/35

### Expected Behavior

Work

### Steps To Reproduce

1. Set up a client pointing to Blutgang
2. call getblocknumber

**Comment by jxom** [comment]
I assume this has been [fixed](https://github.com/rainshowerLabs/blutgang/issues/35#issuecomment-1808625657) now?

**Comment by gskril** [comment]
Weirdly no, viem's `client.request({ method: 'eth_blockNumber' })` is still returning undefined while I'm getting a valid response through a curl request.

**Comment by makemake-kbo** [comment]
> Weirdly no, viem's `client.request({ method: 'eth_blockNumber' })` is still returning undefined while I'm getting a valid response through a curl request.

+1, @jxom the fix mentioned makes blutgang reject non-compliant requests. it does not fix the viem issue

**Comment by jxom** [comment]
Can take a look shortly. Does Blutgang provide `application/json` content type in its **response** headers?

**Comment by jxom** [comment]
Looks like not: https://github.com/rainshowerLabs/blutgang/blob/0220211a3942b38753aceb044b0726e8492b36e2/src/balancer/accept_http.rs#L286

might be good to add `.header(“Content-Type”, “application/json”)` to the builder.
