### ISSUE TITLE
Update Block Explorer URL for Avalanche Network from SnowTrace to Avascan

### ISSUE THREAD

**Issue by barskhianfannie** [wagmi-dev/viem#1497]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.15.1

### Current Behavior

The default explorer URL for Avalanche is `SnowTrace`, however, this platform will be deprecated on Nov. 30th. 

### Expected Behavior

Update the default URL to Avascan -`https://avascan.info/`

**Comment by tmm** [comment]
Feel free to [create a PR](https://github.com/wagmi-dev/viem/blob/main/.github/CONTRIBUTING.md)! We don't normally spend our time on things like this.
