### ISSUE TITLE
bug: `getAction()` + JS minification results in weird behavior

### ISSUE THREAD

**Issue by jbrower95** [wagmi-dev/viem#1502]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.19.x

### Current Behavior

- `getAction()` ends up indexing based on the function's name, which many minifiers will minify. This leads to inconsistent behavior in production if you're not using the fallbacks, especially for apps using `react-scripts`.

for example-
   1. instantiate a walletClient
   2. overwrite `walletClient.writeContract` or another dispatched action, to provide custom behavior
   3. attempt to use this action through a mechanism which uses `getAction(..)` to resolve it (e.g call getContract(...) with the walletClient and perform call a `.write.*` function)

You'll see that this works in a dev build, but not a production build (e.g via react-scripts, where minification takes place).

Generally, overriding these properties in a production build will not produce the desired effect.

## What was I even trying to do?
  I was trying to override `writeContract` to send a user operation instead of a normal RPC :) This works fine in dev, but fails in production for the above reason.

Just flagging here in case anyone else runs into this -- but anything that `getAction` touches likely can't be minified safely.

### Expected Behavior

Cleanly overriding `walletClient.writeContract` should be safely picked up, even if I have a minifier enabled.

### Steps To Reproduce

1. create a wallet client.
2. override `walletClient.writeContract`.
3. call any function in your code that would invoke writeContract
4. observe that in a dev build via react-scripts, this is fine
5. observe that in a prod build with minification (`npm run build`), this breaks silently

**Comment by jbrower95** [comment]
Doing something like `keep_fnames`, and ejecting from react work, but those are not standard.. :)

**Comment by jbrower95** [comment]
Looking at this code, it seems if you overwrite _anything_ that `getAction()` touches, your minifier will wreck you at access time.


The only way around this for me is if you guys exported `writeContract` and all your other fallback functions, so that I could overwrite based on `writeContract.name` directly...

**Comment by jbrower95** [comment]
Yep, doing:

```

import { writeContract } from "viem/actions";

walletClient[writeContract.name] = alternateImplementation;

```

works fine in both dev and prod.

Definitely a nice gotcha though :)

**Comment by jbrower95** [comment]
API-wise, I wonder if `createWalletClient` could just accept overrides for those common actions as part of that constructor. Makes more sense than imperative overwriting like this IMO

**Comment by jxom** [comment]
Slightly annoying. Reason why we don't extend in the constructor is because we need to curry the client to the actions. Can look at relying on another property apart from `Function.prototype.name` though (ie. define our own).

**Comment by jbrower95** [comment]
Thanks for the quick fix!
