### ISSUE TITLE
Hello how to get a signer after create an account using mnemonicToAccount() function

### ISSUE THREAD

**Issue by francelwebdev** [wagmi-dev/viem#1510]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

latest

### Anything else?

Hello how to get a signer after create an account using mnemonicToAccount() function

**Comment by tmm** [comment]
Please do not create issues that are already discussions. Duplicate https://github.com/wagmi-dev/viem/discussions/1509
