### ISSUE TITLE
Hello I'm getting an error on ligne 128

### ISSUE THREAD

**Issue by francelwebdev** [wagmi-dev/viem#1511]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

latest

### Anything else?

Hello I'm getting an error on ligne 128

![Sélection_003](https://github.com/wagmi-dev/viem/assets/18377068/3bac81e1-899e-4c20-b578-dd77b6ca8e96)

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.
