### ISSUE TITLE
bug: AbiEncodingLengthMismatchError: ABI encoding params/values length mismatch.

### ISSUE THREAD

**Issue by dlnuchunge** [wagmi-dev/viem#1515]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.19.1

### Current Behavior

AbiEncodingLengthMismatchError: ABI encoding params/values length mismatch.
Expected length (params): 1
Given length (values): 0
Version: viem@1.19.1
![image](https://github.com/wagmi-dev/viem/assets/25683599/6c8f0756-387c-4b93-8440-80ef5b2a4d91)

**Comment by jxom** [comment]
Thanks for reporting. Can you please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) via https://new.viem.sh or a separate repo? It will save us a lot of time reproducing your config & environment, and trying to reproduce your issue. See [Why reproductions are required](https://antfu.me/posts/why-reproductions-are-required).

Please reopen this issue when a reproduction is added.
