### ISSUE TITLE
bug: Compact signature produced by `hexToCompactSignature` is invalid

### ISSUE THREAD

**Issue by m3th0d** [wagmi-dev/viem#1516]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.19.3

### Current Behavior

When using `hexToCompactSignature(...)` function for converting a full (65 bytes) signature into its compact form, I faced an issue when a contract won't properly recover the signer. The contract uses OpenZeppelin's (v5.0.0) [`ECDSA.recover`](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/932fddf69a699a9a80fd2396fd1a2ab91cdda123/contracts/utils/cryptography/ECDSA.sol#L112) function.

After some research I found that obtaining compact form of the same full signature via two calls `signatureToCompactSignature(hexToSignature(...))` does the trick and the same contract now recovers signer correctly.

In my case the produced compact signatures differ only in the first bit of the `yParityAndS` part:
- `hexToCompactSignature(...)` has the first bit of `yParityAndS` equal to `0`
- `signatureToCompactSignature(hexToSignature(...))` has the first bit of `yParityAndS` equal to `1`

See "Steps To Reproduce" section for my exact scenario demonstrating inconsistency in compact signature results by these two conversion methods.

### Expected Behavior

Converting full signature to its compact form should produce consistent result regardless of what method is used:

- `hexToCompactSignature(...)`
- `signatureToCompactSignature(hexToSignature(...))`

Most likely the `hexToCompactSignature(...)` function implementation should be fixed to work correctly like `signatureToCompactSignature(hexToSignature(...))` already does. See "Anything else" section for my assumption.

### Steps To Reproduce

Here is a test I implemented to demonstrate the issue (passes successfully).

It shows unexpected different compact signatures produced via two conversion methods:
- __A__: via `signatureToCompactSignature(hexToSignature(signature))` - _valid result_ ✅
- __B__: via `hexToCompactSignature(signature)` - _invalid result_ ❌

```ts
import { hexToCompactSignature, hexToSignature, signatureToCompactSignature } from 'viem';
import { expect } from 'chai';

it('Should reproduce Viem compact signature conversion issue', async function () {
  const signature = '0x595dd91a45941447ab6bba95ae68abf13370c06956a39bd401f881f1bc7935d306a09a43c54b9fb884a038aab9837e5c8993989a3069f68e6ac7b9b158fa13921c';

  // Compact signature conversion A: via `hexToSignature` + `signatureToCompactSignature`
  // Result signature is VALID - recoverable with OpenZeppelin's `ECDSA.recover(bytes32 hash, bytes32 r, bytes32 vs)`
  const compactSignatureA = signatureToCompactSignature(hexToSignature(signature));
  expect(compactSignatureA.r).to.be.equal('0x595dd91a45941447ab6bba95ae68abf13370c06956a39bd401f881f1bc7935d3');
  expect(compactSignatureA.yParityAndS).to.be.equal('0x86a09a43c54b9fb884a038aab9837e5c8993989a3069f68e6ac7b9b158fa1392');

  // Compact signature conversion B: via `hexToCompactSignature`
  // Result signature is INVALID - NOT recoverable with OpenZeppelin's `ECDSA.recover(bytes32 hash, bytes32 r, bytes32 vs)`
  const compactSignatureB = hexToCompactSignature(signature);
  expect(compactSignatureB.r).to.be.equal('0x595dd91a45941447ab6bba95ae68abf13370c06956a39bd401f881f1bc7935d3');
  expect(compactSignatureB.yParityAndS).to.be.equal('0x06a09a43c54b9fb884a038aab9837e5c8993989a3069f68e6ac7b9b158fa1392');

  // The difference is in the first bit of produced `yParityAndS`: 1 (A) vs 0 (B), i.e. 0x8... vs 0x0... here
  expect(compactSignatureA.r).to.be.equal(compactSignatureB.r);
  expect(compactSignatureA.yParityAndS).to.be.not.equal(compactSignatureB.yParityAndS);
  expect(compactSignatureA.yParityAndS).to.be.equal('0x8' + compactSignatureB.yParityAndS.slice(3));
});
```

### Anything else?

My assumption is there is an issue in the `hexToCompactSignature(...)` implementation.

It simply does not take into account `v` value returned by [`secp256k1.Signature.fromCompact`](https://github.com/wagmi-dev/viem/blob/2d581ac55d9753cd82baa6f8d3b6e5a7cc5b6721/src/utils/signature/hexToCompactSignature.ts#L23). I guess it makes this function work ~50% of the time, when the highest bit of `s` matches the bit what `v` should've been encoded to.

Unlike this function, the `signatureToCompactSignature(hexToSignature(...))` does work correctly because it:
- saves `v` value to the `Signature` struct in [`hexToSignature(...)`](https://github.com/wagmi-dev/viem/blob/2d581ac55d9753cd82baa6f8d3b6e5a7cc5b6721/src/utils/signature/hexToSignature.ts#L24)
- reflects `v` value in the first bit of returned `yParityAndS` in [`signatureToCompactSignature(...)`](https://github.com/wagmi-dev/viem/blob/2d581ac55d9753cd82baa6f8d3b6e5a7cc5b6721/src/utils/signature/signatureToCompactSignature.ts#L40)

**Comment by m3th0d** [comment]
Sorry, I misunderstood the API: `hexToCompactSignature(...)` expects _compact_ signature hex, not _full_ signature hex to convert to compact form

**Comment by hbriese** [comment]
Just tried this as well. Perhaps `hexToCompactSignature` can throw if a compact signature isn't passed in.

```diff
export function hexToCompactSignature(signatureHex: Hex): CompactSignature {
+ if (signatureHex.length !== 130) throw ...
  const { r, s } = secp256k1.Signature.fromCompact(signatureHex.slice(2, 130))
  return {
    r: numberToHex(r, { size: 32 }),
    yParityAndS: numberToHex(s, { size: 32 }),
  }
}
```

**Comment by m3th0d** [comment]
I agree, asserting the length would prevent such a misuse

Also note that the function [doc](https://github.com/wagmi-dev/viem/blob/9871061f7ebea102f8a0fb2d9d927ecc2067122f/src/utils/signature/hexToCompactSignature.ts#L19C40-L19C40) has a mistake in the example code:

```
 * @example
 * hexToCompactSignature('0x6e100a352ec6ad1b70802290e18aeed190704973570f3b8ed42cb9808e2ea6bf4a90a229a244495b41890987806fcbd2d5d23fc0dbe5f5256c2613c039d76db81c')
 * // { r: '0x...', yParityAndS: '0x...' }
```

The signature is 65 bytes long here, should be 64

**Comment by jxom** [comment]
Happy for someone to make a PR!
