### ISSUE TITLE
publicClient.estimateGas() function not return the value.

### ISSUE THREAD

**Issue by francelwebdev** [wagmi-dev/viem#1517]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

latest

### Anything else?

Hello,
The publicClient.estimateGas() function not return the value.
It return (err: insufficient funds for gas * price + value)

I expected it to return the value even if the wallet balance is 0.

**Comment by tmm** [comment]
Thanks for reporting. Can you please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) via https://new.viem.sh or a separate repo? It will save us a lot of time reproducing your config & environment, and trying to reproduce your issue. See [Why reproductions are required](https://antfu.me/posts/why-reproductions-are-required).

Please reopen this issue when a reproduction is added.
