### ISSUE TITLE
WebSocket is not a constructor

### ISSUE THREAD

**Issue by daron4ever** [wagmi-dev/viem#1535]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.19.8

### Current Behavior

I have the following error with the webSocket connection.

UnknownRpcError: An unknown RPC error occurred.

Details: WebSocket is not a constructor
Version: viem@1.19.7
    at withRetry.delay.count.count (.../node_modules/viem/utils/buildRequest.ts:195:21)
    at attemptRetry (.../node_modules/viem/utils/promise/withRetry.ts:37:22) {
  details: 'WebSocket is not a constructor',
  docsPath: undefined,
  metaMessages: undefined,
  shortMessage: 'An unknown RPC error occurred.',
  version: 'viem@1.19.7',
  cause: TypeError: WebSocket is not a constructor
      at fn (.../node_modules/viem/utils/rpc.ts:175:25)
      at Timeout.exec (.../node_modules/viem/utils/promise/createBatchScheduler.ts:66:5)
      at listOnTimeout (node:internal/timers:568:17)
      at process.processTimers (node:internal/timers:511:7),
  code: -1
}

### Steps To Reproduce

```
const localhost = webSocket('ws://127.0.0.1:xxxx');
const client = createPublicClient({
    chain: mainnet,
    transport: localhost,
});
const _viem = await client.getBlockNumber();
```

**Comment by jxom** [comment]
Thanks for reporting. Can you please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) via https://new.viem.sh or a separate repo? It will save us a lot of time reproducing your config & environment, and trying to reproduce your issue. See [Why reproductions are required](https://antfu.me/posts/why-reproductions-are-required).

Please reopen this issue when a reproduction is added.

**Comment by daron4ever** [comment]
> Thanks for reporting. Can you please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) via https://new.viem.sh or a separate repo? It will save us a lot of time reproducing your config & environment, and trying to reproduce your issue. See [Why reproductions are required](https://antfu.me/posts/why-reproductions-are-required).
> 
> Please reopen this issue when a reproduction is added.

That is the minimal code. It is private full node for localhost. I also have tested with infrura wss and also not working. But it is working well with ethers 5/6 and web3 v1/v4.
