### ISSUE TITLE
bug: forge must be installed before pnpm install

### ISSUE THREAD

**Issue by rin-st** [wagmi-dev/viem#167]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.1.7

### Current Behavior

Making steps from `CONTRIBUTING.md`. Getting error trying to `pnpm install` without installing `forge`.

<img width="869" alt="Снимок экрана 2023-03-09 в 19 16 19" src="https://user-images.githubusercontent.com/25638585/224070272-c76a3d11-b477-4266-87d6-718d0f6ca713.png">

`postinstall` script contains `wagmi generate`, which requires `forge` to be installed

### Expected Behavior

Installing `foundry` should be described before `pnpm install`

### Steps To Reproduce

- remove forge
- `pnpm install`

**Comment by jxom** [comment]
Updated the guide!
