### ISSUE TITLE
bug: 'viem/ethers' is incorrect path

### ISSUE THREAD

**Issue by insulineru** [wagmi-dev/viem#187]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.1.10

### Current Behavior

In the example from the documentation on [connecting a local account](https://viem.sh/docs/clients/wallet.html#ethers-js-wallet), I have to make a wallet using the `getAccount` utility imported from `viem/ethers`. But there is nothing in this path in the library. 

### Expected Behavior

I expected to see the import of the required utility to connect `ethers` or a description in the documentation about the fact that the work with the wallet through `ethers` is not yet available. 

### Steps To Reproduce

1. Start new project
2. Install `view@0.1.10`
3. Try to `import { getAccount } from 'viem/ethers'`
4. Get error: Cannot find module 'viem/ethers' or its corresponding type declarations.

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/edit/viem-getting-started-qvtbmg?file=index.ts

**Comment by jxom** [comment]
Should be good in `0.1.12`!
