### ISSUE TITLE
bug: concat not exported

### ISSUE THREAD

**Issue by holic** [wagmi-dev/viem#193]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.1.12

### Current Behavior

<img width="541" alt="image" src="https://user-images.githubusercontent.com/508855/224520513-fab37a1c-e032-41bc-a78d-8cb562b96cd9.png">

### Expected Behavior

<img width="922" alt="image" src="https://user-images.githubusercontent.com/508855/224520524-30df2f95-1673-4e38-bef6-1114aa808a12.png">

https://viem.sh/docs/utilities/concat.html

(It'd be nice if all concat modules were exported.)

**Comment by jxom** [comment]
my bad, fixed!
