### ISSUE TITLE
client.multicall({ allowFailure: false }) returns a different type than the stated return type

### ISSUE THREAD

**Issue by kyscott18** [wagmi-dev/viem#210]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.1.15

### Current Behavior

`client.multicall({ allowFailure: false })` returns type `[{ result: __type__, status: "success" }]`

### Expected Behavior

`client.multicall({ allowFailure: false })` has a defined return type of` [ __type__ ] `

### Steps To Reproduce

`client.multicall({ allowFailure: false })`

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://github.com/kyscott18/numoen-example-arbitrage/blob/master/src/numoen.ts#L10-L40

**Comment by jxom** [comment]
I just pulled your repo and the types look expected to me? When `allowFailure` is falsy, the shape is `[<type_1>, <type_2>, <type_n>]`. 

<img width="745" alt="Screenshot 2023-03-15 at 7 53 35 am" src="https://user-images.githubusercontent.com/7336481/225134373-1d87a001-4f9c-471c-ab8f-d67cc4112c84.png">

**Comment by jxom** [comment]
Ah, wait, just realised the runtime returns the other type, will fix!

**Comment by oxSaturn** [comment]
@jxom reckon the document needs an update as well, currently it doesn't mention that `allowFailure: false` would result a different return type.
