### ISSUE TITLE
'getAccount' with ethers' 'Wallet': 'signTypedData' missing in type 'Wallet'

### ISSUE THREAD

**Issue by mozrt2** [wagmi-dev/viem#212]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.1.16

### Current Behavior

When trying to follow [this ethers -> viem migration example](https://viem.sh/docs/ethers-migration.html#viem-11), I run into a type error for getAccount:

> Argument of type 'Wallet' is not assignable to parameter of type 'EthersWallet'.
> Property 'signTypedData' is missing in type 'Wallet' but required in type 'EthersWallet'.

### Expected Behavior

'EthersWallet' should fit the properties of type 'Wallet'.

### Steps To Reproduce

```import { createPublicClient, http } from 'viem'
import { getAccount } from 'viem/ethers';
import { goerli } from 'viem/chains'
import { Wallet } from 'ethers';
import "dotenv/config"

const client = createPublicClient({
  chain: goerli,
  transport: http('"https://eth-goerli.g.alchemy.com/v2/[API_KEY]"')
})

const account = getAccount(new Wallet(process.env.KEY as string))```

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

_No response_

### Anything else?

_No response_

**Comment by jxom** [comment]
Fixed on `0.1.17`.
