### ISSUE TITLE
viem unable to properly process Celo precompiles

### ISSUE THREAD

**Issue by kyscott18** [wagmi-dev/viem#222]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.1.15

### Current Behavior

When sending transactions that use Celo precompiles, Celo Native Token is an example of this, viem transaction simulation simulates a revert for valid transaction. Foundry has the same issue and its easier to replicate there. Not saying this is something viem needs to fix but more warnings or a better error message would be helpful because its pretty difficult to tell that this is what is actually happening at first glance.

### Expected Behavior

Ethers is able to handle this somehow.

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://github.com/kyscott18/celo-foundry-bug-example/blob/master/test/CeloTest.sol

**Comment by jxom** [comment]
Can you provide a minimal reproduction in viem?

**Comment by jxom** [comment]
I was able to successfully transfer tokens via the precompile: https://stackblitz.com/edit/github-yrokfn?file=index.tsx,package.json

Is this what you were trying to do? 

Going to close this for now, but if this is something that needs a further look, I'll re-open!
