### ISSUE TITLE
bug: window.ethereum not assignable to type EthereumProvider

### ISSUE THREAD

**Issue by Loris-EPFL** [wagmi-dev/viem#312]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.2.7

### Current Behavior

When using viem with react and typescript, i get a type error when creating a WalletClient with `const walletClient = createWalletClient({
  chain: mainnet,
  transport: custom(window.ethereum)
})`

> Argument of type 'WindowProvider | undefined' is not assignable to parameter of type 'EthereumProvider'.`

This might be related to an issue i saw here [https://github.com/wagmi-dev/viem/issues/244](url) about type inference

### Expected Behavior

No type error when creating a Wallet Client

**Comment by tmm** [comment]
Where does the `WindowProvider` type come from? Are you using another library that sets this or declaring yourself?

**Comment by fubhy** [comment]
Hi. That's not a bug. `window.ethereum` is not guaranteed to be set. So the type issue is legitimate. You can't pass something that's possibly `undefined` to a parameter that expects `EthereumProvider`.

```typescript
if (window.ethereum !== undefined) {
  const walletClient = createWalletClient({ chain: mainnet, transport: custom(window.ethereum) })
}
```
