### ISSUE TITLE
bug: wrong type definition for multicall status

### ISSUE THREAD

**Issue by Gilgames000** [wagmi-dev/viem#407]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.3.7

### Current Behavior

The type of the multicall result status is defined as [`'success' | 'error'`](https://github.com/wagmi-dev/viem/blob/f6892ebc004e70b838e08eef1139e850111c09b9/src/types/multicall.ts#L62).

### Expected Behavior

The type of the multicall result status should be defined as [`'success' | 'failure'`](https://github.com/wagmi-dev/viem/blob/f6892ebc004e70b838e08eef1139e850111c09b9/src/actions/public/multicall.ts#L170).

**Comment by jxom** [comment]
fixed ty
