### ISSUE TITLE
bug: wss transport does not work

### ISSUE THREAD

**Issue by YasuBlockchain** [wagmi-dev/viem#408]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.3.7

### Current Behavior

Does not retrieve the blocknumber using wss protocol

### Expected Behavior

Excepts to retrieve the blocknumber using the wss protocol

### Steps To Reproduce

Try using the http protocol with achemy or infura apikey ==> It does work
Try using the wss protocol with achemy or infura apikey ==> It does NOT work

Can you help me?
![Capture d’écran 2023-04-23 à 18 24 18](https://user-images.githubusercontent.com/110788297/233851889-e673f60e-7ba9-4c4a-a4eb-28a884285115.png)

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/edit/viem-getting-started-on7saa?file=index.ts

**Comment by jxom** [comment]
Vite is cursed. Fixed at https://github.com/wagmi-dev/viem/commit/8371ad9cb6987b5876a679ba502a80573c92ec64. Thanks!
