### ISSUE TITLE
bug: isomorphic-ws import causing build failure

### ISSUE THREAD

**Issue by codyarose** [wagmi-dev/viem#457]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.3.17

### Current Behavior

I'm building a node server that uses viem with the websocket transport. It works fine in dev, of course, but it fails every time when trying to build.

build error
```zsh
../../node_modules/.pnpm/viem@0.3.17_typescript@4.9.4_zod@3.20.2/node_modules/viem/dist/types/clients/transports/webSocket.d.ts(2,15): error TS2616: 'WebSocket' can only be imported by using 'import WebSocket = require("isomorphic-ws")' or a default import.
../../node_modules/.pnpm/viem@0.3.17_typescript@4.9.4_zod@3.20.2/node_modules/viem/dist/types/utils/rpc.d.ts(2,15): error TS2616: 'WebSocket' can only be imported by using 'import WebSocket = require("isomorphic-ws")' or a default import.
```

start error
```sh
../../node_modules/.pnpm/viem@0.3.17_typescript@4.9.4_zod@3.20.2/node_modules/viem/dist/types/clients/transports/webSocket.d.ts:2:15 - error TS2616: 'WebSocket' can only be imported by using 'import WebSocket = require("isomorphic-ws")' or a default import.

2 import type { WebSocket } from 'isomorphic-ws';
                ~~~~~~~~~

../../node_modules/.pnpm/viem@0.3.17_typescript@4.9.4_zod@3.20.2/node_modules/viem/dist/types/utils/rpc.d.ts:2:15 - error TS2616: 'WebSocket' can only be imported by using 'import WebSocket = require("isomorphic-ws")' or a default import.

2 import type { WebSocket } from 'isomorphic-ws';
                ~~~~~~~~~


Found 2 errors in 2 files.

Errors  Files
     1  ../../node_modules/.pnpm/viem@0.3.17_typescript@4.9.4_zod@3.20.2/node_modules/viem/dist/types/clients/transports/webSocket.d.ts:2
     1  ../../node_modules/.pnpm/viem@0.3.17_typescript@4.9.4_zod@3.20.2/node_modules/viem/dist/types/utils/rpc.d.ts:2
```

client setup
```ts
import { createPublicClient, webSocket } from 'viem';
import { mainnet } from 'viem/chains';

const transport = webSocket(process.env.WS_ALCHEMY_MAINNET_URL);

const client = createPublicClient({
  chain: mainnet,
  transport,
});

export default client;
```

**Comment by codyarose** [comment]
Manually changing the WebSocket imports in the files mentioned in the errors
```
node_modules/viem/dist/types/clients/transports/webSocket.d.ts
node_modules/viem/dist/types/utils/rpc.d.ts
```
from
```ts
import type { WebSocket } from 'isomorphic-ws';
```
to
```ts
import WebSocket = require('isomorphic-ws');
```
fixes the errors and allows me to successfully build and run the built files

**Comment by jxom** [comment]
Interesting. Your Node environment shouldn't be importing type definition files. Mind posting a minimal reproduction so I can take a look? Will re-open when provided!

**Comment by codyarose** [comment]
@jxom Unfortunately I don't have the bandwidth to put together a minimum repro right now, especially since I've resolved the issue with pnpm patch. The node env isn't importing them, but they're being checked when tsc runs because skipLibCheck is not enabled.

It's interesting though that the type defs include a named import from isomorphic-ws when it appears that that library uses a default export.

**Comment by nissoh** [comment]
> Interesting. Your Node environment shouldn't be importing type definition files. Mind posting a minimal reproduction so I can take a look? Will re-open when provided!

hey jxom, having the same issue with developing a standalone ESM package

check https://github.com/GMX-Blueberry-Club/Puppet/tree/main/middleware

clone the repo, `pnpm i` and run the build in `/middleware` workspace
