### ISSUE TITLE
bug: React Native imports viem but not viem/chains

### ISSUE THREAD

**Issue by dcposch** [wagmi-dev/viem#459]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.3.17

### Current Behavior

Odd import issue. `tsc` succeeds.

Then, in on-device bundling, the React Native Metro bundler fails to import `viem/chains`:

```
Unable to resolve "viem/chains" from "src/logic/chain.ts"
```

**However, it succeeds as importing `"viem"`.** I can work around the issue by simply copying the chain definitions I need into my own constants file. 

--

I noticed that `viem` has a pretty fancy `package.json`--particularly everything under the `exports` key. I suspect there's some subtle incompatibility between that and Metro.

### Expected Behavior

If a bundler is correctly to configured to `import ... from "viem"`, then `import ... from "viem/chains"` should just work.

### Steps To Reproduce

Create the hello world Expo project

```
npx create-expo-app repro
cd repro
npx expo install viem
```

Then, edit `App.js` adding the following.

```
import { createPublicClient, http } from "viem";
import { mainnet } from "viem/chains";

createPublicClient({ chain: mainnet, transport: http() });
```

Finally, 

```
npm start
``` 
& tap i to start in the iOS simulator.

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

**https://github.com/dcposch/repro-459**

**Comment by dcposch** [comment]
<img width="313" alt="image" src="https://user-images.githubusercontent.com/169280/236782825-8c65de8b-e904-4099-968d-7c0a96c18425.png">

**Comment by jxom** [comment]
You will need to enable the `unstable_enablePackageExports` flag in the Metro bundler: https://github.com/facebook/metro/blob/c11f75acfc02cd773920c489cd7445ce91c9bae7/docs/PackageExports.md#configuration-options
