### ISSUE TITLE
bug: simultaneous `waitForTransactionReceipt` calls never resolve

### ISSUE THREAD

**Issue by holic** [wagmi-dev/viem#467]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.3.18

### Current Behavior

I am working on some [developer tools for MUD](https://github.com/latticexyz/mud/pull/689). One of those is a transaction log, where our MUD internals emit transaction hashes any time the burner wallet kicks off a transaction, which the dev tools listen for and display in the UI.

The dev tools use that list of hashes to make a series of RPC calls with viem (`getTransaction`, `waitForTransactionReceipt` and `simulateContract`) for each transaction (but cached globally, so only one promise for each method call for each hash is made), and displayed as data comes in from the resolving promises.

When I kick off many transactions simultaneously using anvil, the promises from `waitForTransactionReceipt` never seem to resolve.

### Expected Behavior

I would expect these to resolve. I can get the behavior I'm looking for by replacing `waitForTransactionReceipt` with the following code, but it doesn't take into account 1) timeouts and 2) never-confirmed transactions due to replacements:

```ts
new Promise((resolve, reject) => {
  const unwatch = publicClient.watchBlockNumber({
    onBlockNumber: async (_blockNumber) => {
      try {
        const receipt = await publicClient.getTransactionReceipt({ hash });
        unwatch();
        resolve(receipt);
      } catch (error) {
        if (error instanceof TransactionNotFoundError || error instanceof TransactionReceiptNotFoundError) {
          // allow it to retry on the next block
          return;
        }
        unwatch();
        reject(error);
      }
    },
  });
})
```

### Steps To Reproduce

I haven't been able to spin up a minimal repro yet, aside from the PR linked above. I intended to write some failing viem tests, but couldn't get viem installed and running locally (stuck on `wagmi generate`).

### Anything else?

Worth noting that our local + testnet block times are set to 1s!

**Comment by jxom** [comment]
What chain are you testing this against? Anvil or Mainnet?

**Comment by holic** [comment]
> What chain are you testing this against? Anvil or Mainnet?

This is via anvil

**Comment by 0xlxy** [comment]
encountered the same issue on `goerli`

**Comment by atanasbozhkov** [comment]
I'm experiencing the same issue when using wagmi. Multiple simultaneous transactions on ethereum/polygon and arbitrum never resolve except the first one.

**Comment by Songkeys** [comment]
Probably a load-balanced json rpc server issue. I got the same behaviour https://github.com/Crossbell-Box/crossbell.js/issues/40 . You can retry it when rejected.

**Comment by iamkaterpillar** [comment]
We're still experiencing this issue where multiple simultaneous transactions on ethereum/polygon and arbitrum never resolve except the first one.

**Comment by llllvvuu** [comment]
This appears to a regression from `wagmi 0.x` for us. In my case I was using both `useWaitForTransaction` and `waitForTransaction` on the same txHash for handlers tied to the component lifecycle and handlers not tied to the component lifecycle. The workaround was refactoring to have only one or the other.

**Comment by jxom** [comment]
Do you have a minimal repro so we can investigate further?

**Comment by jxom** [comment]
This issue has been closed due to a lack of a minimal reproduction. If this is still an issue, please open a new issue with a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) via https://new.viem.sh or a minimal GitHub repository.

**Comment by llllvvuu** [comment]
FWIW I wasn't able to reproduce it anymore.

@holic @iamkaterpillar you're welcome to try to extend my examples to see if the issue still happens:
https://github.com/llllvvuu/viem-467-repro-attempt
https://github.com/llllvvuu/viem-467-repro-rainbowkit

**Comment by llllvvuu** [comment]
> FWIW I wasn't able to reproduce it anymore.
> 
> @holic @iamkaterpillar you're welcome to try to extend my examples to see if the issue still happens: https://github.com/llllvvuu/viem-467-repro-attempt https://github.com/llllvvuu/viem-467-repro-rainbowkit

Oh ho ho, I spoke too soon. The first example (`viem-467-repro-attempt`) does actually reproduce the issue. It should print 3 receipts but it only prints 2 (`receipt2` hangs forever). @jxom re-openable?

**Comment by llllvvuu** [comment]
> FWIW I wasn't able to reproduce it anymore.
> 
> @holic @iamkaterpillar you're welcome to try to extend my examples to see if the issue still happens: https://github.com/llllvvuu/viem-467-repro-attempt https://github.com/llllvvuu/viem-467-repro-rainbowkit

^Looks like I spoke too soon. The first example does actually reproduce the issue. It should print out 3 txReceipts, but only prints out 2. `receipt2` gets stuck, and the `console.log` shows "waiting..." but not "done". The interesting thing about this code snippet:

```
  useEffect(() => {
    ;(async () => {
      if (hash) {
        setReceipt(await publicClient.waitForTransactionReceipt({ hash }))
        setReceipt3(await publicClient.waitForTransactionReceipt({ hash }))
      }
    })()
  }, [hash])

  useEffect(() => {
    ;(async () => {
      if (hash2) {
        console.log("waiting...")
        const _receipt =
          await publicClient.waitForTransactionReceipt({ hash: hash2 })
        console.log(_receipt)
        console.log("done")
        setReceipt2(_receipt)
      }
    })()
  }, [hash2])
```

is that:

* the issue goes away if `setReceipt3` line is removed
* the issue goes away if `setReceipt3` line is moved to its own `useEffect`

so the issue seems tightly coupled to async execution order.

@jxom re-openable?

**Comment by jxom** [comment]
@llllvvuu – Thanks for the reproduction. Managed to find the issue, and should be fixed in `1.2.9`.

**Comment by atanasbozhkov** [comment]
Hey - I'm once again experiencing this with v1.7.0 (pulled in from wagmi 1.3.10)

**Comment by tmm** [comment]
@atanasbozhkov can you open a new issue with reproduction? hard to track comments on older issues.

**Comment by atanasbozhkov** [comment]
@tmm - I've adapted the previous repro and opened a new issue #1082
