### ISSUE TITLE
bug: React Native TextEncoder Support

### ISSUE THREAD

**Issue by benschac** [wagmi-dev/viem#479]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.3.21

### Current Behavior

React Native doesn't have a native `TextEncoder` Constructor and will throw / crash the application

### Expected Behavior

viem should "just work"

### Steps To Reproduce

- create react-native / expo project: https://docs.expo.dev/get-started/create-a-project/
-  `import { isAddress } from 'viem'` in a ts/js file

### Anything else?

I ended up polyfilling the `TextEncoder` object. Not sure if it's worth polyfilling it in viem directly? Maybe add some documentation with instructions on adding a polyfill to your project?

https://github.com/anonyco/FastestSmallestTextEncoderDecoder was the polyfill I ended up using.

**Comment by benschac** [comment]
Happy to add some documentation / or give pollyfilling the viem a try if either seem like a good path forward.

**Comment by jxom** [comment]
I think adding docs on how to polyfill may be better! Feel free to open a PR if you want.

**Comment by benschac** [comment]
Will do, Ty for the quick reply

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
