### ISSUE TITLE
bug: transactionIndex from getFilterLog is statically typed as number but receives BigInt at runtime

### ISSUE THREAD

**Issue by deodad** [wagmi-dev/viem#499]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.3.24

### Current Behavior

I am querying logs using `createContractEventFilter` and `getFilterLogs`. The `Log` type has a value of `number` for the `TIndex` generic, but at runtime I'm seeing a `bigint`.

### Expected Behavior

`getFilterLogs` return type has `TIndex` of `bigint` for the `Log` type.

**Comment by Volchunovich** [comment]
Can I take it ?

**Comment by jxom** [comment]
Go for it.

**Comment by Volchunovich** [comment]
@jxom could you help me? I want to try to push my changes into my branch but got failed with denied permissions. What should I do to push and create PR?

**Comment by jxom** [comment]
Fixed on #576
