### ISSUE TITLE
bug: `http` does not have `url` in the `config` object parameter

### ISSUE THREAD

**Issue by o-az** [wagmi-dev/viem#512]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.3.26

### Current Behavior

In the docs, [the following is shown](https://viem.sh/docs/clients/transports/fallback.html#usage):

```ts
const alchemy = http({ 
  url: 'https://eth-mainnet.g.alchemy.com/v2/...' 
})
```

However, when I try it typescript is not happy. It doesn't look like `url` is a field in the parameter `config: HttpTransportConfig` 

https://github.com/wagmi-dev/viem/blob/43f1fcf08acb568e2105501e3772752f66986cb2/src/clients/transports/http.ts#L10-L26

### Expected Behavior

Either `url` should be a field in `config` object parameter or docs should be updated.

### Steps To Reproduce

In the public example https://stackblitz.com/github/wagmi-dev/viem/tree/main/examples/clients/public-client?file=index.ts

try replacing any of the `http()` with `http({ url: '' })` and see the error.

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/github/wagmi-dev/viem/tree/main/examples/clients/public-client?file=index.ts

**Comment by jxom** [comment]
updated docs
