### ISSUE TITLE
Can't resolve 'viem/chains'  for module wagmi

### ISSUE THREAD

**Issue by envoyD** [wagmi-dev/viem#523]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

    "viem": "^0.3.28",   "wagmi": "^1.0.5",

### Current Behavior

gives error while importing wagmi:-
./node_modules/@wagmi/connectors/dist/chunk-QYMCVNHT.js
Module not found: Can't resolve 'viem/chains' in '/node_modules/@wagmi/connectors/dist'

### Expected Behavior

should not give error on importing 'wagmi'

### Steps To Reproduce

install wagmi:''^0.3.28" and viem:"^1.0.5",
try to import them in your app

**Comment by ValiKTHD** [comment]
I got the same issue, was just about to report now.

**Comment by jxom** [comment]
What bundler are you using? The consuming bundler should support `package.json#exports` which is most modern bundlers (Webpack 5, Vite, esbuild, swc, rollup, etc).

**Comment by ValiKTHD** [comment]
I'm using react-scripts 4.0.3 which I see that it uses Webpack 4.44.3

**Comment by jxom** [comment]
If you update react-scripts (webpack 5), then it should be fixed!
