### ISSUE TITLE
ChainDoesNotSupportContract: Chain "Arbitrum One" does not support contract "ensUniversalResolver".

### ISSUE THREAD

**Issue by huangzh278** [wagmi-dev/viem#525]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

viem@0.3.28

### Current Behavior

next-dev.js:25 ChainDoesNotSupportContract: Chain "Arbitrum One" does not support contract "ensUniversalResolver".

This could be due to any of the following:
- The chain does not have the contract "ensUniversalResolver" configured.

Version: viem@0.3.28

**Comment by jxom** [comment]
I don’t believe Arb One has a ENS Universal Resolver deployed, so this is expected. Is this causing you some sort of blocking issue?

**Comment by 0xGuybrush** [comment]
> I don’t believe Arb One has a ENS Universal Resolver deployed, so this is expected. Is this causing you some sort of blocking issue?

We're hitting the same when testing against Foundry locally. 

Everything is still working OK, so not a blocker, but if there was a way to silence the warning it would be great though! It adds a bit of noise to the console when trying to debug issues (especially with hot reloading).
