### ISSUE TITLE
Unable to run a build of our app.

### ISSUE THREAD

**Issue by hickscorp** [wagmi-dev/viem#543]
### Package Version

Latest and viem@0.3.31

### Current Behavior

We are able to run our application in development mode, and everything seems to work OK.
It took us a couple of days to migrate it from Wagmi `0.12` to `1.0`, and also getting rid of `ethers` in favor of `viem`.

However, once built and deployed it crashes on a contract `read` which should in fact succeed. The error is:

```json
{
  "url": "https://fast.dev.consilience.vc/",
  "error": {
    "details": "Cannot convert a BigInt value to a number",
    "docsPath": "/docs/contract/readContract",
    "metaMessages": [
      "Raw Call Arguments:",
      "  to:    0x2F03add7AAbA219405ea7Dc94e4345D99D469FbA\n  data:  0xa230c524000000000000000000000000d786f085c53e1674affcee9252bb3e7044698267",
      " ",
      "Contract Call:",
      "  address:   0x2F03add7AAbA219405ea7Dc94e4345D99D469FbA\n  function:  isMember(address who)\n  args:              (0xd786f085c53E1674afFcEe9252Bb3E7044698267)"
    ],
    "shortMessage": "An unknown error occurred while executing the contract function \"isMember\".",
    "name": "ContractFunctionExecutionError",
    "version": "viem@0.3.31",
    "message": "An unknown error occurred while executing the contract function \"isMember\".\n\nRaw Call Arguments:\n  to:    0x2F03add7AAbA219405ea7Dc94e4345D99D469FbA\n  data:  0xa230c524000000000000000000000000d786f085c53e1674affcee9252bb3e7044698267\n \nContract Call:\n  address:   0x2F03add7AAbA219405ea7Dc94e4345D99D469FbA\n  function:  isMember(address who)\n  args:              (0xd786f085c53E1674afFcEe9252Bb3E7044698267)\n\nDocs: https://viem.sh/docs/contract/readContract.html\nDetails: Cannot convert a BigInt value to a number\nVersion: viem@0.3.31",
    "cause": {
      "details": "Cannot convert a BigInt value to a number",
      "metaMessages": [
        "Raw Call Arguments:",
        "  to:    0x2F03add7AAbA219405ea7Dc94e4345D99D469FbA\n  data:  0xa230c524000000000000000000000000d786f085c53e1674affcee9252bb3e7044698267"
      ],
      "name": "CallExecutionError",
      "version": "viem@0.3.31",
      "message": "An error occurred.\n\nRaw Call Arguments:\n  to:    0x2F03add7AAbA219405ea7Dc94e4345D99D469FbA\n  data:  0xa230c524000000000000000000000000d786f085c53e1674affcee9252bb3e7044698267\n\nDetails: Cannot convert a BigInt value to a number\nVersion: viem@0.3.31",
      "cause": {}
    },
    "abi": [...],
    "args": ["0xd786f085c53E1674afFcEe9252Bb3E7044698267"],
    "contractAddress": "0x2F03add7AAbA219405ea7Dc94e4345D99D469FbA",
    "functionName": "isMember"
  }
}
```

It seems that a `bigint` cannot be converted to a `number` - but it's odd - the `isMember` function doesn't involve a `number` conversion.

The main issue here is that there's no stack or nothing for us to look for. Before we go bug hunting - is there anything in particular that we should be careful of when building our app for production?

The function in question is quite simple, something like this:

```ts
  useEffect(() => {
    // Mark current state as loading.
    setState({ status: Status.Unready, reason: UnreadyReason.Loading });
    // Instantiate contracts.
    const issuer = getContract({ abi: issuerABI, address: issuerAddress, walletClient });
    const marketplace = getContract({ abi: marketplaceABI, address: marketplaceAddress, walletClient });

    // Query memberships.
    Promise.all([issuer.read.isMember([signerAddress]), marketplace.read.isMember([signerAddress])])
      .then(([isIssuerMember, isMarketplaceMember]) =>
        setState({
          status: Status.Ready,
          issuer,
          marketplace,
          isMarketplaceMember,
          isIssuerMember,
        }),
      )
      .catch((err) => {
        handleError("Loading Top Contracts", err);
        setState({ status: Status.Unready, reason: UnreadyReason.Error });
      });
  }, [marketplaceAddress, issuerAddress, signerAddress, handleError, walletClient]);
```

The exception is thrown by `handleError("Loading Top Contracts", err);`.
In staging, we are using the exact same wallet configuration as in development. The chain is identical too (Mumbai).

EDIT: I've installed a local server and tried to run the build locally on my computer - same error. It really seems that something breaks during the build process.

**Comment by jxom** [comment]
Can you please provide a minimal reproducible example via a separate repository so we can look closer? We can’t really debug this without knowing the contract address/abi and the bundler you are using.

**Comment by hammadtariq98** [comment]
I am facing same issue 

following is my package.json file

> 
> "dependencies": {
>         "@chakra-ui/icons": "^2.0.19",
>         "@chakra-ui/react": "^2.6.0",
>         "@emotion/react": "^11.10.8",
>         "@emotion/styled": "^11.10.8",
>         "@tanstack/react-query": "^4.29.5",
>         "@testing-library/jest-dom": "^5.16.5",
>         "@testing-library/react": "^13.4.0",
>         "@testing-library/user-event": "^13.5.0",
>         "@types/jest": "^27.5.2",
>         "@types/node": "^16.18.25",
>         "@types/react": "^18.2.0",
>         "@types/react-dom": "^18.2.1",
>         "@uniswap/widgets": "^2.51.2",
>         "@web3modal/ethereum": "^2.4.1",
>         "@web3modal/react": "^2.4.1",
>         "framer-motion": "^10.12.4",
>         "react": "^18.2.0",
>         "react-countdown": "^2.3.5",
>         "react-dom": "^18.2.0",
>         "react-redux": "^8.0.5",
>         "react-router": "^6.10.0",
>         "react-router-dom": "^6.10.0",
>         "react-scripts": "5.0.1",
>         "typescript": "^4.9.5",
>         "viem": "^0.3.19",
>         "wagmi": "^1.0.1",
>         "web-vitals": "^2.1.4"
>     },

    and  this code is working fine on localhost and local ip but on prod same issue as above mentioned in thread  

    `   const { data: totalUsers } = useContractRead({
        address: ADDRESS,
        abi: ABI,
        functionName: 'totalUsers',
        enabled: false,
    })`

**Comment by hickscorp** [comment]
Unfortunatelly, providing a reproducible example wasn't successful.
You can try https://fast.dev.consilience.vc. It's live with the bug.

**Comment by jxom** [comment]
I can try. To assist, can you please provide what bundler you are using?

**Comment by jxom** [comment]
I tried to reproduce this using `react-scripts` (from @hammadtariq98's package.json), but cannot seem to reproduce on a built application: https://viem-eqsrbvjum-jxom.vercel.app/

Repo: https://github.com/jxom/543-repro

Might be best to double check if something is playing up in your environment, or fork my repo/create a repo and try reproduce the problem there so I can debug further.

Going to close for now until a minimal reproduction is provided.

**Comment by jxom** [comment]
Also I noticed that you have not set up a `publicClient` in `getContract`. You will need to do that for `read`s to work.

```diff
- const issuer = getContract({ abi: issuerABI, address: issuerAddress, walletClient });
+ const issuer = getContract({ abi: issuerABI, address: issuerAddress, publicClient, walletClient }); 
```

**Comment by jxom** [comment]
Looks like this might be due to the way create-react-app bundles according to the browserslist. Potential fix here: https://github.com/hirosystems/stacks.js/issues/1096#issuecomment-946350299

**Comment by hickscorp** [comment]
@jxom Thanks a lot for the time spent. Regarding your suggestion to use a `WalletClient` when instantiating contracts, it was the case at the time of the error showing - the version you looked at was an attempt to simplify a reproducible example.

I will have a look at the browserlist now. Thanks again!

**Comment by hickscorp** [comment]
What you suggested @jxom fixed the problem. Thank you very much!

**Comment by hammadtariq98** [comment]
@jxom I  amd reding contract through wagmi not viem

```
import { useContractRead, useAccount, useContractWrite } from 'wagmi'

const { data: totalUsers } = useContractRead({
address: ADDRESS,
abi: ABI,
functionName: 'totalUsers'
})
```
and I am using this example for config from Walletconnect v2.
[web3modal](https://docs.walletconnect.com/2.0/web3modal/react/installation)

**Comment by jxom** [comment]
@hammadtariq98  can you try this please? https://github.com/hirosystems/stacks.js/issues/1096#issuecomment-946350299

**Comment by hammadtariq98** [comment]
Thank you adding 
 ```
   "browserslist": {
        "production": [
            ">0.2%",
           addition:["not ie <= 99",] 
           addition:["not android <= 4.4.4",]
            "not dead",
            "not op_mini all"
        ],
```

**Comment by Solniechniy** [comment]
I also faced with this issue and think that it can be added in documentation somehow or at least some bugfix chapter @jxom
thanks for help, but this issue is also was difficult to find :)

**Comment by rk-spirinova** [comment]
> @jxom Thank you it is working now after updating production in browserslist `package.json`
> 
> ```
> "production": [
>             ">0.2%",
>             "not ie <= 99",
>             "not android <= 4.4.4",
>             "not dead",
>             "not op_mini all"
>         ]
> ```

This is worked. Thanks!
