### ISSUE TITLE
bug: TypeError: Cannot convert a BigInt value to a number at Math.pow ()

### ISSUE THREAD

**Issue by kenmalibu** [wagmi-dev/viem#558]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.3.30

### Current Behavior

Everything works as expected in localhost development.

npm run build

No errors on build.

When running the build version, after connecting wallet, console displays the following error:

w3m-account-context.ts:64 TypeError: Cannot convert a BigInt value to a number
at Math.pow ()
at l (toHex.ts:173:21)
at param (encodeAbiParameters.ts:211:16)
at h (encodeAbiParameters.ts:101:12)
at n.params (encodeAbiParameters.ts:68:25)
at p (encodeAbiParameters.ts:43:26)
at c (encodeFunctionData.ts:58:9)
at readContract.ts:79:20
at d (regeneratorRuntime.js:44:17)
at Generator. (regeneratorRuntime.js:125:22)

All subsequent WAGMI contract calls return a status of failure.

I have only included a fresh version here to make it easier to replicate and report.

I reported this to web3modal who replied:

"I believe this is a known issue in wagmi -> viem, but best ask on their channels to verify, nothing within web3modal scope that we can do here I'm afraid."

### Expected Behavior

I expected the application I had working in testing would work in the same way in the production build. 

The BigInt error seems to effect every WAGMI contract call.

### Steps To Reproduce

npx create-react-app my-app

npm install @web3modal/ethereum @web3modal/react wagmi viem

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://github.com/kenmalibu/ReactWeb3Modal

### Anything else?

Demo: https://webgl.alphabettydoodles.io

**Comment by jxom** [comment]
The recommended solution would be to modify the browserslist to filter out very old browsers like IE and ancient Android browsers: https://github.com/hirosystems/stacks.js/issues/1096#issuecomment-946350299
