### ISSUE TITLE
Cannot convert a BigInt value to a number error after building prod env

### ISSUE THREAD

**Issue by Stenor5** [wagmi-dev/viem#564]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.3.35

### Current Behavior

``` js
      try {
        const { hash } = await writeContract({
          ...accountManagerContractConfig,
          functionName: "load",
          args: [asset, ethAmount, encodedParams],
          value: parseEther("0.1"),
        });
        await waitForTransaction({ hash });
      } catch (error) {
        console.error(error);
      }
     
```
This code is working on dev env (React) but after building I have below errors.
```shell
TypeError: Cannot convert a BigInt value to a number
    at Math.pow (<anonymous>)
    at l (toHex.ts:173:21)
    at encodeAbiParameters.ts:234:14
    at h (encodeAbiParameters.ts:98:12)
    at param (encodeAbiParameters.ts:272:27)
    at h (encodeAbiParameters.ts:86:12)
    at n.params (encodeAbiParameters.ts:68:25)
    at p (encodeAbiParameters.ts:43:26)
    at c (encodeFunctionData.ts:58:9)
    at simulateContract.ts:117:20
```

Please help me if someone has any idea.

**Comment by Volchunovich** [comment]
@Stenor5 how are you building your app? What do you use?

**Comment by Stenor5** [comment]
@Volchunovich I am using `react-app-rewired build`.

**Comment by Volchunovich** [comment]
Hmm, can you reproduce your problem in stackblitz, codesandbox or something else?

**Comment by Stenor5** [comment]
> to use BigInt properly, your "target" should be "es2020" minimum.

Yes, I am using `es2021`

**Comment by tmm** [comment]
@Stenor5 without a reproducible example, we end up spending a lot of time trying to get to a place where we can help you out. In order for us to help you, you need to help us.

**Comment by BrycenG007** [comment]
I tried to reproduce but there is no latest version of wagmi and viem on sandbox.
How can I do that?

**Comment by Stenor5** [comment]
> 
@tmm 
I tried to reproduce but there is no latest version of wagmi and viem on sandbox.
How can I do that?

**Comment by Volchunovich** [comment]
@Stenor5 press "update" button on the right of package, to get latest version

**Comment by jxom** [comment]
Solution: https://github.com/hirosystems/stacks.js/issues/1096#issuecomment-946350299

**Comment by Stenor5** [comment]
> Solution: [hirosystems/stacks.js#1096 (comment)](https://github.com/hirosystems/stacks.js/issues/1096#issuecomment-946350299)

It definitely works. My sincere thanks go out to you for your kind support. 😊

**Comment by babasutra** [comment]
I had the same issue that `MetaMaskConnector` and `InjectedConnector` return `{type: "BigNumber", hex: "0x..."}` rather than a `BigInt` on a `useContractRead` call to a balanceOf call.  It worked correctly with `WalletConnectConnector`. 

The culprit seemed to be `eth-testing` in my devDependencies. After removing it, it worked again.
