### ISSUE TITLE
bug: `waitForTransactionReceipt`'s onReplaced callback never gets called when speeding up a transaction

### ISSUE THREAD

**Issue by ted-palmer** [wagmi-dev/viem#569]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.3.35

### Current Behavior

When speeding up a transaction, `waitForTransactionReceipt`'s onReplaced callback doesn't seem to be getting invoked

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/edit/wagmi-dev-viem-mcd5ep?file=index.tsx

### Anything else?

Have only tested this on goerli thus far.

Maybe worth noting this is the last blocker from us switching to Viem on reservoir-kit: [https://github.com/reservoirprotocol/reservoir-kit/pull/248](https://github.com/reservoirprotocol/reservoir-kit/pull/248) :)

**Comment by jxom** [comment]
It seems to invoke for me. Initially, I set my `maxFeePerGas` and `maxPriorityFeePerGas` to `0.01` and `0.02`, then override it with the market fee.

<img width="1225" alt="Screenshot 2023-05-24 at 9 00 06 am" src="https://github.com/wagmi-dev/viem/assets/7336481/d515f931-f4d0-47e8-ae72-17075c8fcd03">

Would you be able to provide the steps to reproduce yours?

Will re-open when replied with a repro!
