### ISSUE TITLE
bug:  invalid BigNumber value "undefined" with gnosis safe app

### ISSUE THREAD

**Issue by Max-3-7** [wagmi-dev/viem#579]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.3.36

### Current Behavior

Hey,

I'm having an issue with contract writes that require the value to be `undefined` when connected to a safe. It seems that the safe SDK doesn't like that viem sends undefined as value?

For example, this throws an error and you can't sign it from your safe:
```
const { config } = usePrepareContractWrite({
    abi: erc20ABI,
    address: token,
    args: amount ? [spender, amount] : undefined,
    chainId,
    functionName: 'approve',
})
```
<img width="780" alt="Screenshot 2023-05-25 at 10 17 00" src="https://github.com/wagmi-dev/viem/assets/52084503/f20e18d6-bcbd-4343-8262-f5458bbda616">

But this works:
```
const { config } = usePrepareContractWrite({
    abi: erc20ABI,
    address: token,
    args: amount ? [spender, amount] : undefined,
    chainId,
    functionName: 'approve',
    value: BigInt(0) as any // workaround for safe app
})
```

**Comment by jxom** [comment]
Can you raise this on the Safe SDK repo? That error looks like it’s coming from ethers via Safe SDK. This doesn’t look like to be a viem issue.

**Comment by Max-3-7** [comment]
https://github.com/safe-global/safe-apps-sdk/issues/480#issuecomment-1562565492

That's the reply I got from the safe team

We can of course send 0 instead of undefined for every call that do not use `value` but it's very easy to miss.

**Comment by mmv08** [comment]
sorry lads I misread the issue
