### ISSUE TITLE
bug: Memory leak using watchEvent

### ISSUE THREAD

**Issue by adriencohen** [wagmi-dev/viem#583]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.3.36

### Current Behavior

Using the `watchEvent` function is leading to a growing memory consumption which can only be stopped using the unwatch function returned by `watchEvent`. Memory consumption will then stagnate.

### Expected Behavior

Memory consumption shouln't be evergrowing

### Steps To Reproduce

A quick example running the following code will produce the graph attached after:
```js
import { createPublicClient } from 'viem';
import { mainnet } from 'viem/chains';

const client = createPublicClient({
  chain: mainnet,
  transport: http(),
});

setTimeout(() => {
  const unwatch = client.watchEvent(
    { 
      onLogs: () => {},
    }
  ) 
  console.log('watch')


  setTimeout(() => {
    unwatch()
    console.log('Unwatched')
  }, 300000)

}, 300000)


setInterval(() => {
    console.log('Memory used:', process.memoryUsage().heapUsed / 1024 / 1024);
}, 10000)
```

Using http transport (node v18.12.1):
<img width="584" alt="Capture d’écran 2023-05-25 à 15 22 00" src="https://github.com/wagmi-dev/viem/assets/18153974/ef633a25-b5eb-483d-b740-a215fba51125">

Using ws transport (node v18.12.1):
![Capture d’écran 2023-05-25 à 16 00 47](https://github.com/wagmi-dev/viem/assets/18153974/9e583b39-370b-42e2-aad9-796afe69f68d)

**Comment by fubhy** [comment]
I am seeing similar results in other observers too. So likely not related to `watchEvent` itself but underlying utils.

**Comment by jxom** [comment]
Think I found the culprit. It's in our `withTimeout` util. Need to find out what's causing it though.

**Comment by jxom** [comment]
can you try see if this still happens on `npm i viem@0.0.0-jxom-fix-memory-leak.20230526T074413`?

**Comment by fubhy** [comment]
I don't think it's about cleaning up the AbortController and instead more about cleaning up the lingering `fetch`?

**Comment by jxom** [comment]
Might be an issue with how built-in fetch handles signals: https://github.com/nodejs/node/issues/46525#issuecomment-1419364442

**Comment by fubhy** [comment]
True. But when I run a script with short timeouts the memory still goes up so I suspect there's sth. with fetch?

**Comment by fubhy** [comment]
> Might be an issue with how built-in fetch handles signals: [nodejs/node#46525 (comment)](https://github.com/nodejs/node/issues/46525#issuecomment-1419364442)

Good find. Maybe that's what I'm seeing?

**Comment by fubhy** [comment]
> can you try see if this still happens on `npm i viem@0.0.0-jxom-fix-memory-leak.20230526T074413`?
> 
> the memory leak seems to be gone completely when i remove abort controllers, seems like we need to clean them up: [6be7922#diff-8b7a876b21ac77521fcb4a60160e0baceb18c2415682748d306b0d2fb445c480R35](https://github.com/wagmi-dev/viem/commit/6be792277b28d8c44bd39ebb8c0837cbf2759e22#diff-8b7a876b21ac77521fcb4a60160e0baceb18c2415682748d306b0d2fb445c480R35)

Can confirm that works to also clean up the lingering `fetch`s.

**Comment by jxom** [comment]
Looks like this was an issue with previous versions of Node, and was fixed upstream here: https://github.com/nodejs/undici/pull/2049. 

I tried again on Node v20, and it seems to work fine. Closing for now.
