### ISSUE TITLE
bug: WS Client never closes connections

### ISSUE THREAD

**Issue by hexcowboy** [wagmi-dev/viem#591]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.3.37

### Current Behavior

Creating a websocket client and consuming an action causes client connection to stay open and blocks program termination.

### Expected Behavior

Expected behavior is the client closes connection when it reaches end of scope, or a method is provided to close websocket connections.

### Steps To Reproduce

This code is from the minimal repro below.

```ts
import { createPublicClient, webSocket } from "viem";
import { mainnet } from "viem/chains";

const run = async () => {
  const transport = webSocket(
    "wss://eth-mainnet.g.alchemy.com/v2/your-api-key"
  );

  const client = createPublicClient({
    chain: mainnet,
    transport,
  });

  // never terminates
  const blockNumber = await client.getBlockNumber();
  // comment the above out and it will terminate
};

run();
```

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://github.com/hexcowboy/viem-bug-repro

**Comment by jxom** [comment]
You can close it via `transport.getSocket().close()`. Will add to docs!

**Comment by jxom** [comment]
You can close it via `transport.getSocket().close()`. Will add to docs!
