### ISSUE TITLE
bug: Incorrect encoding of bytes parameter

### ISSUE THREAD

**Issue by ben-razor** [wagmi-dev/viem#622]
### Package Version

0.3.39

### Current Behavior

I have a contract method that mints after checking a signature. The signature parameter is type bytes, it is 65 bytes long.

It works fine with ethers (Taking a hex signature and converting it to bytes):

```js
let signature = 'e37f36636f2e00c0cfc8ab50e1e271357b5ac26ed91ab92ef1e588e3cd7cb60e025859b38931ac30f0951a5c335b69c93f75a075af32714630d034f53141059d1b'

let tx = await contract.mint(cid, Buffer.from(signature, 'hex'), value)

```

In Viem, passing the raw bytes isn't supported so the hex string is passed instead:
```js
let hash = await signer.writeContract({
  address,
  abi,
  functionName: 'mint',
  args: [
    cid,
    signature,
  ],
  account
  value
})
```

Viem uses the encodeBytes function in encodeAbiParameters to encode the signature: 

Is encoded by splitting it into 5 parts and padding them.
```js
[
    "0xe37f36636f2e00c0cfc8ab50e1e2713500000000000000000000000000000000",
    "0x7b5ac26ed91ab92ef1e588e3cd7cb60e00000000000000000000000000000000",
    "0x025859b38931ac30f0951a5c335b69c900000000000000000000000000000000",
    "0x3f75a075af32714630d034f53141059d00000000000000000000000000000000",
    "0x1b00000000000000000000000000000000000000000000000000000000000000"
]
```
These are then concatenated after removing the 0x.

I don't think this is right, the spec has:

Dynamic Encoding:

* The encoded value consists of two parts: the length of the byte array and the actual byte data.
* The length is encoded as a 32-byte (256-bit) value, representing the length of the byte array.
* The actual byte data follows the length encoding.

I don't think the hex signature should be split, padded and concatenated. I'm don't know a lot about abi encoding but I can't see anything in the spec about adding any padding to the byte data. The contract method errors due to this.

If the byte array could be passed directly as with Ethers then that would also solve the problem.

Please can you let me know if it's a mistake on my part? Maybe I'm passing the parameter incorrectly.

**Comment by ben-razor** [comment]
My mistake, the signature just needed '0x' adding to the start.

**Comment by ben-razor** [comment]
Sorry about that, I was hoping I could close it before it was picked up. One of those mistakes that reveals itself moments after clicking the submit ticket button. Thanks for checking it. :-)

**Comment by VladimirMikulic** [comment]
Posting for my future reference ethers bytes encoding to viem:
```js
const abi = [{ name: 'memoir', type: 'bytes' }];
const encoder = new ethers.utils.AbiCoder();

const encodedDataEthers = encoder.encode(abi, [ethers.utils.toUtf8Bytes('test')]);
const encodedDataViem = viem.encodeAbiParameters(abi, [viem.toHex('test')]);

console.log(
  encodedDataEthers, // 0x000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000047465737400000000000000000000000000000000000000000000000000000000
  encodedDataViem, // 0x000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000047465737400000000000000000000000000000000000000000000000000000000
  encodedDataEthers === encodedDataViem // true
);
```
