### ISSUE TITLE
bug: ChainMismatchError when forking a network on anvil

### ISSUE THREAD

**Issue by anhthii** [wagmi-dev/viem#638]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.3.39

### Current Behavior

I encountered this error when running some tests on anvil that forked from Sepolia network 

I declared public client and wallet client as follow in my tests:

```js
    const publicClient = createPublicClient({
      chain: foundry,
      transport: http()
    })

    const walletClient = createWalletClient({
      account,
      chain: foundry,
      transport: http()
    })
    
    const { request } = await publicClient.simulateContract({
      address: WBTC,
      abi:  ABI,
      functionName: 'mint',
      args: [100 * 1e8],
      account
    })
```
This will throw the errror 
```js
ChainMismatchError: The current chain of the wallet (id: 11155111) does not match the target chain for the transaction (id: 31337 – Foundry).
```

The error is resolved after I add `chain` attribute to the `simulateContract` method
```js
const { request } = await publicClient.simulateContract({
      address: WBTC,
      abi:  ABI,
      functionName: 'mint',
      args: [100 * 1e8],
      account,
      chain: sepolia
    })
```
However, I noticed that after I mint the tokens successfully. When i read its balance, it's `0`  this means that the public client is not reading the state of the chain correctly

```shell
cast call 0x765C0c2D27A3EfB4064ed7f2E56e4F7CDDf4202f "balanceOf(address)" 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266 --rpc-url http://127.0.0.1:8545
0x0000000000000000000000000000000000000000000000000000000000000000
```

I think the issue might be caused by these lines of code: 
https://github.com/wagmi-dev/viem/blob/c0e7e922b0c99ef68c3a6db4b0f55d841fc1b950/src/actions/wallet/sendTransaction.ts#L125
 https://github.com/wagmi-dev/viem/blob/c0e7e922b0c99ef68c3a6db4b0f55d841fc1b950/src/actions/public/getChainId.ts#L31
 
 `Viem` is getting chainId from the rpc call instead of getting chainId from the config passed in to `clients`
 Here is the command I issued to check the chainId of the forked local network
 ```shell
 cast chain-id --rpc-url http://127.0.0.1:8545
 
 11155111
 ````

### Expected Behavior

I can `simulateContract` without passing the chain property and it still works

### Steps To Reproduce

Described above

### Anything else?

![image](https://github.com/wagmi-dev/viem/assets/20469909/193e8ead-7c47-449e-b1fc-484ba222d690)

**Comment by jxom** [comment]
You'll need to modify the `foundry` chain to have the chain id for Sepolia.

```ts
export const foundrySepolia = {
  ...foundry,
  id: sepolia.id
} as const
```

**Comment by thi-investax** [comment]
This works. Thanks a lot @jxom !  🙏

**Comment by anhthii** [comment]
This works, Thank you  a lot 🙏

**Comment by jxom** [comment]
woohoo
