### ISSUE TITLE
bug: viem/chains not updated to latest version

### ISSUE THREAD

**Issue by oxSaturn** [wagmi-dev/viem#640]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.3.45

### Current Behavior

I've filed a pr here https://github.com/wagmi-dev/references/pull/310/files to set up multicall3 address for `canto` network. And I saw a new version was published recently.

But I reckon it's not included in the latest viem.

Example:

```
import { canto } from 'viem/chains';
console.log(canto);
```
Outputs:

```
{
  id: 7700,
  name: 'Canto',
  network: 'canto',
  nativeCurrency: { decimals: 18, name: 'Canto', symbol: 'CANTO' },
  rpcUrls: { default: { http: [Array] }, public: { http: [Array] } },
  blockExplorers: {
    default: {
      name: 'Canto EVM Explorer (Blockscout)',
      url: 'https://evm.explorer.canto.io'
    }
  }
}
```

And the types are stale as well:

![](https://github.com/wagmi-dev/viem/assets/126733611/376f3b92-f5f3-47ab-ae62-36b3a35982a2)

### Expected Behavior

```
import { canto } from 'viem/chains';
console.log(canto);
```
Outputs:

```
{
  id: 7700,
  name: 'Canto',
  network: 'canto',
  nativeCurrency: { decimals: 18, name: 'Canto', symbol: 'CANTO' },
  rpcUrls: { default: { http: [Array] }, public: { http: [Array] } },
  blockExplorers: {
    default: {
      name: 'Canto EVM Explorer (Blockscout)',
      url: 'https://evm.explorer.canto.io'
    }
  },
  contracts: {
    multicall3: {
      address: '0xca11bde05977b3631167028862be2a173976ca11',
      blockCreated: 2905789,
    },
  }
}
```

### Steps To Reproduce

See https://stackblitz.com/edit/stackblitz-starters-7qwrvq

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/edit/stackblitz-starters-7qwrvq

### Anything else?

Note that I'm not using wagmi in this case.

And I see viem has an old `"@wagmi/chains": "0.3.1",` here https://github.com/wagmi-dev/viem/blob/main/package.json#L155, could it be the problem?

**Comment by jxom** [comment]
Fixed!
