### ISSUE TITLE
bug: `prepareWriteContract` throws 'The contract function "approve" returned no data ("0x")' error for USDT token

### ISSUE THREAD

**Issue by lykalabrada** [wagmi-dev/viem#663]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.1.0

### Current Behavior

Using wagmi hook:
```
usePrepareContractWrite({
    address: "0xdAC17F958D2ee523a2206206994597C13D831ec7",
    functionName: "approve",
    args: ["0x3......", 1000000000000000],
  });
```
throws an error:
![image](https://github.com/wagmi-dev/viem/assets/17063281/af858797-12fd-4b87-89bd-f8dc828b1742)

### Expected Behavior

[USDT](https://etherscan.io/address/0xdAC17F958D2ee523a2206206994597C13D831ec7#code:~:text=Security%20Audit%20Report-,Contract%20ABI,-Export%20ABI) `approve` function doesn’t comply with the ERC20 standard, it doesn't have a return value.
I understand that `AbiDecodingZeroDataError` error has been added, but the `approve` function should be an exemption as this is supported by ethers (supported on `wagmi@0.x.x`)

### Anything else?
USDT ABI for `approve` function:
<img width="286" alt="image" src="https://github.com/wagmi-dev/viem/assets/17063281/5c0b5f7c-6238-4d36-9dc9-89b0855d0169">

**Comment by jxom** [comment]
I can seem to reproduce an `"approve"` simulation on my end: https://stackblitz.com/edit/viem-getting-started-s9pvkg?file=index.ts

Not sure if we should return nullish for zero data responses for ABIs in which we expect output(s). That behaviour seems a bit unpredictable to me, and we will be sacrificing type safety too by allowing nullish responses.

It might be best to modify the ABI for these edge cases on your end?

**Comment by lykalabrada** [comment]
Thanks @jxom! You were correct. We had been using the `erc20ABI` from wagmi, and modifying the ABI as you shared resolved the issue. It's working now 👍

**Comment by prometixX** [comment]
We also encountered this issue. 
This can result in very long debugging sessions since its not very obvious where there error originates. 
Maybe a hint in the docs would help other people.
