### ISSUE TITLE
block formatter should use chains tx formatter if it exists

### ISSUE THREAD

**Issue by aaronmgdr** [wagmi-dev/viem#669]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.0.0

### Current Behavior

the default `formatBlock` function does not  use the chain's specific transaction format function to format transactions in block. 

furthermore if I define a custom block formatter it is not aware of the custom transaction formatter

### Expected Behavior

if a transaction formatter is defined the both the default and custom block formatters should use it. 

### Anything else?

One possibility is for `formatBlock` function signature to take an optional transactionFormatter function. 

```
function formatBlock(block: Partial<RpcBlock>, formatTransaction_: Formatter<RpcTransaction, Transaction> = formatTransaction) {}
```

**Comment by aaronmgdr** [comment]
fixed by https://github.com/wagmi-dev/viem/pull/699

**Comment by aaronmgdr** [comment]
oops wrong issue

**Comment by jxom** [comment]
This should be fixed now!

**Comment by aaronmgdr** [comment]
hmm looking on main i see formatBlock calls the standard formatTransaction method https://github.com/wagmi-dev/viem/blob/main/src/utils/formatters/block.ts#L16

Or is there something different?
