### ISSUE TITLE
bug: React Native marshalling error when using `webSocket` transport

### ISSUE THREAD

**Issue by dcposch** [wagmi-dev/viem#711]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.0.7

### Current Behavior

React Native marshalling error when trying to use the `webSocket` transport. See screenshot below.

<img width="620" alt="image" src="https://github.com/wagmi-dev/viem/assets/169280/0ae9b59b-a5cb-4eec-abfa-ca72de5bc5bd" >

.

**It looks like viem might be turning the string URL into an instance of `URL`.**

<img width="534" alt="image" src="https://github.com/wagmi-dev/viem/assets/169280/9bceaea2-4238-4724-99a9-4b08e63ac833">

The object being sent (instead of a string) appears to be a React Native URL object:

`node_modules/react-native/Libraries/Blob/URL.js`

<img width="472" alt="image" src="https://github.com/wagmi-dev/viem/assets/169280/d6882e21-9bbb-438a-aa37-1a47a44f8bf5">

### Expected Behavior

Should connect to the websocket.

Using `transport: http()` works without issue.

**Comment by jxom** [comment]
Interesting. Could be a bug in React Native, because you should be able to send a URL instance to `WebSocket` (as you can in the browser).

**Comment by dcposch** [comment]
Yeah, that sounds plausible. Is it sending the URL thru the websocket, though? This is the URL *of* the websocket endpoint, so not immediately clear why it would be sent (vs just used for connection establishment).

If it does turn out out to be the issue, the easiest solution is to send the URL as a string. LMK if viem would be open to a PR for that.

**Comment by jxom** [comment]
It should be fine. As long as we are stripping out any search parameters from the URL etc. Feel free to open a PR!

**Comment by dcposch** [comment]
@jxom done (credit to Nalin!) https://github.com/wagmi-dev/viem/pull/739
