### ISSUE TITLE
bug: Read OP revert for bytes32 or bytes32[] input.

### ISSUE THREAD

**Issue by asimashfaq** [wagmi-dev/viem#723]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.0.7

### Current Behavior

Hi I am trying to ready data from my Price Feed contract. Polygonsan / ethers is working fine

<img width="627" alt="image" src="https://github.com/wagmi-dev/viem/assets/8992522/578e8e85-1bf1-429a-83e3-573a9f5b58d6">

But when i  read via viem it give me reverted error.

<img width="711" alt="image" src="https://github.com/wagmi-dev/viem/assets/8992522/3c5ce5f4-b78b-4ad2-a82f-2b275fa71ecf">

This is my code 

<img width="1051" alt="image" src="https://github.com/wagmi-dev/viem/assets/8992522/9da0d448-b383-4d2c-af8d-06697247558f">

And i am using this method to format args for `bytes32[]`  input 
<img width="509" alt="image" src="https://github.com/wagmi-dev/viem/assets/8992522/7c651b6d-43d7-48ac-ac6f-b4009083e191">

### Expected Behavior

It should read the data from smart contract.

### Steps To Reproduce

You can confirm the data  here

https://polygonscan.com/address/0x12F513D977B47D1d155bC5ED4d295c1B10D6D027#readContract

Read method `getLatestPrice` and input `0x4555524d41490000000000000000000000000000000000000000000000000000`

**Comment by tmm** [comment]
@asimashfaq can you update the issue and replace the screenshots with the actual code? will save anyone time that is trying to look into this issue.

**Comment by asimashfaq** [comment]
I tried on codepen. Issue is coming from rainbowkit. Viem is working fine
