### ISSUE TITLE
bug: Walletclient doesnt support getAddress method expected on signer in ethers

### ISSUE THREAD

**Issue by hWonderOfTheWorld** [wagmi-dev/viem#724]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.0.7

### Current Behavior

If I am using a library that accepts `Signer` as an input hook it errors on getAddress method
Observation fixed with a quick and dirty polyfill: 

```
const client = useWalletClient()

 const polyfill = await client.data.getAddresses()

      const signer = {
        getAddress: () => polyfill[0],
        ...client.data
      }
      ```
      
    Now I can pass in this `signer` accordingly.

### Expected Behavior

I expect to `client.data.getAddress()` to return an address

### Steps To Reproduce

```const { data }  = useWalletClient()

const addy = data.getAddress()

```
I expect addy to return the address

### Anything else?

<img width="399" alt="image" src="https://github.com/wagmi-dev/viem/assets/76861306/0ac53c05-0ac9-4275-81eb-f711a62eb72d">

**Comment by tmm** [comment]
Being tracked here: https://github.com/orgs/WalletConnect/discussions/2534
