### ISSUE TITLE
bug: unformatted hex values from watchBlock with websocket transport

### ISSUE THREAD

**Issue by holic** [wagmi-dev/viem#725]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.0.6

### Current Behavior

If I `watchBlocks` with the `http` transport, I get something that looks like:

<img width="462" alt="image" src="https://github.com/wagmi-dev/viem/assets/508855/25f9871f-d0e5-4409-8134-b8dcecce56eb">

If I do the same with the `webSocket` transport, I get:

<img width="495" alt="image" src="https://github.com/wagmi-dev/viem/assets/508855/ac696756-26b2-4319-ab84-9ffb537de094">

I noticed this while using `fallback([webSocket(), http()])` and was seeing inconsistent behavior.

### Expected Behavior

The TS types appear to correspond with the `http` transport response, so I would expect the response from `webSocket` transport to be similarly converted to native types (mostly hex -> bigint).

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/edit/viem-getting-started-xpazr8

**Comment by jxom** [comment]
Can you provide a minimal repro?

**Comment by holic** [comment]
Ahh, found that it's specifically `watchBlocks`'s `onBlock` callback that shows bad data. Repro is here: https://stackblitz.com/edit/viem-getting-started-xpazr8

**Comment by holic** [comment]
I think the issue is we're not formatting block data from websocket transport:
https://github.com/wagmi-dev/viem/blob/main/src/actions/public/watchBlocks.ts#L173

With an http client, it works because it polls using `getBlock`, which does format the block:
https://github.com/wagmi-dev/viem/blob/main/src/actions/public/getBlock.ts#L105-L107

**Comment by holic** [comment]
I think this is the fix? https://github.com/wagmi-dev/viem/pull/735
