### ISSUE TITLE
bug: hashTypedData returning incorrect hash as compared to ethers counterpart

### ISSUE THREAD

**Issue by witherblock** [wagmi-dev/viem#727]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.0.7

### Current Behavior

Hey! I am working on a port of the [uniswap permit2-sdk](https://github.com/Uniswap/permit2-sdk) library from ethers to viem. (https://github.com/witherblock/permit2-sdk-viem).

Currently facing issue with the `hashTypedData` function;

When using a dynamic type in the `hashTypedData` function, the hash generated differs (and is incorrect) from what ethers generates.

Its a very obscure issue and might be because of how the types/values are created and sent to the `hashTypedData` function in my code, but I can't seem to figure out the issue.

### Expected Behavior

`hashTypedData` should generate the correct hash. Please check https://github.com/Uniswap/permit2-sdk/blob/main/src/signatureTransfer.ts for the ethers implementation and https://github.com/Uniswap/permit2-sdk/blob/main/src/signatureTransfer.test.ts for the test.

### Steps To Reproduce

Follow the steps in the README to setup the [repo](https://github.com/witherblock/permit2-sdk-viem/tree/feat/add-witness)  (make sure you are on the feat/add-witness branch). 

If run `yarn test` you will notice the tests fail due to a hash mismatch.

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://github.com/witherblock/permit2-sdk-viem/pull/1/files

**Comment by jxom** [comment]
Interesting! Our implementation of `hashTypedData` is a fork of https://github.com/MetaMask/eth-sig-util/blob/main/src/sign-typed-data.ts. So I wonder if it doesn't calculate the correct hash there too. Will have a closer look at this issue early next week!

**Comment by jxom** [comment]
I noticed that your `MockWitness` has no dependencies on the other types (`PermitTransferFrom` & `TokenPermissions`), and the `SignatureTransfer.hash` uses `PermitTransferFrom` as it's primary type which has no dependencies on `MockWitness`, which means that the `MockWitness` type is never used. 

Are you meant to set `MockWitness` as the primary type or include it as a dependency of another type?

This might be much easier to debug if you could create a super minimal reproducible example on https://new.viem.sh. Will close this for now, but I'll re-open when an minimal reproduction is provided! Thanks!
