### ISSUE TITLE
bug: Error reading contract

### ISSUE THREAD

**Issue by rick20220222** [wagmi-dev/viem#730]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.0.7

### Current Behavior

This error is prompted when calling the method of readContract.what is the reason?

![screenshot-20230619-145904](https://github.com/wagmi-dev/viem/assets/100116396/45f3f382-529d-4103-aee3-dc7221dc53fe)
![screenshot-20230619-150242](https://github.com/wagmi-dev/viem/assets/100116396/cf64da18-394e-46dc-b21e-6101e2f337e0)

**Comment by jxom** [comment]
Usually means that the ABI at the contract address doesn’t match the ABI that you provided, or maybe the function doesn’t exist on the ABI. 

Can you provide a minimal reproducible example? The ABI and contract address will help.

**Comment by rick20220222** [comment]
Contract address: https://etherscan.io/address/0x87acAE6dF21385A74ed4FB55A1a29354E9bdc6c1#code

There are three dots,
1. It can be successful after refreshing it a few times. Could it be due to the network?
2. This problem does not exist after packaging
3. This function has been online for a long time, I was just upgrading wagmi, and a problem suddenly occurred

**Comment by YVeselovskyi** [comment]
I have the same issue, you can reproduce it here, just try to connect / disconnect multiple times.

https://codesandbox.io/p/sandbox/github/WalletConnect/web3modal-examples/tree/main/html-wagmi

**Comment by YVeselovskyi** [comment]
also there is another error:

TypeError: Cannot convert undefined to a BigInt in getBalance.72

**Comment by tmm** [comment]
@YVeselovskyi doesn't seem like your issue is related as I don't see `readContract` called anywhere in the CodeSandbox you linked. If you think there is another issue, feel free to open a new issue with a reproducible example.

**Comment by jxom** [comment]
Closing for now. If the issue persists after changing the RPC provider, can you please re-open this as another issue with a minimal reproducible example via https://new.viem.sh?

Thanks!
