### ISSUE TITLE
bug: shielding internal viem client breaks third party mocking libraries

### ISSUE THREAD

**Issue by actuallymentor** [wagmi-dev/viem#750]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.0.7

### Current Behavior

Due to viem's setup, libraries like[web3-mock](https://github.com/DePayFi/web3-mock) break. See [this docs section](https://github.com/DePayFi/web3-mock#viem--wagmi). Quoting for conveineince:

> viem makes it's own internal public client inaccesible for external mocks due to their decorator pattern (see: https://github.com/wagmi-dev/viem/blob/main/src/clients/createPublicClient.ts#LL86C8-L86C21).
> That's why only the custom(window.ethereum) is compatible with web3-mock

See [this issue](https://github.com/DePayFi/web3-mock/issues/29).

### Expected Behavior

For viem to retain compatibility with third party libraries.

### Steps To Reproduce

Use `web3-mock` with viem.

### Anything else?

Thank you for maintaining this library!

**Comment by 10xSebastian** [comment]
We would need to get access to the client you are internally passing to the publicActions decorator.

**Comment by jxom** [comment]
It seems that you’re trying to pass a Client into the `provider` property of web3-mock, which I assume accepts an EIP1193 compatible provider. viem’s Client is not an EIP1193 provider.

I’m not too sure how this library works, so best to defer to the authors there. My recommendation would be to be able to pass a mocked EIP1193 provider to the `custom` transport so you can mock the Actions you need.
