### ISSUE TITLE
bug: `BlockNotFoundError` when using `waitForTransactionReceipt`

### ISSUE THREAD

**Issue by codeonblocks** [wagmi-dev/viem#760]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.1.2

### Current Behavior

I'm trying to get the `receipt` of a transaction by waiting for it using `waitForTransactionReceipt`, but when I do, I get the following error:

```bash
Version: viem@1.1.2
There was an uncaught error: BlockNotFoundError: Block at number "9218538" could not be found.
 
Version: viem@1.1.2
   at getBlock (project/node_modules/viem/src/actions/public/getBlock.ts:101:21)
   at processTicksAndRejections (node:internal/process/task_queues:95:5)
   at Object.onBlockNumber (project/node_modules/viem/src/actions/public/waitForTransactionReceipt.ts:198:31) {
   details: undefined,
   docsPath: undefined,
   metaMessages: undefined,
   shortMessage: 'Block at number "9218538" could not be found.',
   version: 'viem@1.1.2'
}
```

This is the code that's making it throw an error:
```typescript
import { createPublicClient, http } from 'viem';
import { goerli } from 'viem/chains';

export const viemClient = createPublicClient({
  chain: goerli,
  transport: http()
});

try {
  const receipt = await viemClient.waitForTransactionReceipt({ hash }); // <- Errors here
} catch (err) {
  console.error(err);
}
```

It says uncaught error from Viem, so I'm assuming it's a bug on viem's side since my app is catching the error.

### Expected Behavior

It should work and find the block without throwing a `BlockNotFoundError` error.

### Steps To Reproduce

Copy & paste my code.

**Comment by jxom** [comment]
Can you reproduce this using Alchemy as the RPC URL? The Goerli public RPC can be pretty unreliable for this.

**Comment by jxom** [comment]
Hmm, I can't seem to reproduce this on my end. 😅

**Comment by codeonblocks** [comment]
I think you're right about the Public RPC. When I tried the Alchemy one it started working properly. Must've been an issue with the public one. Thanks for your help.
