### ISSUE TITLE
bug: Multicall Batching fails to batch calls with `simulate`

### ISSUE THREAD

**Issue by arjun-io** [wagmi-dev/viem#766]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.1.4

### Current Behavior

When using multicall batching config: 
```
{
    batch: {
      multicall: true,
    },
  }
```

And calling a set of functions:
```
const myContract = getContract(...)
const [fooRes, barRes, bazRes] = await Promise.all([
  myContract.read.foo()
  myContract.simulate.bar()
  myContract.simulate.baz()
])
```

The resulting network requests have a separate `eth_call` request for each `simulate`d call.

### Expected Behavior

Simulated calls, when batched with read calls, should result in a single multicall call.

**Comment by arjun-io** [comment]
It seems that simulate is explicitly disabling batching here: https://github.com/wagmi-dev/viem/blob/839f3eaad1c04c21c83f2c54759c8595b6740896/src/actions/public/simulateContract.ts#L130

Any reason for this?

**Comment by jxom** [comment]
Think the rationale here is that the multicall doesn't accurately "simulate" a contract write given the consumer could provide fee data, sender, etc as parameters. Though, we already check for this [here](https://github.com/wagmi-dev/viem/blob/main/src/actions/public/call.ts#L175), so think it could be safe to remove it.

**Comment by arjun-io** [comment]
Ah yeah that makes sense. Agreed that the cases where a regular call can't be batched should be equivalent to a `simulate` call as well. I can whip up a quick PR to remove that line but unsure how it will affect tests...

**Comment by jxom** [comment]
Closing due to reasoning here: https://github.com/wagmi-dev/viem/pull/771#issuecomment-1685380121

**Comment by coreyar** [comment]
By disallowing batching contract simulations, users of viem will have to look for another solution when msg.sender and msg.value aren't relevant to multicalls. Since calls are being simulated and nothing is being I think it is sufficient to put the responsibility on the user to ensure that the calls are being made correctly. I can see how you wouldn't want users to accidentally write bad data with a muticall but simulate seems safe.
