### ISSUE TITLE
bug: Automine only starts when interacting with the test client

### ISSUE THREAD

**Issue by fzavalia** [wagmi-dev/viem#767]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.1.2

### Current Behavior

I'm trying to test with ganache some contract deployments. 

The ganache server is initialized like:

```
const server = ganache.server();

const provider = await new Promise<EthereumProvider>((resolve, reject) => {
  server.listen(8545, (err) => {
    if (err) {
      return reject(err);
    }

    resolve(server.provider);
  });
});
```

I have 3 different Clients:

```
const walletClient = createWalletClient({
  transport: custom(provider),
});

const publicClient = createPublicClient({
  transport: custom(provider),
});

const testClient = createTestClient({
  transport: custom(provider),
  mode: 'ganache',
});
```

When I run:

```
console.log(await testClient.getAutomine())
```

I see in the logs:

```
eth_mining
true
```

However, if I don't run that, there is no `eth_mining` being executed. As if I needed to so something with the test client for automining to start.

### Expected Behavior

I expect that if I'm using a ganache provider, or any local blockchain provider, for automining to start by default. Maybe its an issue with how I'm setting it up. But seems kind of unintuitive to have to interact with the testclient first for it to start.

### Anything else?

Loving viem ❤️

**Comment by fzavalia** [comment]
For example, If I run:

```
const testClient = createTestClient({
  transport: custom(provider),
  mode: 'ganache',
});

await testClient.setAutomine(true)
```

It logs the following:

```
miner_start
Warning: startMining called when miner was already started
```

**Comment by jxom** [comment]
The Test Client is an interface to interact with an Ethereum test node. Usually you'd set up your mining configuration when you set up the Ganache server (via `ganache.server(options)`, no? 

If the Test Client's responsibility were to set up the server, then yes, viem should be able to set those configuration. But the Test Client is purely for interaction.
