### ISSUE TITLE
bug: Typing error with signMessage and account hoisting

### ISSUE THREAD

**Issue by mattdalpi** [wagmi-dev/viem#770]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.1.6

### Current Behavior

Following steps described in [https://viem.sh/docs/actions/wallet/signMessage.html#account-hoisting](https://viem.sh/docs/actions/wallet/signMessage.html#account-hoisting) and using the example code below:
```typescript
const [account] = await window.ethereum.request({
  method: 'eth_requestAccounts'
})

const walletClient = createWalletClient({
  account,
  chain: mainnet,
  transport: custom(window.ethereum)
})

await walletClient.signMessage({ 
  message: 'hello world',
})
```

I'm getting a TypeScript error on `signMessage` (sorry, translated from my language):

> Property `account` is missing on type `'{ message: string; }` but it's required on type
> `{ account: 0x${string} | Account; }`

<img width="974" alt="Captura de Tela 2023-06-22 às 20 15 04" src="https://github.com/wagmi-dev/viem/assets/94379499/33ba1a23-5044-415d-9188-2886041081df">

### Expected Behavior

It should use the account provided on client creation for `signMessage`

**Comment by izayl** [comment]
@mattdalpi can you reproduce the problem use https://new.viem.sh

**Comment by jxom** [comment]
Can't seem to reproduce here: https://www.typescriptlang.org/play?target=99#code/JYWwDg9gTgLgBAbzgYygUwIYzQdQwG3zRgGF9g0A7GAGhQFcBnGCEOAXzgDMpW4ByAG4UQ-AFChIsRHBAZglSsQ7debISID0yABbzKjcWOQQD8ANoZkJ+tQC6cALxwMAd3nxXCgCYRXAOmIdNHR6EH90AEd6NGYACgQxOFkgiG8ALgEggH0omOYAQWsIWxhDMXYASjFjU2Y4d0JiMgpqJxR0LFwCIlJyKhgEpJdi0pph3X1MuQUlWmGYKAwDKRhM5CYWEDivSl8AoJC0MOqqmrcPBp7m-up-RmAAc0oAWVjGDEe0BLhhkHfPmhMvxgoQIA1oPhvPxxlUgA

Do you have `strict` enabled in your TSConfig? 

Closing for now, but if `strict` is also truthy, can you please provide a minimal repro and I'll reopen this issue?

**Comment by egemon** [comment]
If someone bumps into this - https://github.com/wevm/viem/issues/1666#issuecomment-1926266692
