### ISSUE TITLE
getBlock does not support RPC's transaction detail flag

### ISSUE THREAD

**Issue by comunidadio** [wagmi-dev/viem#774]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.1.4

### Current Behavior

getBlock only supports blockNumber|blockHash|blockTag.

### Expected Behavior

Support optional transactionDetail:true flag as per RPC.
This would return all transactions directly in the Block returned without having to do separate getTransaction calls for each.

### Steps To Reproduce

None.

**Comment by jxom** [comment]
You can pass `includeTransactions: true`.

**Comment by tmm** [comment]
Feel free to open a PR documenting it!
