### ISSUE TITLE
bug: HTTP request failed

### ISSUE THREAD

**Issue by it-posley** [wagmi-dev/viem#775]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.0.7

### Current Behavior

I have built a backend with NestJS which has several endpoints for my frontend (built in NextJS) to interact with.

Everything work just fine in my local environment, i can use viem to create wallets, to call smart contract's view functions (eg: balanceOf), to call smart contract's functions (eg: some trade functions that will alter state), etc.

and then i deployed into Railway.app, then everything is not working, i checked for a long time and figured out below points:

1/ cors is well set, i can call the endpoints properly when the calling functions are not using viem
2/ the node provider is normal, i tried alchemy,infura,quicknode, all got same problems
3/ i tried to switch back one of the function to use EthersJS, it works just fine

Therefore, after a long time debug, i found that the problem is come from Viem, thats why i am opening a post here and see if it's a bug or not, and see anyone can help me to fix it.

here is the error:

HTTP request failed.
﻿URL: https://arb-mainnet.g.alchemy.com/v2/xxxxx
﻿Request body: {"method":"eth_chainId"}
﻿ 
﻿Request Arguments:
﻿from:  0x27C9A0ddf367b35C751DCc2f0470C425973dE0E3
﻿to:    0xDA10009cBd5D07dd0CeCc66161FC93D7c9000da1
﻿data:  0x095ea7b30000000000000000000000006532efcc1d617e094957247d188ae6d54093718a0000000000000000000000000000000000000000000000000de0b6b3a7640000
﻿Details: fetch is not defined
﻿Version: viem@1.0.7

### Expected Behavior

expected to function properly just like it was in my local environment, updating balances, calling functions, etc.

**Comment by jxom** [comment]
You'll need to make sure to be running on Node 18+ that supports `fetch`

**Comment by monar24** [comment]
Came across a similar error; if you're working with serverless functions (aws lambda, netifly, etc) remember to make sure the function's runtime env itself is also Node 18+
