### ISSUE TITLE
bug: ContractFunctionExecutionError: Execution reverted for an unknown reason

### ISSUE THREAD

**Issue by dev-aly3n** [wagmi-dev/viem#787]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.1.7

### Current Behavior

when I call a write contract on ethers5 + wagmi it works fine. but it throw error with viem + wagmi
in both cases I get the `Execution reverted for an unknown reason` error, how ever in ethers5 version I can call a write with `mode: recklesslyUnprepared` and it opens the metamask and it works fine. how ever viem doesn't open metamask at all and just show the error. 

### Expected Behavior

how we can open the metamask like `mode: recklesslyUnprepared` in wagmi 0.1 and ethers5?

**Comment by jxom** [comment]
Thanks for reporting. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) via https://new.wagmi.sh, otherwise we cannot help you. 

Will re-open once a reproduction is provided.

**Comment by dev-aly3n** [comment]
> Thanks for reporting. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) via https://new.viem.sh, otherwise we cannot help you.
> 
> Will re-open once a reproduction is provided.

Hi thanks for checking. I made a minimal reproducible example here: https://stackblitz.com/edit/viem-getting-started-qfbnc1?file=index.ts

you can import this private key that has faucet token in this test network: `ccb16f429788e18b295c4175f1bc77da077c1790b153b6c86b16fb845bf308d4`

etherscan for provided netwrok: 
https://dashboard.tenderly.co/shared/fork/8e16246a-fb73-48b1-80f6-7f8d777752a9/transactions

**Comment by ArianHamdi** [comment]
Same here

**Comment by dev-aly3n** [comment]
@jxom 
I also made a minimal production with wagmi+wiem here (as I'm using wagmi):
https://stackblitz.com/edit/new-wagmi-9l5flp?file=src%2FApp.tsx

the testnetwork uses arbitrum chain id but different rpc url, so use the `switch to Test Network` button to add this network. and then try to write contract by clicking on `write contract` button. then you can check the console to see error logs

there is also a file `ethersjsexample.tsx` contains **ethers version of same logic that is work without any error**, both with prepare and without prepare.

thanks in advance

**Comment by jxom** [comment]
Are you sure this works in Ethers without errors? I tried to reproduce using wagmi 0.12.x, but got the following error from ethers:

```
Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="execution reverted", method="estimateGas", transaction={"from":"0x009fc422832e4fDEC24928A0cA4a16cd41AC00a2","to":"0x19b9192455351473E3833B3D3BEAd3fFF09c460B","data":"0x2e401701000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000001200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000002f2a2543b76a4166549f7aab2e75bef0aefc5b0f000000000000000000000000000000000000000000000000000000000ecb3b400000000000000000000000000000000000000000000000000000000007659da0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000078f358208685046a11c85e8ad32895ded33a2490000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001630d8e00000000000000000000000000000000000000000000000000000000000000000","accessList":null}, error={"code":-32603,"message":"Internal JSON-RPC error.","data":{"code":-32000,"message":"execution reverted","data":{"error_id":"7b8ac412-1470-4422-87cd-cab2fdfd30f7"}},"stack":"{\n  \"code\": -32603,\n  \"message\": \"Internal JSON-RPC error.\",\n  \"data\": {\n    \"code\": -32000,\n    \"message\": \"execution reverted\",\n    \"data\": {\n      \"error_id\": \"7b8ac412-1470-4422-87cd-cab2fdfd30f7\"\n    }\n  },\n  \"stack\": \"Error: Internal JSON-RPC error.\\n
```

**Comment by jxom** [comment]
Are you sure this works in Ethers without errors? I tried to reproduce using wagmi 0.12.x, but got the following error from ethers:

```
Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="execution reverted", method="estimateGas", transaction={"from":"0x009fc422832e4fDEC24928A0cA4a16cd41AC00a2","to":"0x19b9192455351473E3833B3D3BEAd3fFF09c460B","data":"0x2e401701000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000001200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000002f2a2543b76a4166549f7aab2e75bef0aefc5b0f000000000000000000000000000000000000000000000000000000000ecb3b400000000000000000000000000000000000000000000000000000000007659da0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000078f358208685046a11c85e8ad32895ded33a2490000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001630d8e00000000000000000000000000000000000000000000000000000000000000000","accessList":null}, error={"code":-32603,"message":"Internal JSON-RPC error.","data":{"code":-32000,"message":"execution reverted","data":{"error_id":"7b8ac412-1470-4422-87cd-cab2fdfd30f7"}},"stack":"{\n  \"code\": -32603,\n  \"message\": \"Internal JSON-RPC error.\",\n  \"data\": {\n    \"code\": -32000,\n    \"message\": \"execution reverted\",\n    \"data\": {\n      \"error_id\": \"7b8ac412-1470-4422-87cd-cab2fdfd30f7\"\n    }\n  },\n  \"stack\": \"Error: Internal JSON-RPC error.\\n
```

**Comment by dev-aly3n** [comment]
yes I know it can't estimate gas, but if you call the write function (maybe override the gas with 2_000_000) and confirm it in metamask, everything will work fine and you can see in blockexplorer everything working.

**Comment by jxom** [comment]
Ah okay. If you use a pure `useContractWrite` without the Prepare Hook, wagmi will validate the the contract write with `eth_call` before it sends it off. My guess is that the error is happening there. Can you try skip this step using `mode: 'prepared'`? Unsure why Tenderly isn't behaving well with `eth_call` though, as that should succeed if the actual transaction were to succeed.

```ts
const { write, error } = useContractWrite({
  mode: 'prepared',
  request: {
    abi: wagmiAbi,
    address: '0x19b9192455351473E3833B3D3BEAd3fFF09c460B',
    functionName: 'open',
    args: [order]
  }
});
```

**Comment by dev-aly3n** [comment]
That's a great help, @jxom . thank you.
now we can see the errors on tenderly with more specific details. I will share the problem here when I find out.
