### ISSUE TITLE
getFunctionSelector generates wrong function selector

### ISSUE THREAD

**Issue by wighawag** [wagmi-dev/viem#799]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.2.1

### Current Behavior

see : https://runkit.com/wighawag/649c521fc7a661000894e8ca

it returns `0xff998007`

while the correct return value should be `0xd703f50a`

See ethers here returning the same value as solidity compiler : https://runkit.com/wighawag/649c52e15e98170008f85e6e

### Expected Behavior

the correct return value should be `0xd703f50a`

### Steps To Reproduce

https://runkit.com/wighawag/649c521fc7a661000894e8ca

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://runkit.com/wighawag/649c521fc7a661000894e8ca

**Comment by hrik2001** [comment]
Hey! Can I work on this?

**Comment by tmm** [comment]
@hrik2001 go for it!

**Comment by jxom** [comment]
There is already an open PR here: https://github.com/wagmi-dev/viem/pull/749

**Comment by amandafanny** [comment]
I have same problem

**Comment by jxom** [comment]
Fixed via #974
