### ISSUE TITLE
bug: signMessage !== EthCrypto.sign ?

### ISSUE THREAD

**Issue by reslear** [wagmi-dev/viem#804]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.2.2

### Current Behavior

hi @jxom thx for the cool library) 
could you see if I do something wrong or is it a bug?

```ts
const signature = EthCrypto.sign(privateKey, message);

const signature2 = await signMessage({
  privateKey,
  message: { raw: message },
});

```

I get not same signatures 

<img width="1035" alt="Screenshot 2023-06-28 at 23 52 16" src="https://github.com/wagmi-dev/viem/assets/12596485/d1899325-6a04-459d-b420-a7f0fe21c7e7">

I wanted to reproduce your test value https://github.com/wagmi-dev/viem/blob/main/src/accounts/utils/signMessage.test.ts#L30 but found that there is an additional protection  https://github.com/pubkey/eth-crypto/blob/master/src/sign.js#L18-L19

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/edit/stackblitz-starters-hijh8v?file=index.js

**Comment by jxom** [comment]
viem's `signMessage` signs a message in EIP-141 format (meaning it prepends a keccak encoded "\x19Ethereum Signed Message:\n" string before your message). I think you may be looking for `sign`, which we don't export right now. I can quickly add it in.

**Comment by jxom** [comment]
Should be in `1.2.5` soon. Check [here](https://github.com/wagmi-dev/viem/blob/main/src/accounts/utils/signMessage.ts#L25-L26) for usage. Just replace `hashMessage(hash)`, with `hash` for your case.

**Comment by reslear** [comment]
works fine, thx ❤️ ;)
