### ISSUE TITLE
bug: Typer error: Type parameter declaration expected

### ISSUE THREAD

**Issue by francesco-gaglione** [wagmi-dev/viem#819]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.2.6

### Current Behavior

Compilation fails with this error:

``` bash
web:build: ../../node_modules/viem/node_modules/abitype/dist/types/human-readable/formatAbi.d.ts:18:35
web:build: Type error: Type parameter declaration expected.

web:build:   16 |  * @returns Human-readable ABI
web:build:   17 |  */
web:build: > 18 | export declare function formatAbi<const TAbi extends Abi | readonly unknown[]>(abi: TAbi): FormatAbi<TAbi>;
web:build:      |                                   ^
web:build:   19 | //# sourceMappingURL=formatAbi.d.ts.map
```

### Expected Behavior

Compilation success

### Steps To Reproduce

Setup a classic turborepo monorepo, install viem into one of the packages (react components libraries prefered) and try to build

### Anything else?

The issue appeared after upgrade viem from v1.0.0 to v 1.2.6. The very strange behavior is that if I try to downgrade to v1.0.0 the error persists

**Comment by jxom** [comment]
Is your TypeScript version up to date?

**Comment by francesco-gaglione** [comment]
@jxom  I'm currently using ts v5.0.4

**Comment by jxom** [comment]
can you try TS 5.1?

**Comment by francesco-gaglione** [comment]
Yes It works now. Thank you a lot
