### ISSUE TITLE
bug: [WAGMI CORE] TransactionExecutionError: An unknown RPC error occurred.

### ISSUE THREAD

**Issue by arganjava** [wagmi-dev/viem#827]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

viem@1.2.6

### Current Behavior

i am trying to integrate with walletconnect using @wagmi/core scan qr wallet success but when i try to sendTransaction error i facing error like this :
`Uncaught (in promise) TransactionExecutionError: An unknown RPC error occurred.

Request Arguments:
  from:      0x5b6183f79418E397A10779319dbE39539C21f4Ea
  to:        0x79280d9DDb2753f1fdB85924c81ECB831AB9C8c5
  value:     0.00000000001 ETH
  gas:       21000
  gasPrice:  0.0000001 gwei
  nonce:     29

Details: Unknown method(s) requested
Version: viem@1.2.6
    at getTransactionError (getTransactionError.ts:29:10)
    at sendTransaction (sendTransaction.ts:181:11)
    at async sendTransaction (chunk-LAFZBYO7.js:2789:16)
    at async Proxy.sendTrx (AppHeader.vue?t=1688176913460:118:3)`

### Expected Behavior

expected wallet connect on trust wallet show popup to confirm the transaction, but fail 

### Steps To Reproduce

```
import {
  createConfig,
  configureChains,
  connect,
  sendTransaction
} from '@wagmi/core'
import {mainnet, optimism, polygon} from '@wagmi/core/chains'

import {publicProvider} from '@wagmi/core/providers/public'
import {InjectedConnector} from '@wagmi/core/connectors/injected'
import {WalletConnectConnector} from '@wagmi/core/connectors/walletConnect'

const {publicClient, webSocketPublicClient} = configureChains(
    [polygon],
    [publicProvider()],
)

const connector = new WalletConnectConnector({
  chains: [mainnet, optimism, polygon],
  options: {
    projectId: 'a82986d2dc104e10f7e8042da7b0b542',
    showQrModal: true,
    rpc: {
      "137": "https://polygon-rpc.com"
    }
  },
})

await connect({
    connector: new InjectedConnector({chains: [polijon]}), //metamask
  })

  await sendTransaction({
    chain: polygon,
    to: "0x79280d9DDb2753f1fdB85924c81ECB831AB9C8c5",
    value: 10000000,
    chainId: 137,
    gas: 21000,
    gasPrice: 100,
    nonce: 29
  })
```

error in console web :
`Uncaught (in promise) TransactionExecutionError: An unknown RPC error occurred.

Request Arguments:
  from:      0x5b6183f79418E397A10779319dbE39539C21f4Ea
  to:        0x79280d9DDb2753f1fdB85924c81ECB831AB9C8c5
  value:     0.00000000001 ETH
  gas:       21000
  gasPrice:  0.0000001 gwei
  nonce:     29

Details: Unknown method(s) requested
Version: viem@1.2.6
    at getTransactionError (getTransactionError.ts:29:10)
    at sendTransaction (sendTransaction.ts:181:11)
    at async sendTransaction (chunk-LAFZBYO7.js:2789:16)
    at async Proxy.sendTrx (AppHeader.vue?t=1688176913460:118:3)`

please help me how to fix it

**Comment by jxom** [comment]
What wallet are you using? Looks like this error is coming from the wallet as I can't seem to reproduce this in MetaMask Mobile. Specifically, the wallet is throwing you a "Unknown method(s) requested" error via WalletConnect. It might be best to get in touch with the wallet or WalletConnect.
