### ISSUE TITLE
invalid argument 0: json: cannot unmarshal non-string into Go value of type common.Hash

### ISSUE THREAD

**Issue by gwz-365461760** [wagmi-dev/viem#832]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

viem@1.2.7

### Current Behavior

  package.json
  "viem": "^1.2.7",
   "wagmi": "^1.3.3",

myerc.ts
`
import {readContract,writeContract,prepareWriteContract,waitForTransaction} from 'wagmi/actions';
//#1
   const { request } = await prepareWriteContract({
      address: item.contracts,
      abi: approveContract.abi,
      functionName: "approve",
      args: [DepWthContract.address, parseEther(newAmount)],
      account: address,
    });

//#2
const hash = await writeContract(request);

//#3
// hash:0x8f1c602a9b329cb9817e12861905907bef08f33051b3656ea772e7d7115f7eeb
const transaction = await waitForTransaction({ hash })

`

**error**
`
Uncaught (in promise) InvalidParamsRpcError: Invalid parameters were provided to the RPC method.
Double check you have provided the correct parameters.

URL: https://matic-mumbai.chainstacklabs.com
Request body: {"method":"eth_getTransactionByHash","params":[{"hash":"0x8f1c602a9b329cb9817e12861905907bef08f33051b3656ea772e7d7115f7eeb"}]}

Details: invalid argument 0: json: cannot unmarshal non-string into Go value of type common.Hash
Version: viem@1.2.7
    at withRetry.delay.count.count (buildRequest.ts:86:21)

`

**Comment by jxom** [comment]
Can you please provide a minimal reproducible example via https://new.viem.sh or a separate GitHub repository? It could be likely that the RPC (https://matic-mumbai.chainstacklabs.com/) is providing errorneous data. Can you try a different RPC?

Will reopen when a minimal reproducible example is provided.
