### ISSUE TITLE
bug: watchContractEvent infinitely tries to get updates on a non-existent filter when the filter has expired

### ISSUE THREAD

**Issue by iuriiiurevich** [wagmi-dev/viem#836]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.2.7 (latest)

### Current Behavior

There are cases in which a filter (created with `eth_newFilter`) is no longer available (`eth_getFilterChanges` throws `filter not found)`, for example:

1. The filter has expired due to being inactive for 5 minutes (for example, if the user was offline).
2. The node on which the filter was located was dropped because of the changes in infrastructure.

Related: [QuickNode docs](https://support.quicknode.com/hc/en-us/articles/10838914856977-Error-code-32000-message-filter-not-found-), [Alchemy docs](https://docs.alchemy.com/reference/eth-newfilter).

This causes `watchContractEvent` to endlessly try to get updates on a non-existent filter.

### Expected Behavior

As stated in the [QuickNode docs](https://support.quicknode.com/hc/en-us/articles/10838914856977-Error-code-32000-message-filter-not-found-), it would be better to recreate a filter if it throws the "filter not found" error.

### Anything else?

Related: https://github.com/wagmi-dev/viem/discussions/818

**Comment by Gift-Stack** [comment]
@jxom Can I take this?

**Comment by jxom** [comment]
yes

**Comment by jxom** [comment]
Fixed via #954
