### ISSUE TITLE
bug: inconsistent results simulating as contract instance vs. publicClient.simulateContract()

### ISSUE THREAD

**Issue by evvvritt** [wagmi-dev/viem#838]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.0.7

### Current Behavior

When simulating a write method on a contract, `publicClient.simualteContract()` properly throws a contract error, but `myContractInstance.simulate...` does not.

### Expected Behavior

Both simulate contract methods should have the same results(?)

### Steps To Reproduce

1. open [stackblitz](https://stackblitz.com/edit/viem-getting-started-bucjnx?file=index.ts)
2. click both buttons and compare results in the console

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/edit/viem-getting-started-bucjnx?file=index.ts

**Comment by jxom** [comment]
Your second one doesn't have an `account`. Does that answer your question?
