### ISSUE TITLE
bug: Fix comment for "status" field in TransactionReceipt type + Fix TransactionReceipt Anchor Links

### ISSUE THREAD

**Issue by saintmaxi** [wagmi-dev/viem#849]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.2.9

### Current Behavior

1. The comments on the status field of the TransactionReceipt type say the field will be `'1' if this transaction was successful or '0' if it failed` ([LINK](https://github.com/wagmi-dev/viem/blob/2c7932d4f8c2909c9ab86e6c7a43625c03305f16/src/types/transaction.ts#L38C1-L39C18)). This is inaccurate (see Expected Behavior for correction).

2. On the [waitForTransactionReceipt](https://viem.sh/docs/actions/public/waitForTransactionReceipt.html#waitfortransactionreceipt), [getTransactionConfirmations](https://viem.sh/docs/actions/public/getTransactionConfirmations.html#gettransactionconfirmations), and [getTransactionReceipt](https://viem.sh/docs/actions/public/getTransactionReceipt.html#gettransactionreceipt) documentation pages, the link to the TransactionReceipt anchor on the types glossary page is broken (links to #transaction-receipt, actual anchor is #transactionreceipt). Similarly, the link to the glossary terms page for TransactionReceipt in the getTransactionReceipt page is incorrect ((links to #transactionreceipt, actual anchor is #transaction-receipt). Rather than jumping to the appropriate spot on the page for the TransactionReceipt type, the user is taken to the top of the page, impacting user experience.

### Expected Behavior

1. This should be changed to `'success' if this transaction was successful or 'reverted' if it failed` as indicated in the [viem docs](https://viem.sh/docs/glossary/terms.html#transaction-receipt) and as reflected in the actual values in my own experience when using objects of type TransactionReceipt. Also aligns with the default value of the type parameter TStatus: [LINK](https://github.com/wagmi-dev/viem/blob/7567f58e808b5cf67e46c151bf0569a2820be7bd/src/types/transaction.ts#L17).

2.  The links in the relevant documentation pages should be adjusted.

### Steps To Reproduce

no code execution - see links provided

### Anything else?

I have created a PR to address these two points: [PR 848](https://github.com/wagmi-dev/viem/pull/848)

**Comment by jxom** [comment]
ty!
