### ISSUE TITLE
bug: incorrect type from createConfig after 1.2.11 update

### ISSUE THREAD

**Issue by imaksp** [wagmi-dev/viem#869]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.2.12

### Current Behavior

wagmi/core's
```ts
const config  = createConfig({
      autoConnect,
      connectors,
      publicClient,
      webSocketPublicClient,
    })
```
 call resolves to incorrect type  `Config<never, never>`.

### Expected Behavior

it should resolve to correct type which is:
`Config<PublicClient, WebSocketPublicClient>`

### Steps To Reproduce

I am using @wagmi/core with Angular & getting this type issue after 1.2.11 + update.

Also webSocketPublicClient param from `configureChains` shows incorrect type inside createConfig & could be fixed type passing it like webSocketPublicClient({}), but config still resolves to Config<never, never> type (even if I don't pass websocket client)

### Anything else?

as a workaround I have downgraded to 1.2.10 version again.

**Comment by jxom** [comment]
Do you have strict mode on in your tsconfig? https://viem.sh/docs/typescript.html

**Comment by imaksp** [comment]
Hi, No its older project (currently at latest Angular & typescript) but enabling strict mode will introduce lot of ts errors, but will try with strict mode once.

**Comment by imaksp** [comment]
With strict mode error is different not sure if this is related to viem or wagmi/core:
```
Type 'Config<PublicClient<FallbackTransport>, WebSocketPublicClient<FallbackTransport>>' is not assignable to type 'Config<PublicClient, WebSocketPublicClient>'
```

**Comment by imaksp** [comment]
This is reproduction link with strict mode on you can see error in above comment in this service file on line 24:
https://stackblitz.com/edit/angular-l2o6en?file=src%2Feth.service.ts

& let me know if its wagmi config type issue, if yes will create issue in that repo.
 
& without strict mode I am getting type issue as mentioned in original comment. it was working fine till 1.2.10 version. 
but if strict mode is required will enable it after error with strict mode true is resolved.

**Comment by jxom** [comment]
Could you try reproduce this on a TS Playground with just @wagmi/core and viem? Otherwise I can check it out when I get to a computer. A minimal reproduction might help us better: https://www.typescriptlang.org/play (simply importing the modules will automatically install them).

**Comment by imaksp** [comment]
Sure, here is the TS playground link:
[Click here to view in TS playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbwFBzgYQgOwGbAOYA0KcAxlrngK5QCmaAFgIbCYDORqJtjMd5+HOAElMAKxoleAEwyZMEmNCIBfONigQQcAOQABAO6M8IYAHoytbQG4koSLERwQzOTRgE4kADYBPPFg9WGm9gRjhVdU0dAyMTcyYWVmtbcGh4BDgWbGpGAAUNADdgKRoocLUNLT1DYzMLGlMpYFYYUzBC4tLWUyyc5Ls0xzBKACMvYBJ8iCKSsojK6Jq4+sbm1vbpzqhu4bGJ5KQyNnhd8ZIRbKhGAGkaHzgAXh0AFQBRAGVngH1r14BNA40AAe9ngJC8jFYrDgrxg9HepSKJBoiGIAGIjhQAPwALnQ-DwNmIXBoPBoAHVGF4vG5ZBQABQASlRqE4WBaQ1GZzQ4xomHccH0NBG7wgJAA1m5clyJjzgHyBSQEmxyk9MfhqHRlax6cRWXAANrOFjyAVBEKMDzePxYAC6gn1Bt6VymM1K9IyjDAwFuPjxpwmFxyvvCjKtMsmHVmTNtergjJs+rhzQAdBiCY9SNxeHT8B646hGJRFLJ5JI8TAoJQaA7WUcy4ptniDfJ9MIxAoaDIsA3oB7SNrQ-aC54I3KFbXUEKRWLJTBpXsSOP+bXlAniMokMogA)

**Comment by jxom** [comment]
Ah yes, as a result of turning `strict` mode on, the types have obviously become "stricter". You'll need to further narrow the `Config` type: https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbwFBzgYQgOwGbAOYA0KcAxlrngK5QCmaAFgIbCYDORqJtjMd5+HOAElMAKxoleAEwyZMEmNEEAFSgCMANsBJotNTDEEB1GmoDKEEgGsaMVZu27g+w0gC+cbFAgg4AcgABAHdGPBBgAHoyWj8AbiRQSFhEOBBmOVsCOEgNAE88LCzWGhzgRjgPLx9-YNDwqKYWVjiE8Gh4BDgWbGpGZW8AN2ApGigKz29fQJCwyOiaCKlgVhgIsEHh0dYI7t6WxPaUsHUtEn6IIZGxysmamfr5xeXV9YvNqG3jhxJ9tuTOgBijA0GjUjGsABUoIw2El4Ddqn4hjQQH4kEgyGx4F9TiIetCANI0XJwAC8-ghAFEzBCAPoEykATRaSBoAA84aQNIxWKw4JSYPQzKMhiQaIhiABiTEUAD8AC50Pw8AAeeynJwuFVAkFgyHQ2HtAB8WRM5ksNjsJ0cegM2uBoPBVihMNYcKNRvixC4NB4NCMDtssgoAAoAJQS1CcLArI7WnS2wxwIKmCzWWzqm3OAxZEiNNjjcky-DUOj51gh4hRuAAbTSLHkSeKpUYWRy+SwAF1BNWa7toedLqMQ51GGBgETcoqcdo8b1JxUw2344P3uHO1W4GH4tXBcsAHTS5Vk0jcXjB-AjzeoRiURSyeSSRUwKCUGg9qOYx+KD6KmvyIJhDEBQaBkLBv2gEdSHLRdu2vbJ401HN4JTc10ytb4kNcas3G3Yg3HcIA

**Comment by imaksp** [comment]
Ok, got it, thanks.
& it seems with newer viem I have to enable strict mode to make it work correctly.

**Comment by imaksp** [comment]
Hi @jxom it now works properly again (on version 1.2.14) with strict mode off so it is confirmed that some kind of type issue was introduced with [1.2.11](https://github.com/wagmi-dev/viem/releases/tag/viem%401.2.11) update, &  I have also started work on enabling strict mode. Thanks.
