### ISSUE TITLE
bug: added viem to a nestjs project, creating a client returns never

### ISSUE THREAD

**Issue by shaunkh** [wagmi-dev/viem#871]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.2.12

### Current Behavior

Running a nestjs REST API and added viem. 

I created a client and wanted to test it out.

    const client: PublicClient = createPublicClient({
      chain: sepolia,
      transport: http(process.env.ALCHEMY_URL),
    });

    console.log(await client.getBlock());

But it shows an error: 
<img width="694" alt="image" src="https://github.com/wagmi-dev/viem/assets/13260261/9f0c149a-a0fa-40a3-a71b-a3db4fa46335">

I looked through other issues and I have `"strict": true` in my tsconfig
I can ts-ignore it and it works fine but ignoring everything isn't ideal.

### Expected Behavior

It should work fine without the error.

**Comment by jxom** [comment]
Most likely because you do not have `strict` mode on in your tsconfig.json. I would recommend turning it on: https://viem.sh/docs/typescript.html

**Comment by shaunkh** [comment]
I do have strict mode set to true in my tsconfig.json
This is it:
{
  "compilerOptions": {
    "module": "commonjs",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "target": "es2017",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "incremental": true,
    "skipLibCheck": true,
    "strictNullChecks": false,
    "noImplicitAny": false,
    "strictBindCallApply": false,
    "forceConsistentCasingInFileNames": false,
    "noFallthroughCasesInSwitch": false,
    "strict": true
  }
}

**Comment by jxom** [comment]
You don’t need to explicitly cast to `PublicClient`, you can remove it and the type will be inferred.
