### ISSUE TITLE
bug: hexToString on a weird hex from the chain

### ISSUE THREAD

**Issue by tunnckoCore** [wagmi-dev/viem#898]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

latest

### Current Behavior

I'm getting the transaction input data, with `getTransaction`'s input field. Which is hex, right? Yea, but it has some extra zeros in it, and so I can't decode it into correct utf8 string because of them.

that's the `input` I'm getting

```
0x0064006100740061003a0069006d006100670065002f0070006e0067003b006200610073006500360034002c006900560042004f005200770030004b00470067006f0041004100410041004e0053005500680045005500670041004100410042006700410041004100410059004300410059004100410041004400670064007a00330034004100410041004100680055006c004500510056005200340032006d004e0067004700410057006a0067004600370067005000770035004d00580063004e00420067004e007100570059004200680049006200550076002b00450034006e004a004e004c003100760033003300390069004d004d0057004700330039003700590041004d006200340078004d0069003200410047005400490073006a00770064004d00490059005a0069004300780047006c00670058006f007200670051004a0058005a007100620041004f0063006a00690035004500560056004e0069004300410068006300650065006800610041007000410065002f0044003700420046004e00410067005800430067006a0041004d006400570053004b005400350066005500430032007a00590051007400370063004c006c0045006900650048004900390069004100620053007500320069006d00670047006200790036006c00650032005600420069004100510043006a0051002b006f004e00480051006800720069005100410041004100410042004a00520055003500450072006b004a006700670067003d003d
```

In reality, the input data is

```
0x646174613a696d6167652f706e673b6261736536342c6956424f5277304b47676f414141414e535568455567414141426741414141594341594141414467647a33344141414168556c4551565234326d4e674741576a674637675077354d58634e42674e7157594268496255762b45346e4a4e4c3176333339694d4d574733393759414d6234784d693241475449736a77644d49595a694378476c67586f7267514a585a7162414f636a69354556564e694341686365656861417041652f443742464e41675843676a414d6457534b5435665543327a59517437634c6c456965484939694162537532696d67476279366c65325642694151436a512b6f4e48516872695141414141424a52553545726b4a6767673d3d
```

I tried everything i know and can't think of now, but only the dumb `.replaceAll('00', '')` works but that's a temporary solution for my case.

Thing is, some input data is with extra zeros, other isn't. So, that's the dumbest thing i've wrote..

```js
if (tx.input.startsWith('0x006400')) {
    content = hexToString(tx.input.replaceAll('00', ''));
  } else {
    content = hexToString(tx.input);
  }
```

### Expected Behavior

get proper hex string that i can convert to correct utf8

### Steps To Reproduce

Try the above. Basically

```js
const tx = await publicClient.getTransaction({
	hash: `0x70246c3f97771d33647b1a961fb3701dd44cc1e824010bcbb3d3ef0f88d42362`,
})

console.log(hexToString(tx.input)
```

Transaction hash that has "proper" input data: 0xa91be3f0b6be3b6929cedf41e9b11c08b60be1d795cc712d476ed20b3e2b00ae

Tx that has wrong one: 0x70246c3f97771d33647b1a961fb3701dd44cc1e824010bcbb3d3ef0f88d42362

**Comment by tunnckoCore** [comment]
Uh, okay, it seems like needed `decodeURIComponent(escape(`.. 

But still, maybe can be good to have this supported out of the box.

**Comment by jxom** [comment]
Transaction data isn’t predictable since the sender can set it to anything. Best to do this yourself.
