### ISSUE TITLE
bug: can't convert string 'USDT' to Byte16

### ISSUE THREAD

**Issue by aliasadolahi74** [wagmi-dev/viem#905]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.2.14

### Current Behavior

when I pass run `toBytes('USDT', {size: 16})` function I receive `TypeError: hex_.replace is not a function` error.

**Comment by jxom** [comment]
My repro test seems to pass: https://github.com/wagmi-dev/viem/compare/jxom/905?expand=1#diff-104ab750731554f209a1ae368dd0d361d061bd95ddecd16bebc0271090e3b09bR1188-R1209

Can you please provide a minimal reproducible example?
