### ISSUE TITLE
bug: publicClient doesn't work for SKALE networks

### ISSUE THREAD

**Issue by dmytrotkk** [wagmi-dev/viem#910]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.3.0

### Current Behavior

With the current implementation, all JSON RPC calls don't work in case of using `publicClient`:

```typescript
import {
    http,
    createPublicClient
} from 'viem';
import { skaleCalypso } from 'wagmi/chains';

const client = createPublicClient({
    chain: skaleCalypso,
    transport: http()
});

...

await client1.getBlockNumber(); // throws an error: Uncaught (in promise) TypeError: Cannot convert undefined to a BigInt
```

The root cause of this issue is a combination of 2 factors:

1. SKALE Chains doesn't add `application/json` in `Content-Type` header.
2. `viem` doesn't handle this case correctly in the `rpc` module.

Without `application/json` it goes to [this](https://github.com/wagmi-dev/viem/blob/2c666f452968e349a839344ee563331e20e6fdad/src/utils/rpc.ts#L110) if clause, and then passed (in string format, without being parsed) [here](https://github.com/wagmi-dev/viem/blob/2c666f452968e349a839344ee563331e20e6fdad/src/clients/transports/http.ts#L97) - both `error` and `result` are `undefined` because of this. 

### Expected Behavior

Correct behaviour when using SKALE Chains, since they are a part of `wagmi/chains` module.

### Steps To Reproduce

1. Import any SKALE Chain from `wagmi/chains` (e.g. `skaleCalypso`)
2. Init publicClient using `http` as a transport
3. Make any call

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/edit/viem-getting-started-po5zk3?file=index.ts

**Comment by jxom** [comment]
That’s a bit annoying. I’d say viem’s implementation is technically correct as without an `application/json` header, the response is essentially raw text (even though it might be represented as json). Wonder what it would take to fix this on Skale’s side.

**Comment by jxom** [comment]
Let's track this issue here: https://github.com/skalenetwork/skale-network/issues/192.
