### ISSUE TITLE
bug: The best way the get event logs value

### ISSUE THREAD

**Issue by undefinedlol** [wagmi-dev/viem#917]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

Latest

### Problem

After I upgrade wagmi to the latest version, I have to migrate from web3js to viem. 
for web3js 
```typescript
 const trans = contract?.methods?.contractMethod(params);
 const result =  trans?.send({ from: account, maxPriorityFeePerGas: baseFeePerGas, maxFeePerGas: gasPrice });
 const values = (result?.events?.LogContractmethod?.returnValues?.[1] || '').toLocaleLowerCase();
```

for viem

```typescript
const unwatch = contract.watchEvent.LogContractmethod(
          { sender: address },
          {
            onLogs(ev) {
              resolve((ev[0].args.proxy || ''));
            },
          },
        );
        contract.write.contractMethod(params).catch((err) => {
          unwatch();
          reject(err?.details || err);
        });
```

I can't get this watchEvent call resolved randomly, but for web3js, works all the time. So I want to know the best way to get event log values

### Expected Behavior

Can get event log timely

**Comment by jxom** [comment]
It’s a bit hard to tell what is going wrong when I don’t have an event definition or contract to debug. Could you please share your contract + event being emitted, or even better, a minimal reproducible example via a separate GitHub repo? 

Will re-open the issue when provided!
