### ISSUE TITLE
bug: encodeFunctionData fails on empty `bytes[]` arg

### ISSUE THREAD

**Issue by timbrinded** [wagmi-dev/viem#921]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.3.1

### Current Behavior

I am trying to construct a contract write interaction using `encodeFunctionData()`, however it it failing due to passing an empty array to a `bytes[]` typed arg.

In my specific case I am providing the args:
```
[0, []]
```
to this function parameter `feeAsset`:
```
Multilocation memory feeAsset,
```
whose struct is defined as:
```
    struct Multilocation {
        uint8 parents;
        bytes[] interior;
    }
```

giving error:
```
TypeError: hex_.replace is not a function
 ❯ padHex node_modules/.pnpm/viem@1.3.12_typescript@5.1.6/node_modules/viem/src/utils/data/pad.ts:23:20
 ❯ encodeBytes node_modules/.pnpm/viem@1.3.12_typescript@5.1.6/node_modules/viem/src/utils/abi/encodeAbiParameters.ts:203:9
 ❯ prepareParam node_modules/.pnpm/viem@1.3.12_typescript@5.1.6/node_modules/viem/src/utils/abi/encodeAbiParameters.ts:101:12
 ❯ prepareParams node_modules/.pnpm/viem@1.3.12_typescript@5.1.6/node_modules/viem/src/utils/abi/encodeAbiParameters.ts:68:25
 ❯ encodeAbiParameters node_modules/.pnpm/viem@1.3.12_typescript@5.1.6/node_modules/viem/src/utils/abi/encodeAbiParameters.ts:43:26
 ❯ Module.encodeFunctionData node_modules/.pnpm/viem@1.3.12_typescript@5.1.6/node_modules/viem/src/utils/abi/encodeFunctionData.ts:58:9
```

### Expected Behavior

Expected to be able to handle this, as have had to rely on ethers.js to do the function encoding via an interface instead. Should be able to handle empty array, or array containing "0x"

### Steps To Reproduce

It can be easiest reproduced with this:
```
console.log(encodePacked(["uint8", "bytes[]"], [0, []]))
```

**Comment by jxom** [comment]
Fixed for `encodePacked` on https://github.com/wagmi-dev/viem/commit/e3ff8509879d175f89634f4e2fcadd65ec4b7216.

Can't seem to reproduce for `encodeAbiParameters` though. Feel free to break this test I added: https://github.com/wagmi-dev/viem/commit/e3ff8509879d175f89634f4e2fcadd65ec4b7216#diff-08ffb9307c82d6b6ae2b1422acf35854405c1de6de0b3f04eb4ceb0ba76db89cR720-R742
