### ISSUE TITLE
bug: TransactionNotFoundError with waitForTransactionReceipt()

### ISSUE THREAD

**Issue by 0xIchigo** [wagmi-dev/viem#923]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

^1.3.0

### Current Behavior

I am experiencing the following TransactionNotFoundError:  
`"Transaction with hash \"0x82a3186d307ccf9df654339862b7549490040e9e0229fdac4df512b952be63e5\" could not be found.\n\nVersion: viem@1.2.15"`

This occurs with different versions, including the latest (1.4.0) while trying to build a [Web3 dapp that allows users to play Rock, Paper, Scissors, Lizard, Spock](https://github.com/0xIchigo/rpsls).

### Expected Behavior

Since the transaction [hash does exist](https://sepolia.etherscan.io/tx/0x82a3186d307ccf9df654339862b7549490040e9e0229fdac4df512b952be63e5), a transaction receipt should be returned when the `useEffect()` tries to execute the `fetchReceipt()` function. 

The `console.log("Inside the if condition for createGameHash async func");` prints to the console so it is the try/catch block that is throwing an error, which is the `TransactionNotFoundError` error

### Steps To Reproduce

This occurs with the following code:
```
const createRPSLSGame = async (
    ) => {
        if (!props.playerAddress) return;
        if (moveRef.current === undefined) return;

        const account = props.playerAddress as Address;
        let choice = Object.keys(Weapon).indexOf(moveRef.current as unknown as string) - 6;

        /*
            We generate a new salt every game such that any sort of pass the hash (PtH) attack is prevented -
            an attacker that knows the salt of the first game has no insight into the salt used in the second
            game
        */
        saltRef.current = getRandomVal() as unknown as bigint;
        forceUpdate();
        console.log(p2Address);

        const p1Hash = keccak256(encodePacked(["uint8", "uint256"], [choice, saltRef.current])) as Hex;

        try {
            const hash: Hash = await props.walletClient.deployContract({
                ...rpsContract,
                account,
                args: [p1Hash, p2Address],
                value: parseEther(stake),
            });

            setCreateGameHash(hash);
            console.log("Successfully set hash");
            console.log(`Hash: ${hash}`);
        } catch (err) {
            console.log(`Failed to deploy contract: ${err}`);
            console.log("Please ensure to pass the correct Player 2 address (with the leading 0x prefix), and the numeric value of Ether you wish to stake");
            setCreateGameHash(undefined);
        }
    }

    useEffect(() => {
        const fetchReceipt = async () => {
            if (createGameHash) {
                console.log("Inside the if condition for createGameHash async func");

                try {
                    const receipt: TransactionReceipt = await props.publicClient.waitForTransactionReceipt({ hash: createGameHash });
                    console.log('Setting game receipt!');
                    setCreateGameReceipt(receipt);
                    console.log(`Game receipt set: ${createGameReceipt}`);
                } catch (err) {
                    console.error(err);
                    // Retry after 5 seconds if an error occurred
                    setTimeout(fetchReceipt, 5000);
                }
            }
        };
        fetchReceipt();
    }, [createGameHash, props.publicClient, createGameReceipt])

    /*
        We can ignore a lot of TypeScript's warnings as this code will only execute if the
        game has been created. For a game to be created: both players must have their wallets
        connected, both players will be connected via Peer.js, and createGameReceipt will have
        a .contractAddress field
    */
    useEffect(() => {
        ;(async () => {
            if (createGameReceipt) {
                // Resetting moveInfo for the new game after Player One moves
                setMoveInfo({
                    p1Moved: true,
                    p2Moved: false,
                    p2Choice: 0,
                });
                //@ts-ignore
                setContractAddress(createGameReceipt.contractAddress);
                console.log(`Game Address: ${contractAddress}`);

                await timeSinceLastAction();

                let peerMessage: PeerMessage = {
                    _type: "ContractAddress",
                    address: contractAddress!,
                };

                connected?.send(peerMessage);

                peerMessage = {
                    _type: "Stake",
                    stakeAmount: stake,
                };

                connected?.send(peerMessage);
            }
        })
        // eslint-disable-next-line
    }, [createGameReceipt])
```

The error occurs at this line: `const receipt: TransactionReceipt = await props.publicClient.waitForTransactionReceipt({ hash: createGameHash });`

**Comment by jxom** [comment]
Mind providing a more minimal reproducible example without React and with just the required viem Actions? This will save us a lot of time to debug. Also what RPC are you using? I’m assuming this might be a load balancing sync issue.

**Comment by 0xIchigo** [comment]
I followed the [deploying-contracts example](https://github.com/wagmi-dev/viem/blob/main/examples/contracts/deploying-contracts/index.tsx) pretty closely for my set up. I do not have any RPC set up at the moment - I was under the impression that with a small, test app I would be okay with using the publicClient and walletClient on the Sepolia Testnet using the http and custom window.ethereum (to access Metamask) transports.

Here is a very rough, minimal reproducible example: https://stackblitz.com/edit/viem-getting-started-fzwqbc?file=index.ts 

I apologize for the errors as I am not familiar with stackblitz. Regardless, my main issue is that the publicClient.waitForTransactionReceipt() returns an error when the txt actually succeeds and should return a TransactionReceipt

**Comment by milaabl** [comment]
Have the same error with the latest version when using the wagmi wrapper.

wagmi @ 1.3.9, viem @ 1.4.0.

The transaction watching hook:

```
const {
    error,
    data: transactionData,
    isLoading: isTransactionDataLoading,
  } = useWaitForTransaction({
    hash: transactionHash,
    enabled: !!(transactionHash),
    onError: (err) => console.log({ err }),
  });
```


The write hook:

```
const { error, isLoading : isNewGameSessionLoading, write : createNewGameSession, data: createNewGameSessionData } = useContractWrite({
      ...contracts.factory,
      functionName: "createGameSession",
      value: parseEther(bid),
      args: [move1Hash, player2]
    });

```

The error I'm getting after the write completes successfully is:

**"Transaction with hash \"0x1588939929dc6d22b29107a08700257ec6f1c933b67040f33c4972db8ff1b095\" could not be found.\n\nVersion: viem@1.2.15"**

Though the transaction exists in the exlporer: https://sepolia.etherscan.io/tx/0x1588939929dc6d22b29107a08700257ec6f1c933b67040f33c4972db8ff1b095

Am I supposed to only fetch the transaction data this way when the transaction is pending? It used to work before in my last project, with versions as follows:

```
"viem": "~0.3.36",
"wagmi": "^1.0.6"
```

Please advice!

**Comment by jxom** [comment]
Will take a look when I’m back at the computer, but can you try use a different Sepolia RPC URL? The public url is quite brittle in terms of load balancing sync. Can you see if this happens also with an Alchemy, Infura, or Ankr URL?

**Comment by milaabl** [comment]
@jxom, just noticed that I have the same error in the app that worked perfectly a few days ago. https://github.com/milaabl/kleros-ex-d--rock-paper-scissors/blob/main/src/pages/create-game/page.tsx

A strange thing though, because I'm certainly sure it worked before. 🤔

It must be something related to Sepolia. Will try using a different provider & report back.

**Comment by milaabl** [comment]
✅ Can confirm that using a provider different from the publicProvider fixes the issue @jxom

**Comment by jxom** [comment]
Cool. Might put a note in the docs that public RPC providers can be quite brittle for mined transaction sync due to the way they handle load balancing.

**Comment by 0xIchigo** [comment]
Thanks! For future reference: I switched to Infura and tried to use the `http()` transport for Sepolia. This did not work and I ran into a number of `TransactionNotFoundError` errors. This was fixed by using the `webSocket` transport with my API key instead

**Comment by 0xIchigo** [comment]
Now I am running into the error: `ViemError: No URL was provided to the Transport. Please provide a valid RPC URL to the Transport.` It works when I paste the API key in as plaintext, however, it fails to work with a process.env variable. I am setting up the public client as follows:

```
const transport = webSocket(process.env.SEPOLIA);
const publicClient = createPublicClient({
     chain: sepolia,
     transport,
});
```
![image](https://github.com/wagmi-dev/viem/assets/96965321/9d7c27e4-0c91-4596-ab1d-bf4b9c2369a2)

And my .env file looks like: `SEPOLIA = 'wss://sepolia.infura.io/ws/v3/<api key>';`

Should I open up a new issue, or is there something that I am missing with setting up the RPC API key and viem? @jxom

**Comment by tmm** [comment]
> it fails to work with a process.env variable

This seems like an environment issue on your end, not a problem with viem. If you can create a minimal reproduction, feel free to create a new issue, but I would investigate how your environment variables are being loaded first.

**Comment by 0xIchigo** [comment]
@tmm The weird thing is that there isn't much to reproduce:

```
import { webSocket, createPublicClient } from "viem";
import { sepolia } from "viem/chains";
import dotenv from "dotenv";
dotenv.config();

const transport = webSocket(process.env.SEPOLIA as string);
const publicClient = createPublicClient({
    chain: sepolia,
    transport
});
```

And my .env file has the following: `SEPOLIA='wss://sepolia.infura.io/ws/v3/<api key>'`

In my console I get confirmation that `info Loaded env from ...\.env`. This seems like the correct way to load from an .env file so I was wondering if maybe the issue lies in how viem handles a `webSocket` transport that uses an .env variable? Or am I missing something in my config?

**Comment by 0xIchigo** [comment]
Never mind @tmm @jxom - it looks like there was an issue with the API key itself and generating a new one fixed everything. I appreciate all the help, thank you!

**Comment by milaabl** [comment]
@0xIchigo , did you try console logging the value of that env? It looks like the proper way to reference the .env variable in React is process.env.REACT_APP_PUBLIC_NAME_OF_YOUR_VARIABLE. It might be VITE_NAME_OF_YOUR_VARIABLE and NEXT_PUBLIC_NAME_OF_VAR for Vite or NextJS

**Comment by 0xIchigo** [comment]
@milaabl yes, thank you for the help! The issue was with the API key itself but it's all sorted now, thanks

**Comment by Songkeys** [comment]
> Cool. Might put a note in the docs that public RPC providers can be quite brittle for mined transaction sync due to the way they handle load balancing.

We host the chain and rpc ourselves. We have the same problem because three rpc servers are there for load balancing. Is there any way to solve this on the client side? like backoff retry strategy? As we can't switch to another provider.
