### ISSUE TITLE
bug: All Contract read data returns ContractFunctionExecutionError: The contract function "approve" returned no data ("0x")

### ISSUE THREAD

**Issue by emmajane1313** [wagmi-dev/viem#930]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

`Wagmi: 1.3.2`

### Current Behavior

Every useContractRead hook returns this error message: ContractFunctionExecutionError: The contract function "approve" returned no data ("0x")

On polygonscan and with ethers when querying the same contracts, on the same network (137) with the same parameters the correct values are returned. 

I have verified the abi and functionnames and args being passed are all correct. I also tried passing in the account variable with my address (although anyone can call the read functions i'm querying) and this did not solve it. 

Here is the code:

  ```
const { data: oracleData, error: oracleError } = useContractRead({
    address:"0x0e92989b083b2ea0328eba2db5c9ad3819e64794",
    abi: [
      {
        inputs: [
          {
            internalType: "address",
            name: "_tokenAddress",
            type: "address",
          },
        ],
        name: "getRateByAddress",
        outputs: [
          {
            internalType: "uint256",
            name: "",
            type: "uint256",
          },
        ],
        stateMutability: "view",
        type: "function",
      },
    ],
    functionName: "getRateByAddress",
    args: [
      "0xc2132d05d31c914a87c6611c10748aeb04b58e8f"
    ],
    enabled: Boolean(
      ACCEPTED_TOKENS.find(([_, token]) => token === checkoutCurrency)?.[2]
    ),
    chainId: 137,
  });


```

Also for this read function:

```
  const { address: addressConnected, isConnected } = useAccount();


const { data, error } = useContractRead({
    address: "0xc2132d05d31c914a87c6611c10748aeb04b58e8f",
    abi: [
      {
        inputs: [
          {
            internalType: "address",
            name: "owner",
            type: "address",
          },
          {
            internalType: "address",
            name: "spender",
            type: "address",
          },
        ],
        name: "allowance",
        outputs: [
          {
            internalType: "uint256",
            name: "",
            type: "uint256",
          },
        ],
        stateMutability: "view",
        type: "function",
      },
    ],
    functionName: "allowance",
    args: [addressConnected as `0x${string}`,"0x2F4a5544E8436ced2EE71CD3FfF76Cb6DAf9cf6F"],
    enabled:
      Boolean(address) &&
      Boolean(approved) &&
      Boolean(checkoutCurrency) &&
      Boolean(cartItems?.length > 0),
    chainId: 137,
  })
```

Full Error:
client.js:1 ContractFunctionExecutionError: Cannot decode zero data ("0x") with ABI parameters.

Raw Call Arguments:
  to:    0x0e92989b083b2ea0328eba2db5c9ad3819e64794
  data:  0x39076e39000000000000000000000000c2132d05d31c914a87c6611c10748aeb04b58e8f
 
Contract Call:
  address:   0x0e92989b083b2ea0328eba2db5c9ad3819e64794
  function:  getRateByAddress(address _tokenAddress)
  args:                      (0xc2132d05d31c914a87c6611c10748aeb04b58e8f)

Docs: https://viem.sh/docs/contract/readContract.html
Version: viem@1.2.10
    at getContractError (getContractError.js:24:1)
    at readContract (readContract.js:56:31)
    at async Object.eval [as queryFn] (index.j

**Comment by jxom** [comment]
I seem to be getting the correct response back for the example you provided (`1000000000000000000n`) with `readContract`. Can you please provide a minimal reproducible example via https://new.viem.sh?

This issue may also be related: https://github.com/wagmi-dev/viem/issues/663

**Comment by emmajane1313** [comment]
Hmm its a bit strange won't reproduce on there. It seems something with my local might have changed because now all of my code bases are returning 0x in dev environment for even my old wagmi projects that were previosuly working. Anyway I've switched to solely using the viem and it works fine.

**Comment by jxom** [comment]
Could also be an issue with the RPC Provider: https://github.com/wagmi-dev/viem/issues/936#issuecomment-1650967812

Try swap around the RPC URLs!
