### ISSUE TITLE
bug: Cannot access OnLogsParameter type from watchContractEvent

### ISSUE THREAD

**Issue by sanjayprabhu** [wagmi-dev/viem#938]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.4.1

### Current Behavior

The `OnLogsParameter` type from `watchContractEvent.ts` is not exported publicly, only the one from `watchContractEvent.ts` is https://github.com/wagmi-dev/viem/blob/89be5ec216bc928ddf163ef0e4efb2a0189c1f31/src/actions/index.ts#L164.

So, I'm not able to pass functions into watchContractEvent. 

### Expected Behavior

Be able to import the `OnLogsParameter` type from `watchContractEvent.ts` 

### Steps To Reproduce

Something like 
```typescript

import { OnLogsParameter } from "viem";

public watch() {
    this.publicClient.watchContractEvent({
      address: '0x...',
      abi: SomeContract.abi
      onLogs: this.ProcessLogs.bind(this),
    });
}

private async(logs: OnLogsParameter<typeof SomeContract.abi>) {
    // do something
}

```

fails with `Type ... does not satisfy the constraint  AbiEvent`. This is because OnLogsParameter is expecting `TAbiEvent extends AbiEvent | undefined = undefined` instead of `TAbi extends Abi | readonly unknown[] = readonly unknown[]`

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://replit.com/@sanjayprabhu/GlisteningWellwornConditionals?v=1#index.ts

**Comment by alexfertel** [comment]
@jxom What would the solution here look like? I'm happy to give this a try, but I'm unsure of the path you'd want to take. (Also, the replit link is broken 🙈 )

**Comment by jxom** [comment]
Think we just need to export the type from `src/index.ts`!

**Comment by alexfertel** [comment]
> Think we just need to export the type from `src/index.ts`!

I think we can't since there would be a duplicate identifier. `OnLogsParameter` is already being exported from `watchEvent.js`.

**Comment by jxom** [comment]
Yeah noticed. I think the path forward here would be to prefix the types with `WatchContractEvent*`, and same with the types in `watchEvent`. 

Instead of removing the original `OnLogsParameters`, let’s leave the export and mark it as `/** @deprecated */`.

**Comment by alexfertel** [comment]
> Yeah noticed. I think the path forward here would be to prefix the types with `WatchContractEvent*`, and same with the types in `watchEvent`.
> 
> Instead of removing the original `OnLogsParameters`, let’s leave the export and mark it as `/** @deprecated */`. We can remove them in the next major version.

Sounds good! Will work on that then.

**Comment by sanjayprabhu** [comment]
Thank you for the quick fix 🙏
