### ISSUE TITLE
bug: args stripped from [[1n]] to []

### ISSUE THREAD

**Issue by 0xartcro** [wagmi-dev/viem#939]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.3.9

### Current Behavior

```
ContractFunctionExecutionError: The contract function "stake" reverted with the following reason:
Must stake at least 1

Contract Call:
  address:   0x88e...
  function:  stake(uint256[] tokens)
  args:           ([])
  sender:    0x93...
```

### Expected Behavior

Correct arguments set.

### Steps To Reproduce

```
const prepareStake = usePrepareContractWrite({
        ...contractConfig,
        functionName: 'stake',
        args: [[1n]],
        value: 1n,
    })
```

ABI:
```
  {
    "inputs": [
      {
        "internalType": "uint256[]",
        "name": "tokens",
        "type": "uint256[]"
      }
    ],
    "name": "stake",
    "outputs": [],
    "stateMutability": "payable",
    "type": "function"
  },
```

Setting an array with a single `1n` element (weirdly it works fine with any other number, 1n seems to be the only problematic one) incorrectly triggers an error thinking the array was empty. Works fine when there is 2 or more elements.

**Comment by 0xartcro** [comment]
@jxom might the issue be related to wagmi's `usePrepareContractWrite` then?

**Comment by tmm** [comment]
`usePrepareContractWrite` passes the `args` straight through to `simulateContract` (via [`prepareWriteContract`](https://github.com/wagmi-dev/wagmi/blob/main/packages/core/src/actions/contracts/prepareWriteContract.ts#L91)). The best way for us to help you out is if you are able to reproduce - by breaking the test in https://github.com/wagmi-dev/viem/commit/6e11c8a5906f2fed0797ea0f1151c64c67060157 or using [new.viem.sh](https://new.viem.sh).

**Comment by 0xartcro** [comment]
> `usePrepareContractWrite` passes the `args` straight through to `simulateContract` (via [`prepareWriteContract`](https://github.com/wagmi-dev/wagmi/blob/main/packages/core/src/actions/contracts/prepareWriteContract.ts#L91)). The best way for us to help you out is if you are able to reproduce - by breaking the test in [6e11c8a](https://github.com/wagmi-dev/viem/commit/6e11c8a5906f2fed0797ea0f1151c64c67060157) or using [new.viem.sh](https://new.viem.sh).

https://stackblitz.com/edit/new-wagmi-2t5etm

Here is example project using new.viem.sh

**Comment by 0xartcro** [comment]
Try this
```
contract Playground3{
    function stake(uint256[] calldata tokens) external payable {}
}
```

Looks like it fails when function name is 'stake', works fine for your sample.

**Comment by 0xartcro** [comment]
> `usePrepareContractWrite` passes the `args` straight through to `simulateContract` (via [`prepareWriteContract`](https://github.com/wagmi-dev/wagmi/blob/main/packages/core/src/actions/contracts/prepareWriteContract.ts#L91)). The best way for us to help you out is if you are able to reproduce - by breaking the test in [6e11c8a](https://github.com/wagmi-dev/viem/commit/6e11c8a5906f2fed0797ea0f1151c64c67060157) or using [new.viem.sh](https://new.viem.sh).

Let me know if you need any more details

**Comment by tmm** [comment]
What is the address of the wallet you are connected with?

**Comment by 0xartcro** [comment]
> What is the address of the wallet you are connected with?

0x93EeF15E5d6f1a0c238F93A274E1b9514F260c4C
