### ISSUE TITLE
bug: 'WebSocket' can only be imported by using a default import.

### ISSUE THREAD

**Issue by nzhl** [wagmi-dev/viem#940]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.4.1

### Current Behavior

i am having exactly the same issue as #457  mentioned. I am using typescript `5.0.4` and this is my tsconfig:

```
{
  "compilerOptions": {
    "target": "es2022",
    "module": "node16",
    "lib": [
      "ES2022",
      "DOM"
    ],
    "moduleResolution": "node16",
    "rootDir": ".",
    "outDir": "build",
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "importHelpers": true,
    "alwaysStrict": true,
    "sourceMap": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitAny": false,
    "noImplicitThis": false,
    "strictNullChecks": false
  },
  "include": [
    "src/**/*",
    "__tests__/**/*"
  ]
}
```

### Steps To Reproduce

Check https://github.com/wagmi-dev/viem/issues/457#issuecomment-1555964318 for a minimum reproduce

**Comment by jxom** [comment]
Thanks for reporting. Can you please share a minimal reproducible example via a separate repository? The one in that comment links to a 404.

**Comment by IgnacioPastor-Improbable** [comment]
I solved this by trial an error with this tsconfig
{
  "compilerOptions": {
    "target": "ESNext",
    "module": "CommonJS",
    "moduleResolution": "node",
    "outDir": "dist",
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "strict": false,
    "noImplicitAny": false,
    "allowSyntheticDefaultImports": true
  },
}
Hope it helps

**Comment by jxom** [comment]
Closing for now. Will reopen when a minimal repro is provided.

**Comment by Zil-B** [comment]
I had the same issue - there were a bunch of errors relating to the ``isomorphic-ws`` and ``ws`` packages

Installing @types/ws fixed it

**Comment by Zil-B** [comment]
Here's a minimal repo for reproduction - https://github.com/Zil-B/viem-websocket-type-bug

I guess moving @types/ws from Viem's devDependencies to dependencies instead should fix it.

**Comment by tmm** [comment]
@Zil-B good spot! Want to open a PR to get credit?

**Comment by Zil-B** [comment]
> @Zil-B good spot! Want to open a PR to get credit?

Affirmative! Tested locally with new viem package and working as expected without needing to manually install `@types/ws`

https://github.com/wagmi-dev/viem/pull/967
