### ISSUE TITLE
Turborepo, next js, wagmi and rainbowkit webpack error bug: <title>

### ISSUE THREAD

**Issue by IbrahimIjai** [wagmi-dev/viem#950]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.3.9

### Current Behavior

I am just trying to set up a project using turborepo and next js, but after getting my wagmi and rainbowkit setup and wrapped up around my provider, I keep on getting this error. Please how can I fix????

error ../../node_modules/viem/dist/cjs/utils/abi/getAbiItem.js
Module parse failed: Unexpected character '' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)

**Comment by jxom** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) via a separate repository.
