### ISSUE TITLE
bug: "Property 'name' is incompatible with index signature." for TypedDataDomain

### ISSUE THREAD

**Issue by carlos-menezes** [wagmi-dev/viem#962]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.2.6

### Current Behavior

I am trying to use the `signTypedMethod` on a `WalletClient` to sign data.

```ts
const signature = await walletClient.signTypedData({
    account: walletClient.account.address,
    message: {
      from: forwardRequest.from,
      to: forwardRequest.to,
      contents: JSON.stringify(forwardRequest.data),
    },
    domain: {
      name: 'Test',
      version: '0.0.1',
      chainId: NETWORK_ID,
      verifyingContract,
    } as const,
    primaryType: 'ForwardRequest',
    types: {
      EIP712Domain: EIP712DomainType,
      ForwardRequest: ForwardRequestType,
    } as const,
  })
```

However, I get this error:

> Type '{ readonly name: "Test"; readonly version: "0.0.1"; readonly chainId: number; readonly verifyingContract: string; }' is not assignable to type '{ [x: string]: [`Error: Cannot convert unknown type '${string}' to primitive type.`]; }'.
  Property 'name' is incompatible with index signature.
    Type 'string' is not assignable to type '[`Error: Cannot convert unknown type '${string}' to primitive type.`]'.ts(2322)
    
    
![image](https://github.com/wagmi-dev/viem/assets/36506580/a5484616-efde-4136-bc8d-f9ed792b67e8)

### Expected Behavior

I should be able to create the `domain` object with no issues.

**Comment by anader123** [comment]
Hi @carlos-menezes I'm running into a similar TS error. Were you able to figure out what is causing this issue?
